
= XProc Test Results for MorganaXProc

Passed 910 of 913 tests (99.67%) on 17 Jan 2016 at 05:51p.

:toc: right

[cols="<h,<,<h,<"]
|=============================================
4+<h|Processor information
|Name|MorganaXProc|Language|en
|Vendor|xml-project Achim Berndzen|XProc version|1.0
|Vendor URI|http://www.xml-project.com|XPath version|1.0 2.0
|Version|0.95-9 (public beta) with SaxonXSLTConnector(Saxon HE 9.6.0.8)|PSVI Supported|false
|=============================================


== Required tests

Passed 602 of 602 tests (100.00%).

[role="pass"]
=== PASS Test p:add-attribute #001
http://tests.xproc.org/tests/required/add-attribute-001.xml

[role="pass"]
=== PASS Test p:add-attribute #002
http://tests.xproc.org/tests/required/add-attribute-002.xml

[role="pass"]
=== PASS Test add attribute 003
http://tests.xproc.org/tests/required/add-attribute-003.xml

[role="pass"]
=== PASS Test p:add-attribute #004
http://tests.xproc.org/tests/required/add-attribute-004.xml

[role="pass"]
=== PASS Test p:add-attribute #005
http://tests.xproc.org/tests/required/add-attribute-005.xml

[role="pass"]
=== PASS Test p:add-attribute #006
http://tests.xproc.org/tests/required/add-attribute-006.xml

[role="pass"]
=== PASS Test p:add-attribute #007
http://tests.xproc.org/tests/required/add-attribute-007.xml

[role="pass"]
=== PASS Test add-xml-base-001
http://tests.xproc.org/tests/required/add-xml-base-001.xml

[role="pass"]
=== PASS Test add-xml-base-002
http://tests.xproc.org/tests/required/add-xml-base-002.xml

[role="pass"]
=== PASS Test add-xml-base-003
http://tests.xproc.org/tests/required/add-xml-base-003.xml

[role="pass"]
=== PASS Test add-xml-base-004
http://tests.xproc.org/tests/required/add-xml-base-004.xml

[role="pass"]
=== PASS Test add-xml-base-005
http://tests.xproc.org/tests/required/add-xml-base-005.xml

[role="pass"]
=== PASS Test add-xml-base-006
http://tests.xproc.org/tests/required/add-xml-base-006.xml

[role="pass"]
=== PASS Test base-uri #001
http://tests.xproc.org/tests/required/base-uri-001.xml

[role="pass"]
=== PASS Test base-uri #002
http://tests.xproc.org/tests/required/base-uri-002.xml

[role="pass"]
=== PASS Test base-uri #003
http://tests.xproc.org/tests/required/base-uri-003.xml

[role="pass"]
=== PASS Test choose #001
http://tests.xproc.org/tests/required/choose-001.xml

[role="pass"]
=== PASS Test choose #002
http://tests.xproc.org/tests/required/choose-002.xml

[role="pass"]
=== PASS Test choose #003
http://tests.xproc.org/tests/required/choose-003.xml

[role="pass"]
=== PASS Test choose #004
http://tests.xproc.org/tests/required/choose-004.xml

[role="pass"]
=== PASS Test choose #005
http://tests.xproc.org/tests/required/choose-005.xml

[role="pass"]
=== PASS Test choose #006
http://tests.xproc.org/tests/required/choose-006.xml

[role="pass"]
=== PASS Test choose #007
http://tests.xproc.org/tests/required/choose-007.xml

[role="pass"]
=== PASS Test choose #008
http://tests.xproc.org/tests/required/choose-008.xml

[role="pass"]
=== PASS Test compare
http://tests.xproc.org/tests/required/compare-001.xml

[role="pass"]
=== PASS Test compare
http://tests.xproc.org/tests/required/compare-002.xml

[role="pass"]
=== PASS Test compare
http://tests.xproc.org/tests/required/compare-003.xml

[role="pass"]
=== PASS Test compare
http://tests.xproc.org/tests/required/compare-004.xml

[role="pass"]
=== PASS Test compare
http://tests.xproc.org/tests/required/compare-005.xml

[role="pass"]
=== PASS Test of the p:count Step
http://tests.xproc.org/tests/required/count-001.xml

[role="pass"]
=== PASS Test of the p:count Step #002
http://tests.xproc.org/tests/required/count-002.xml

[role="pass"]
=== PASS Test count 003
http://tests.xproc.org/tests/required/count-003.xml

[role="pass"]
=== PASS Test count 004
http://tests.xproc.org/tests/required/count-004.xml

[role="pass"]
=== PASS Test p:data #001
http://tests.xproc.org/tests/required/data-001.xml

[role="pass"]
=== PASS Test p:data #002
http://tests.xproc.org/tests/required/data-002.xml

[role="pass"]
=== PASS Test p:data #003
http://tests.xproc.org/tests/required/data-003.xml

[role="pass"]
=== PASS Test p:data #004
http://tests.xproc.org/tests/required/data-004.xml

[role="pass"]
=== PASS Test p:data #005
http://tests.xproc.org/tests/required/data-005.xml

[role="pass"]
=== PASS Test p:data #006
http://tests.xproc.org/tests/required/data-006.xml

[role="pass"]
=== PASS Test p:data #007
http://tests.xproc.org/tests/required/data-007.xml

[role="pass"]
=== PASS Test p:data #008
http://tests.xproc.org/tests/required/data-008.xml

[role="pass"]
=== PASS Test p:declare-step-001
http://tests.xproc.org/tests/required/declare-step-001.xml

[role="pass"]
=== PASS Test p:declare-step-002
http://tests.xproc.org/tests/required/declare-step-002.xml

[role="pass"]
=== PASS Test p:declare-step-003
http://tests.xproc.org/tests/required/declare-step-003.xml

[role="pass"]
=== PASS Test p:declare-step-004
http://tests.xproc.org/tests/required/declare-step-004.xml

[role="pass"]
=== PASS Test p:declare-step-005
http://tests.xproc.org/tests/required/declare-step-005.xml

[role="pass"]
=== PASS Test p:declare-step-006
http://tests.xproc.org/tests/required/declare-step-006.xml

[role="pass"]
=== PASS Test p:declare-step-007
http://tests.xproc.org/tests/required/declare-step-007.xml

[role="pass"]
=== PASS Test p:declare-step-008
http://tests.xproc.org/tests/required/declare-step-008.xml

[role="pass"]
=== PASS Test p:declare-step-009
http://tests.xproc.org/tests/required/declare-step-009.xml

[role="pass"]
=== PASS Test p:declare-step-010
http://tests.xproc.org/tests/required/declare-step-010.xml

[role="pass"]
=== PASS Test p:declare-step-011
http://tests.xproc.org/tests/required/declare-step-011.xml

[role="pass"]
=== PASS Test delete-001
http://tests.xproc.org/tests/required/delete-001.xml

[role="pass"]
=== PASS Test delete-002
http://tests.xproc.org/tests/required/delete-002.xml

[role="pass"]
=== PASS Test delete-003
http://tests.xproc.org/tests/required/delete-003.xml

[role="pass"]
=== PASS Test delete-004
http://tests.xproc.org/tests/required/delete-004.xml

[role="pass"]
=== PASS Test delete-005
http://tests.xproc.org/tests/required/delete-005.xml

[role="pass"]
=== PASS Test directory-list-001
http://tests.xproc.org/tests/required/directory-list-001.xml

[role="pass"]
=== PASS Test directory-list-002
http://tests.xproc.org/tests/required/directory-list-002.xml

[role="pass"]
=== PASS Test p:document-001
http://tests.xproc.org/tests/required/document-001.xml

[role="pass"]
=== PASS Test ebv-001
http://tests.xproc.org/tests/required/ebv-001.xml

[role="pass"]
=== PASS Test ebv-002
http://tests.xproc.org/tests/required/ebv-002.xml

[role="pass"]
=== PASS Test err:XC0002 #001
http://tests.xproc.org/tests/required/err-c0002-001.xml

[role="pass"]
=== PASS Test for err:XC0003 #001
http://tests.xproc.org/tests/required/err-c0003-001.xml

[role="pass"]
=== PASS Test for err:XC0003 #002
http://tests.xproc.org/tests/required/err-c0003-002.xml

[role="pass"]
=== PASS Test err:XC0004 #001
http://tests.xproc.org/tests/required/err-c0004-001.xml

[role="pass"]
=== PASS Test err:XC0005 #001
http://tests.xproc.org/tests/required/err-c0005-001.xml

[role="pass"]
=== PASS Test err:XC0005 #002
http://tests.xproc.org/tests/required/err-c0005-002.xml

[role="pass"]
=== PASS Test for err:XC0006 #001
http://tests.xproc.org/tests/required/err-c0006-001.xml

[role="pass"]
=== PASS Test for err:XC0010 #001
http://tests.xproc.org/tests/required/err-c0010-001.xml

[role="pass"]
=== PASS Test for err:XC0010 #002
http://tests.xproc.org/tests/required/err-c0010-002.xml

[role="pass"]
=== PASS Test err:XC0012 (p:directory-list on an inaccessible directory).
http://tests.xproc.org/tests/required/err-c0012-001.xml

[role="pass"]
=== PASS Test for err:XC0013 #001
http://tests.xproc.org/tests/required/err-c0013-001.xml

[role="pass"]
=== PASS Test err:XC0014 #001
http://tests.xproc.org/tests/required/err-c0014-001.xml

[role="pass"]
=== PASS Test err:XC0014 #002
http://tests.xproc.org/tests/required/err-c0014-002.xml

[role="pass"]
=== PASS Test err:XC0017 (p:directory-list with a non-directory path).
http://tests.xproc.org/tests/required/err-c0017-001.xml

[role="pass"]
=== PASS Test for err:XC0019 - 001
http://tests.xproc.org/tests/required/err-c0019-001.xml

[role="pass"]
=== PASS Test err:XC0020 #001
http://tests.xproc.org/tests/required/err-c0020-001.xml

[role="pass"]
=== PASS Test err:XC0020 #003
http://tests.xproc.org/tests/required/err-c0020-003.xml

[role="pass"]
=== PASS Test err:XC0020 #004
http://tests.xproc.org/tests/required/err-c0020-004.xml

[role="pass"]
=== PASS Test err:XC0020 #005
http://tests.xproc.org/tests/required/err-c0020-005.xml

[role="pass"]
=== PASS Test err:XC0020 #006
http://tests.xproc.org/tests/required/err-c0020-006.xml

[role="pass"]
=== PASS Test err:XC0020 #007
http://tests.xproc.org/tests/required/err-c0020-007.xml

[role="pass"]
=== PASS Test err:XC0022 #001
http://tests.xproc.org/tests/required/err-c0022-001.xml

[role="pass"]
=== PASS Test for err:XC0023 #001
http://tests.xproc.org/tests/required/err-c0023-001.xml

[role="pass"]
=== PASS Test for err:XC0023 #002
http://tests.xproc.org/tests/required/err-c0023-002.xml

[role="pass"]
=== PASS Test for err:XC0023 #003
http://tests.xproc.org/tests/required/err-c0023-003.xml

[role="pass"]
=== PASS Test for err:XC0023 #004
http://tests.xproc.org/tests/required/err-c0023-004.xml

[role="pass"]
=== PASS Test for err:XC0023 #005
http://tests.xproc.org/tests/required/err-c0023-005.xml

[role="pass"]
=== PASS Test for err:XC0023 #006
http://tests.xproc.org/tests/required/err-c0023-006.xml

[role="pass"]
=== PASS Test for err:XC0023 #007
http://tests.xproc.org/tests/required/err-c0023-007.xml

[role="pass"]
=== PASS Test for err:XC0023 #008
http://tests.xproc.org/tests/required/err-c0023-008.xml

[role="pass"]
=== PASS Test for err:XC0023 #009
http://tests.xproc.org/tests/required/err-c0023-009.xml

[role="pass"]
=== PASS Test for err:XC0025 #001
http://tests.xproc.org/tests/required/err-c0025-001.xml

[role="pass"]
=== PASS Test for err:XC0025 #002
http://tests.xproc.org/tests/required/err-c0025-002.xml

[role="pass"]
=== PASS Test for err:XC0027 - 001
http://tests.xproc.org/tests/required/err-c0027-001.xml

[role="pass"]
=== PASS Test for err:XC0027 - 002
http://tests.xproc.org/tests/required/err-c0027-002.xml

[role="pass"]
=== PASS Test for err:XC0027 - 003
http://tests.xproc.org/tests/required/err-c0027-003.xml

[role="pass"]
=== PASS Test err:XC0028 #001
http://tests.xproc.org/tests/required/err-c0028-001.xml

[role="pass"]
=== PASS Test err:XC0029 #001
http://tests.xproc.org/tests/required/err-c0029-001.xml

[role="pass"]
=== PASS Test err:XC0029 #002
http://tests.xproc.org/tests/required/err-c0029-002.xml

[role="pass"]
=== PASS Test err:XC0030 #001
http://tests.xproc.org/tests/required/err-c0030-001.xml

[role="pass"]
=== PASS Test for err:XC0039 - 001
http://tests.xproc.org/tests/required/err-c0039-001.xml

[role="pass"]
=== PASS Test err:XC0040 #001
http://tests.xproc.org/tests/required/err-c0040-001.xml

[role="pass"]
=== PASS Test for err:XC0050 - 001
http://tests.xproc.org/tests/required/err-c0050-001.xml

[role="pass"]
=== PASS Test err:XC0051 #001
http://tests.xproc.org/tests/required/err-c0051-001.xml

[role="pass"]
=== PASS Test err:XC0052 #001
http://tests.xproc.org/tests/required/err-c0052-001.xml

[role="pass"]
=== PASS Test err:XC0052 #002
http://tests.xproc.org/tests/required/err-c0052-002.xml

[role="pass"]
=== PASS Test for err:XC0056 - 001
http://tests.xproc.org/tests/required/err-c0056-001.xml

[role="pass"]
=== PASS Test for err:XC0056 - 002
http://tests.xproc.org/tests/required/err-c0056-002.xml

[role="pass"]
=== PASS Test for err:XC0058 - 001
http://tests.xproc.org/tests/required/err-c0058-001.xml

[role="pass"]
=== PASS Test err:XC0059 #001
http://tests.xproc.org/tests/required/err-c0059-001.xml

[role="pass"]
=== PASS Test err:XC0059 #002
http://tests.xproc.org/tests/required/err-c0059-002.xml

[role="pass"]
=== PASS Test err:XC0062 #001
http://tests.xproc.org/tests/required/err-c0062-001.xml

[role="pass"]
=== PASS Test err:XD0001 #001
http://tests.xproc.org/tests/required/err-d0001-001.xml

[role="pass"]
=== PASS Test err:XD0001 #002
http://tests.xproc.org/tests/required/err-d0001-002.xml

[role="pass"]
=== PASS Test err:XD0003
http://tests.xproc.org/tests/required/err-d0003-001.xml

[role="pass"]
=== PASS Test err:XD0004
http://tests.xproc.org/tests/required/err-d0004-001.xml

[role="pass"]
=== PASS Test err:XD0005
http://tests.xproc.org/tests/required/err-d0005-001.xml

[role="pass"]
=== PASS Test err:XD0006 #001
http://tests.xproc.org/tests/required/err-d0006-001.xml

[role="pass"]
=== PASS Test err:XD0007
http://tests.xproc.org/tests/required/err-d0007-001.xml

[role="pass"]
=== PASS Test err:XD0007 (p:viewport)
http://tests.xproc.org/tests/required/err-d0007-002.xml

[role="pass"]
=== PASS Test err:XD0007 #003
http://tests.xproc.org/tests/required/err-d0007-003.xml

[role="pass"]
=== PASS Test output-003
http://tests.xproc.org/tests/required/err-d0007-004.xml

[role="pass"]
=== PASS Test err:XD0008
http://tests.xproc.org/tests/required/err-d0008-001.xml

[role="pass"]
=== PASS Test err:XD0009
http://tests.xproc.org/tests/required/err-d0009-001.xml

[role="pass"]
=== PASS Test err:XD0009
http://tests.xproc.org/tests/required/err-d0009-002.xml

[role="pass"]
=== PASS Test err:XD0010
http://tests.xproc.org/tests/required/err-d0010-001.xml

[role="pass"]
=== PASS Test for inaccessible URIs (err:XD0011)
http://tests.xproc.org/tests/required/err-d0011-001.xml

[role="pass"]
=== PASS Test for err:XD0011 - 002
http://tests.xproc.org/tests/required/err-d0011-002.xml

[role="pass"]
=== PASS Test for err:XD0011 - 003
http://tests.xproc.org/tests/required/err-d0011-003.xml

[role="pass"]
=== PASS Test err:XD0012 #001
http://tests.xproc.org/tests/required/err-d0012-001.xml

[role="pass"]
=== PASS Test err:XD0012 #002
http://tests.xproc.org/tests/required/err-d0012-002.xml

[role="pass"]
=== PASS Test err:XD0012 #003
http://tests.xproc.org/tests/required/err-d0012-003.xml

[role="pass"]
=== PASS Test err:XD0013 #001
http://tests.xproc.org/tests/required/err-d0013-001.xml

[role="pass"]
=== PASS Test err:XD0013 #002
http://tests.xproc.org/tests/required/err-d0013-002.xml

[role="pass"]
=== PASS Test for err:XD0014 #001
http://tests.xproc.org/tests/required/err-d0014-001.xml

[role="pass"]
=== PASS Test for err:XD0014 #002
http://tests.xproc.org/tests/required/err-d0014-002.xml

[role="pass"]
=== PASS Test for err:XD0015 #001
http://tests.xproc.org/tests/required/err-d0015-001.xml

[role="pass"]
=== PASS Test for err:XD0016 #001
http://tests.xproc.org/tests/required/err-d0016-001.xml

[role="pass"]
=== PASS Test for err:XD0016 #002
http://tests.xproc.org/tests/required/err-d0016-002.xml

[role="pass"]
=== PASS Test for err:XD0018 #001
http://tests.xproc.org/tests/required/err-d0018-001.xml

[role="pass"]
=== PASS Test err:XD0019
http://tests.xproc.org/tests/required/err-d0019-001.xml

[role="pass"]
=== PASS Test for err:XD0019 - 002
http://tests.xproc.org/tests/required/err-d0019-002.xml

[role="pass"]
=== PASS Test err:XD0020 #001
http://tests.xproc.org/tests/required/err-d0020-001.xml

[role="pass"]
=== PASS Test err:XD0020 #002
http://tests.xproc.org/tests/required/err-d0020-002.xml

[role="pass"]
=== PASS Test err:XD0021 #001
http://tests.xproc.org/tests/required/err-d0021-001.xml

[role="pass"]
=== PASS Test for err:XD0021 - 002
http://tests.xproc.org/tests/required/err-d0021-002.xml

[role="pass"]
=== PASS Test for err:XD0022 #001
http://tests.xproc.org/tests/required/err-d0022-001.xml

[role="pass"]
=== PASS Test err:XD0023 - #001
http://tests.xproc.org/tests/required/err-d0023-001.xml

[role="pass"]
=== PASS Test err:XD0023 - #002
http://tests.xproc.org/tests/required/err-d0023-002.xml

[role="pass"]
=== PASS Test err:XD0023 - #003
http://tests.xproc.org/tests/required/err-d0023-003.xml

[role="pass"]
=== PASS Test err:XD0023 - #004
http://tests.xproc.org/tests/required/err-d0023-004.xml

[role="pass"]
=== PASS Test err:XD0023 - #005
http://tests.xproc.org/tests/required/err-d0023-005.xml

[role="pass"]
=== PASS Test err:XD0023 - #006
http://tests.xproc.org/tests/required/err-d0023-006.xml

[role="pass"]
=== PASS Test err:XD0023 - #007
http://tests.xproc.org/tests/required/err-d0023-007.xml

[role="pass"]
=== PASS Test err:XD0023 - #008
http://tests.xproc.org/tests/required/err-d0023-008.xml

[role="pass"]
=== PASS Test err:XD0023 - #009
http://tests.xproc.org/tests/required/err-d0023-009.xml

[role="pass"]
=== PASS Test for err:XD0025 #001
http://tests.xproc.org/tests/required/err-d0025-001.xml

[role="pass"]
=== PASS Test err-d0026-001
http://tests.xproc.org/tests/required/err-d0026-001.xml

[role="pass"]
=== PASS Test err:XD0026 #002
http://tests.xproc.org/tests/required/err-d0026-002.xml

[role="pass"]
=== PASS Test err:XD0026 #003
http://tests.xproc.org/tests/required/err-d0026-003.xml

[role="pass"]
=== PASS Test err:XD0026 #004
http://tests.xproc.org/tests/required/err-d0026-004.xml

[role="pass"]
=== PASS Test err:XD0026 #005
http://tests.xproc.org/tests/required/err-d0026-005.xml

[role="pass"]
=== PASS Test for err:XD0027 #001
http://tests.xproc.org/tests/required/err-d0027-001.xml

[role="pass"]
=== PASS Test err:XC0028 #001
http://tests.xproc.org/tests/required/err-d0028-001.xml

[role="pass"]
=== PASS Test err:XC0028 #002
http://tests.xproc.org/tests/required/err-d0028-002.xml

[role="pass"]
=== PASS Test err:XC0028 #003
http://tests.xproc.org/tests/required/err-d0028-003.xml

[role="pass"]
=== PASS Test err:XC0028 #004
http://tests.xproc.org/tests/required/err-d0028-004.xml

[role="pass"]
=== PASS Test for err:XD0029 #001
http://tests.xproc.org/tests/required/err-d0029-001.xml

[role="pass"]
=== PASS Test for err:XD0029 #002
http://tests.xproc.org/tests/required/err-d0029-002.xml

[role="pass"]
=== PASS Test err:XD0030 - 001
http://tests.xproc.org/tests/required/err-d0030-001.xml

[role="pass"]
=== PASS Test err:XD0030 - 002
http://tests.xproc.org/tests/required/err-d0030-002.xml

[role="pass"]
=== PASS Test err:XD0031 #001
http://tests.xproc.org/tests/required/err-d0031-001.xml

[role="pass"]
=== PASS Test err:XD0031 #002
http://tests.xproc.org/tests/required/err-d0031-002.xml

[role="pass"]
=== PASS Test err:XD0033 #001
http://tests.xproc.org/tests/required/err-d0033-001.xml

[role="pass"]
=== PASS Test err:XD0033 #002
http://tests.xproc.org/tests/required/err-d0033-002.xml

[role="pass"]
=== PASS Test err:XD0034 - 001
http://tests.xproc.org/tests/required/err-d0034-001.xml

[role="pass"]
=== PASS Test err:XD0034 - 002
http://tests.xproc.org/tests/required/err-d0034-002.xml

[role="pass"]
=== PASS Test err:XD0034 - 003
http://tests.xproc.org/tests/required/err-d0034-003.xml

[role="pass"]
=== PASS Test err:XD0034 - 004
http://tests.xproc.org/tests/required/err-d0034-004.xml

[role="pass"]
=== PASS Test err:XD0034 - 005
http://tests.xproc.org/tests/required/err-d0034-005.xml

[role="pass"]
=== PASS Test err:XD0034 - 006
http://tests.xproc.org/tests/required/err-d0034-006.xml

[role="pass"]
=== PASS Test err:XD0034 - 007
http://tests.xproc.org/tests/required/err-d0034-007.xml

[role="pass"]
=== PASS Test err:XD0034 - 008
http://tests.xproc.org/tests/required/err-d0034-008.xml

[role="pass"]
=== PASS Test err:XD0034 - 009
http://tests.xproc.org/tests/required/err-d0034-009.xml

[role="pass"]
=== PASS Test err:XD0034 - 010
http://tests.xproc.org/tests/required/err-d0034-010.xml

[role="pass"]
=== PASS Test err:XD0034 - 011
http://tests.xproc.org/tests/required/err-d0034-011.xml

[role="pass"]
=== PASS Test err:XD0034 - 012
http://tests.xproc.org/tests/required/err-d0034-012.xml

[role="pass"]
=== PASS Test err:XD0034 - 013
http://tests.xproc.org/tests/required/err-d0034-013.xml

[role="pass"]
=== PASS Test err:XD0034 - 014
http://tests.xproc.org/tests/required/err-d0034-014.xml

[role="pass"]
=== PASS Test err:XD0034 - 015
http://tests.xproc.org/tests/required/err-d0034-015.xml

[role="pass"]
=== PASS Test err:XD0034 - 016
http://tests.xproc.org/tests/required/err-d0034-016.xml

[role="pass"]
=== PASS Test err:XD0034 - 017
http://tests.xproc.org/tests/required/err-d0034-017.xml

[role="pass"]
=== PASS Test err:XD0034 - 018
http://tests.xproc.org/tests/required/err-d0034-018.xml

[role="pass"]
=== PASS Test err:XS0008
http://tests.xproc.org/tests/required/err-primary-001.xml

[role="pass"]
=== PASS Test for err:XS0001
http://tests.xproc.org/tests/required/err-s0001-001.xml

[role="pass"]
=== PASS Test for err:XS0001 #002
http://tests.xproc.org/tests/required/err-s0001-002.xml

[role="pass"]
=== PASS Test for err:XS0001 #003
http://tests.xproc.org/tests/required/err-s0001-003.xml

[role="pass"]
=== PASS Test for err:XS0001 #004
http://tests.xproc.org/tests/required/err-s0001-004.xml

[role="pass"]
=== PASS Test for err:XS0001 #005
http://tests.xproc.org/tests/required/err-s0001-005.xml

[role="pass"]
=== PASS Test for err:XS0001 #006
http://tests.xproc.org/tests/required/err-s0001-006.xml

[role="pass"]
=== PASS Test for err:XS0001 #007
http://tests.xproc.org/tests/required/err-s0001-007.xml

[role="pass"]
=== PASS Test for err:XS0001 #008
http://tests.xproc.org/tests/required/err-s0001-008.xml

[role="pass"]
=== PASS Test for err:XS0001 #010
http://tests.xproc.org/tests/required/err-s0001-010.xml

[role="pass"]
=== PASS Test for err:XS0001 #011
http://tests.xproc.org/tests/required/err-s0001-011.xml

[role="pass"]
=== PASS Test for duplicate names error (err:XS0002)
http://tests.xproc.org/tests/required/err-s0002-001.xml

[role="pass"]
=== PASS Test for duplicate names error (err:XS0002)
http://tests.xproc.org/tests/required/err-s0002-002.xml

[role="pass"]
=== PASS Test err:XS0003 #001
http://tests.xproc.org/tests/required/err-s0003-001.xml

[role="pass"]
=== PASS Test err:XS0003 #002
http://tests.xproc.org/tests/required/err-s0003-002.xml

[role="pass"]
=== PASS Test err:XS0003 #004
http://tests.xproc.org/tests/required/err-s0003-004.xml

[role="pass"]
=== PASS Test for err:XS0004 #001
http://tests.xproc.org/tests/required/err-s0004-001.xml

[role="pass"]
=== PASS Test for err:XS0004 #002
http://tests.xproc.org/tests/required/err-s0004-002.xml

[role="pass"]
=== PASS Test for err:XS0004 #003
http://tests.xproc.org/tests/required/err-s0004-003.xml

[role="pass"]
=== PASS Test for err:XS0004 #004
http://tests.xproc.org/tests/required/err-s0004-004.xml

[role="pass"]
=== PASS Test err:XS0005 #001
http://tests.xproc.org/tests/required/err-s0005-001.xml

[role="pass"]
=== PASS Test err:XS0005 #002
http://tests.xproc.org/tests/required/err-s0005-002.xml

[role="pass"]
=== PASS Test err:XS0005 #003
http://tests.xproc.org/tests/required/err-s0005-003.xml

[role="pass"]
=== PASS Test err:XS0005 #004
http://tests.xproc.org/tests/required/err-s0005-004.xml

[role="pass"]
=== PASS Test err:XS0005 #005
http://tests.xproc.org/tests/required/err-s0005-005.xml

[role="pass"]
=== PASS Test err:XS0005 #006
http://tests.xproc.org/tests/required/err-s0005-006.xml

[role="pass"]
=== PASS Test err:XS0005 #007
http://tests.xproc.org/tests/required/err-s0005-007.xml

[role="pass"]
=== PASS Test err:XS0005 #008
http://tests.xproc.org/tests/required/err-s0005-008.xml

[role="pass"]
=== PASS Test err:XS0005 #009
http://tests.xproc.org/tests/required/err-s0005-009.xml

[role="pass"]
=== PASS Test err:XS0005 #010
http://tests.xproc.org/tests/required/err-s0005-010.xml

[role="pass"]
=== PASS Test err:XS0005 #011
http://tests.xproc.org/tests/required/err-s0005-011.xml

[role="pass"]
=== PASS Test err:XS0005 #012
http://tests.xproc.org/tests/required/err-s0005-012.xml

[role="pass"]
=== PASS Test err:XS0005 #013
http://tests.xproc.org/tests/required/err-s0005-013.xml

[role="pass"]
=== PASS Test for err:XS0006 - 001
http://tests.xproc.org/tests/required/err-s0006-001.xml

[role="pass"]
=== PASS Test for err:XS0007
http://tests.xproc.org/tests/required/err-s0007-001.xml

[role="pass"]
=== PASS Test for err:XS0007 #002
http://tests.xproc.org/tests/required/err-s0007-002.xml

[role="pass"]
=== PASS Test for err:XS0007 #003
http://tests.xproc.org/tests/required/err-s0007-003.xml

[role="pass"]
=== PASS Test for err:XS0008 - 001
http://tests.xproc.org/tests/required/err-s0008-001.xml

[role="pass"]
=== PASS Test for err:XS0009 - 001
http://tests.xproc.org/tests/required/err-s0009-001.xml

[role="pass"]
=== PASS Test for err:XS0009 - 002
http://tests.xproc.org/tests/required/err-s0009-002.xml

[role="pass"]
=== PASS Test for err:XS0009 - 004
http://tests.xproc.org/tests/required/err-s0009-004.xml

[role="pass"]
=== PASS Test for err:XS0009 - 005
http://tests.xproc.org/tests/required/err-s0009-005.xml

[role="pass"]
=== PASS Test for err:XS0010 - 001
http://tests.xproc.org/tests/required/err-s0010-001.xml

[role="pass"]
=== PASS Test for err:XS0010 - 002
http://tests.xproc.org/tests/required/err-s0010-002.xml

[role="pass"]
=== PASS Test for err:XS0010 - 003
http://tests.xproc.org/tests/required/err-s0010-003.xml

[role="pass"]
=== PASS Test err:XS0011 #001
http://tests.xproc.org/tests/required/err-s0011-001.xml

[role="pass"]
=== PASS Test err:XS0011 #002
http://tests.xproc.org/tests/required/err-s0011-002.xml

[role="pass"]
=== PASS Test err:XS0011 #003
http://tests.xproc.org/tests/required/err-s0011-003.xml

[role="pass"]
=== PASS Test err:XS0011 #004
http://tests.xproc.org/tests/required/err-s0011-004.xml

[role="pass"]
=== PASS Test for multiple primary outputs
http://tests.xproc.org/tests/required/err-s0014-001.xml

[role="pass"]
=== PASS Test err:XS0015 #001
http://tests.xproc.org/tests/required/err-s0015-001.xml

[role="pass"]
=== PASS Test for err:XS0017 - 001
http://tests.xproc.org/tests/required/err-s0017-001.xml

[role="pass"]
=== PASS Test for err:XS0018 - 001
http://tests.xproc.org/tests/required/err-s0018-001.xml

[role="pass"]
=== PASS Test for err:XS0018 - 002
http://tests.xproc.org/tests/required/err-s0018-002.xml

[role="pass"]
=== PASS Test for err:XS0018 - 003
http://tests.xproc.org/tests/required/err-s0018-003.xml

[role="pass"]
=== PASS Test for err:XS0019 - 001
http://tests.xproc.org/tests/required/err-s0019-001.xml

[role="pass"]
=== PASS Test for err:XS0020 - 001
http://tests.xproc.org/tests/required/err-s0020-001.xml

[role="pass"]
=== PASS Test for err:XS0020 - 002
http://tests.xproc.org/tests/required/err-s0020-002.xml

[role="pass"]
=== PASS Test for err:XS0020 - 003
http://tests.xproc.org/tests/required/err-s0020-003.xml

[role="pass"]
=== PASS Test err:XS0022 #001
http://tests.xproc.org/tests/required/err-s0022-001.xml

[role="pass"]
=== PASS Test for err:XS0022
http://tests.xproc.org/tests/required/err-s0022-002.xml

[role="pass"]
=== PASS Test for err:XS0022
http://tests.xproc.org/tests/required/err-s0022-003.xml

[role="pass"]
=== PASS Test for err:XS0022 #004
http://tests.xproc.org/tests/required/err-s0022-004.xml

[role="pass"]
=== PASS Test for err:XS0022 #005
http://tests.xproc.org/tests/required/err-s0022-005.xml

[role="pass"]
=== PASS Test for err:XS0022 #006
http://tests.xproc.org/tests/required/err-s0022-006.xml

[role="pass"]
=== PASS Test for err:XS0024 #001
http://tests.xproc.org/tests/required/err-s0024-001.xml

[role="pass"]
=== PASS Test for err:XS0024 #002
http://tests.xproc.org/tests/required/err-s0024-002.xml

[role="pass"]
=== PASS Test for err:XS0025 #001
http://tests.xproc.org/tests/required/err-s0025-001.xml

[role="pass"]
=== PASS Test for err:XS0025 #002
http://tests.xproc.org/tests/required/err-s0025-002.xml

[role="pass"]
=== PASS Test for err:XS0025 #003
http://tests.xproc.org/tests/required/err-s0025-003.xml

[role="pass"]
=== PASS Test for err:XS0025 #004
http://tests.xproc.org/tests/required/err-s0025-004.xml

[role="pass"]
=== PASS Test for err:XS0026 #001
http://tests.xproc.org/tests/required/err-s0026-001.xml

[role="pass"]
=== PASS Test for err:XS0026 #002
http://tests.xproc.org/tests/required/err-s0026-002.xml

[role="pass"]
=== PASS Test for err:XS0027
http://tests.xproc.org/tests/required/err-s0027-001.xml

[role="pass"]
=== PASS Test err:XS0028 #001
http://tests.xproc.org/tests/required/err-s0028-001.xml

[role="pass"]
=== PASS Test err:XS0028 #002
http://tests.xproc.org/tests/required/err-s0028-002.xml

[role="pass"]
=== PASS Test err:XS0029 #001
http://tests.xproc.org/tests/required/err-s0029-001.xml

[role="pass"]
=== PASS Test for multiple primary inputs
http://tests.xproc.org/tests/required/err-s0030-001.xml

[role="pass"]
=== PASS Test for err:XS0031 - 001
http://tests.xproc.org/tests/required/err-s0031-001.xml

[role="pass"]
=== PASS Test for err:XS0031 - 002
http://tests.xproc.org/tests/required/err-s0031-002.xml

[role="pass"]
=== PASS Test err:XS0032 #001
http://tests.xproc.org/tests/required/err-s0032-001.xml

[role="pass"]
=== PASS Test for err:XS0033 - 001
http://tests.xproc.org/tests/required/err-s0033-001.xml

[role="pass"]
=== PASS Test for err:XS0034 - 001
http://tests.xproc.org/tests/required/err-s0034-001.xml

[role="pass"]
=== PASS Test for err:XS0034 - 002
http://tests.xproc.org/tests/required/err-s0034-002.xml

[role="pass"]
=== PASS Test err:XS0035 #001
http://tests.xproc.org/tests/required/err-s0035-001.xml

[role="pass"]
=== PASS Test err:XS0035 #002
http://tests.xproc.org/tests/required/err-s0035-002.xml

[role="pass"]
=== PASS Test err:XS0036 #001
http://tests.xproc.org/tests/required/err-s0036-001.xml

[role="pass"]
=== PASS Test err:XS0036 #002
http://tests.xproc.org/tests/required/err-s0036-002.xml

[role="pass"]
=== PASS Test err:XS0036 #003
http://tests.xproc.org/tests/required/err-s0036-003.xml

[role="pass"]
=== PASS Test err:XS0036 #004
http://tests.xproc.org/tests/required/err-s0036-004.xml

[role="pass"]
=== PASS Test err:xs0036 #005
http://tests.xproc.org/tests/required/err-s0036-005.xml

[role="pass"]
=== PASS Test for err:XS0037 - 001
http://tests.xproc.org/tests/required/err-s0037-001.xml

[role="pass"]
=== PASS Test for err:XS0037 - 002
http://tests.xproc.org/tests/required/err-s0037-002.xml

[role="pass"]
=== PASS Test for err:XS0037 - 003
http://tests.xproc.org/tests/required/err-s0037-003.xml

[role="pass"]
=== PASS Test for err:XS0038 - 001
http://tests.xproc.org/tests/required/err-s0038-001.xml

[role="pass"]
=== PASS Test for err:XS0038 - 002
http://tests.xproc.org/tests/required/err-s0038-002.xml

[role="pass"]
=== PASS Test for err:XS0039 - 001
http://tests.xproc.org/tests/required/err-s0039-001.xml

[role="pass"]
=== PASS Test for err:XS0039 - 002
http://tests.xproc.org/tests/required/err-s0039-002.xml

[role="pass"]
=== PASS Test for err:XS0040 - 001
http://tests.xproc.org/tests/required/err-s0040-001.xml

[role="pass"]
=== PASS Test err:XS0041 #001
http://tests.xproc.org/tests/required/err-s0041-001.xml

[role="pass"]
=== PASS Test err:XS0042 #001
http://tests.xproc.org/tests/required/err-s0042-001.xml

[role="pass"]
=== PASS Test err:XS0044 #001
http://tests.xproc.org/tests/required/err-s0044-001.xml

[role="pass"]
=== PASS Test err:XS0044 #002
http://tests.xproc.org/tests/required/err-s0044-002.xml

[role="pass"]
=== PASS Test err:XS0044 #0003
http://tests.xproc.org/tests/required/err-s0044-003.xml

[role="pass"]
=== PASS Test for err:XS0048 - 001
http://tests.xproc.org/tests/required/err-s0048-001.xml

[role="pass"]
=== PASS Test err:XS0051 #001
http://tests.xproc.org/tests/required/err-s0051-001.xml

[role="pass"]
=== PASS Test err:XS0051 #001
http://tests.xproc.org/tests/required/err-s0051-002.xml

[role="pass"]
=== PASS Test err:XS0052 #001
http://tests.xproc.org/tests/required/err-s0052-001.xml

[role="pass"]
=== PASS Test err:XS0052 #002
http://tests.xproc.org/tests/required/err-s0052-002.xml

[role="pass"]
=== PASS Test err:XS0053 #001
http://tests.xproc.org/tests/required/err-s0053-001.xml

[role="pass"]
=== PASS Test err:XS0055 #001
http://tests.xproc.org/tests/required/err-s0055-001.xml

[role="pass"]
=== PASS Test err:XS0055 #002
http://tests.xproc.org/tests/required/err-s0055-002.xml

[role="pass"]
=== PASS Test err:XS0057 #001
http://tests.xproc.org/tests/required/err-s0057-001.xml

[role="pass"]
=== PASS Test err:XS0057 #002
http://tests.xproc.org/tests/required/err-s0057-002.xml

[role="pass"]
=== PASS Test err:XS0058 #001
http://tests.xproc.org/tests/required/err-s0058-001.xml

[role="pass"]
=== PASS Test for err:XS0059 #001
http://tests.xproc.org/tests/required/err-s0059-001.xml

[role="pass"]
=== PASS Test err:XS0061 #001
http://tests.xproc.org/tests/required/err-s0061-001.xml

[role="pass"]
=== PASS Test for err:XS0062 #001
http://tests.xproc.org/tests/required/err-s0062-001.xml

[role="pass"]
=== PASS Test for err:XS0062 #002
http://tests.xproc.org/tests/required/err-s0062-002.xml

[role="pass"]
=== PASS Test err:XS0063 #001
http://tests.xproc.org/tests/required/err-s0063-001.xml

[role="pass"]
=== PASS Test p:error #001
http://tests.xproc.org/tests/required/error-001.xml

[role="pass"]
=== PASS Test p:error #002
http://tests.xproc.org/tests/required/error-002.xml

[role="pass"]
=== PASS Test p:error #003
http://tests.xproc.org/tests/required/error-003.xml

[role="pass"]
=== PASS Test escape-markup #001
http://tests.xproc.org/tests/required/escape-markup-001.xml

[role="pass"]
=== PASS Test evaluation order #001
http://tests.xproc.org/tests/required/evaluation-order-001.xml

[role="pass"]
=== PASS Test evaluation order #002
http://tests.xproc.org/tests/required/evaluation-order-002.xml

[role="pass"]
=== PASS Test evaluation order #003
http://tests.xproc.org/tests/required/evaluation-order-003.xml

[role="pass"]
=== PASS Test exclude-inline-prefixes-001
http://tests.xproc.org/tests/required/exclude-inline-prefixes-001.xml

[role="pass"]
=== PASS Test exclude-inline-prefixes-002
http://tests.xproc.org/tests/required/exclude-inline-prefixes-002.xml

[role="pass"]
=== PASS Test exclude-inline-prefixes-003
http://tests.xproc.org/tests/required/exclude-inline-prefixes-003.xml

[role="pass"]
=== PASS Test exclude-inline-prefixes-004
http://tests.xproc.org/tests/required/exclude-inline-prefixes-004.xml

[role="pass"]
=== PASS Test exclude-inline-prefixes-005
http://tests.xproc.org/tests/required/exclude-inline-prefixes-005.xml

[role="pass"]
=== PASS Test exclude-inline-prefixes-006
http://tests.xproc.org/tests/required/exclude-inline-prefixes-006.xml

[role="pass"]
=== PASS Test exclude-inline-prefixes-007
http://tests.xproc.org/tests/required/exclude-inline-prefixes-007.xml

[role="pass"]
=== PASS Test exclude-inline-prefixes-008
http://tests.xproc.org/tests/required/exclude-inline-prefixes-008.xml

[role="pass"]
=== PASS Test exclude-inline-prefixes-009
http://tests.xproc.org/tests/required/exclude-inline-prefixes-009.xml

[role="pass"]
=== PASS Test exclude-inline-prefixes-010
http://tests.xproc.org/tests/required/exclude-inline-prefixes-010.xml

[role="pass"]
=== PASS Test fibonacci
http://tests.xproc.org/tests/required/fibonacci.xml

[role="pass"]
=== PASS Test filter-001
http://tests.xproc.org/tests/required/filter-001.xml

[role="pass"]
=== PASS Test filter-002
http://tests.xproc.org/tests/required/filter-002.xml

[role="pass"]
=== PASS Test filter-003
http://tests.xproc.org/tests/required/filter-003.xml

[role="pass"]
=== PASS Test for-each #001
http://tests.xproc.org/tests/required/for-each-001.xml

[role="pass"]
=== PASS Test for-each #002
http://tests.xproc.org/tests/required/for-each-002.xml

[role="pass"]
=== PASS Test for-each #003
http://tests.xproc.org/tests/required/for-each-003.xml

[role="pass"]
=== PASS Test for-each #004
http://tests.xproc.org/tests/required/for-each-004.xml

[role="pass"]
=== PASS Test for-each #005
http://tests.xproc.org/tests/required/for-each-005.xml

[role="pass"]
=== PASS Test for-each #006
http://tests.xproc.org/tests/required/for-each-006.xml

[role="pass"]
=== PASS Test for-each #007
http://tests.xproc.org/tests/required/for-each-007.xml

[role="pass"]
=== PASS Test for-each #008
http://tests.xproc.org/tests/required/for-each-008.xml

[role="pass"]
=== PASS Test for-each #009
http://tests.xproc.org/tests/required/for-each-009.xml

[role="pass"]
=== PASS Test for-each #010
http://tests.xproc.org/tests/required/for-each-010.xml

[role="pass"]
=== PASS Test for-each #011
http://tests.xproc.org/tests/required/for-each-011.xml

[role="pass"]
=== PASS Test for-each #004
http://tests.xproc.org/tests/required/for-each-012.xml

[role="pass"]
=== PASS Test group #001
http://tests.xproc.org/tests/required/group-001.xml

[role="pass"]
=== PASS Test group #002
http://tests.xproc.org/tests/required/group-002.xml

[role="pass"]
=== PASS Test group #003
http://tests.xproc.org/tests/required/group-003.xml

[role="pass"]
=== PASS Test http-request #001
http://tests.xproc.org/tests/required/http-request-001.xml

[role="pass"]
=== PASS Test http-request #002
http://tests.xproc.org/tests/required/http-request-002.xml

[role="pass"]
=== PASS Test http-request #003
http://tests.xproc.org/tests/required/http-request-003.xml

[role="pass"]
=== PASS Test http-request #004
http://tests.xproc.org/tests/required/http-request-004.xml

[role="pass"]
=== PASS Test http-request #005
http://tests.xproc.org/tests/required/http-request-005.xml

[role="pass"]
=== PASS Test http-request #006
http://tests.xproc.org/tests/required/http-request-006.xml

[role="pass"]
=== PASS Test http-request #007
http://tests.xproc.org/tests/required/http-request-007.xml

[role="pass"]
=== PASS Test http-request #008
http://tests.xproc.org/tests/required/http-request-008.xml

[role="pass"]
=== PASS Test http-request #009
http://tests.xproc.org/tests/required/http-request-009.xml

[role="pass"]
=== PASS Test http-request #010
http://tests.xproc.org/tests/required/http-request-010.xml

[role="pass"]
=== PASS Test http-request #011
http://tests.xproc.org/tests/required/http-request-011.xml

[role="pass"]
=== PASS Test http-request #012
http://tests.xproc.org/tests/required/http-request-012.xml

[role="pass"]
=== PASS Test http-request #009
http://tests.xproc.org/tests/required/http-request-013.xml

[role="pass"]
=== PASS Test http-request #014
http://tests.xproc.org/tests/required/http-request-014.xml

[role="pass"]
=== PASS Test p:identity-step-001
http://tests.xproc.org/tests/required/identity-001.xml

[role="pass"]
=== PASS Test p:identity-step-002
http://tests.xproc.org/tests/required/identity-002.xml

[role="pass"]
=== PASS Test p:identity-step-002
http://tests.xproc.org/tests/required/identity-003.xml

[role="pass"]
=== PASS Test p:identity-step-004
http://tests.xproc.org/tests/required/identity-004.xml

[role="pass"]
=== PASS Test p:identity-step-005
http://tests.xproc.org/tests/required/identity-005.xml

[role="pass"]
=== PASS Test p:import #001
http://tests.xproc.org/tests/required/import-001.xml

[role="pass"]
=== PASS Test p:import #002
http://tests.xproc.org/tests/required/import-002.xml

[role="pass"]
=== PASS Test p:import #009
http://tests.xproc.org/tests/required/import-003.xml

[role="pass"]
=== PASS Test p:import #004
http://tests.xproc.org/tests/required/import-004.xml

[role="pass"]
=== PASS Test p:import #005
http://tests.xproc.org/tests/required/import-005.xml

[role="pass"]
=== PASS Test p:import #006
http://tests.xproc.org/tests/required/import-006.xml

[role="pass"]
=== PASS Test p:import #007
http://tests.xproc.org/tests/required/import-007.xml

[role="pass"]
=== PASS Test p:import #008
http://tests.xproc.org/tests/required/import-008.xml

[role="pass"]
=== PASS Test p:import #009
http://tests.xproc.org/tests/required/import-009.xml

[role="pass"]
=== PASS Test p:import #010
http://tests.xproc.org/tests/required/import-010.xml

[role="pass"]
=== PASS Test p:import #011
http://tests.xproc.org/tests/required/import-011.xml

[role="pass"]
=== PASS Test input-001
http://tests.xproc.org/tests/required/input-001.xml

[role="pass"]
=== PASS Test input-002
http://tests.xproc.org/tests/required/input-002.xml

[role="pass"]
=== PASS Test input-003
http://tests.xproc.org/tests/required/input-003.xml

[role="pass"]
=== PASS Test input-004
http://tests.xproc.org/tests/required/input-004.xml

[role="pass"]
=== PASS Test input-005
http://tests.xproc.org/tests/required/input-005.xml

[role="pass"]
=== PASS Test input-006
http://tests.xproc.org/tests/required/input-006.xml

[role="pass"]
=== PASS Test input-007
http://tests.xproc.org/tests/required/input-007.xml

[role="pass"]
=== PASS Test input-008
http://tests.xproc.org/tests/required/input-008.xml

[role="pass"]
=== PASS Test input-009
http://tests.xproc.org/tests/required/input-009.xml

[role="pass"]
=== PASS Test input-010
http://tests.xproc.org/tests/required/input-010.xml

[role="pass"]
=== PASS Test input-011
http://tests.xproc.org/tests/required/input-011.xml

[role="pass"]
=== PASS Test input-012
http://tests.xproc.org/tests/required/input-012.xml

[role="pass"]
=== PASS Test p:insert #001
http://tests.xproc.org/tests/required/insert-001.xml

[role="pass"]
=== PASS Test p:insert #002
http://tests.xproc.org/tests/required/insert-002.xml

[role="pass"]
=== PASS Test p:insert #003
http://tests.xproc.org/tests/required/insert-003.xml

[role="pass"]
=== PASS Test p:insert #004
http://tests.xproc.org/tests/required/insert-004.xml

[role="pass"]
=== PASS Test insert-005
http://tests.xproc.org/tests/required/insert-005.xml

[role="pass"]
=== PASS Test insert-006
http://tests.xproc.org/tests/required/insert-006.xml

[role="pass"]
=== PASS Test p:insert #007
http://tests.xproc.org/tests/required/insert-007.xml

[role="pass"]
=== PASS Test p:insert #008
http://tests.xproc.org/tests/required/insert-008.xml

[role="pass"]
=== PASS Test insert-009
http://tests.xproc.org/tests/required/insert-009.xml

[role="pass"]
=== PASS Test p:insert #010
http://tests.xproc.org/tests/required/insert-010.xml

[role="pass"]
=== PASS Test iteration #001
http://tests.xproc.org/tests/required/iteration-001.xml

[role="pass"]
=== PASS Test iteration #002
http://tests.xproc.org/tests/required/iteration-002.xml

[role="pass"]
=== PASS Test labelelements001
http://tests.xproc.org/tests/required/labelelements-001.xml

[role="pass"]
=== PASS Test p:label-elements #002
http://tests.xproc.org/tests/required/labelelements-002.xml

[role="pass"]
=== PASS Test p:label-elements #003
http://tests.xproc.org/tests/required/labelelements-003.xml

[role="pass"]
=== PASS Test labelelements #004
http://tests.xproc.org/tests/required/labelelements-004.xml

[role="pass"]
=== PASS Test p:label-elements #005
http://tests.xproc.org/tests/required/labelelements-005.xml

[role="pass"]
=== PASS Test labelelements #006
http://tests.xproc.org/tests/required/labelelements-006.xml

[role="pass"]
=== PASS Test labelelements #007
http://tests.xproc.org/tests/required/labelelements-007.xml

[role="pass"]
=== PASS Test labelelements #008
http://tests.xproc.org/tests/required/labelelements-008.xml

[role="pass"]
=== PASS Test labelelements #009
http://tests.xproc.org/tests/required/labelelements-009.xml

[role="pass"]
=== PASS Test labelelements #010
http://tests.xproc.org/tests/required/labelelements-010.xml

[role="pass"]
=== PASS Test labelelements #011
http://tests.xproc.org/tests/required/labelelements-011.xml

[role="pass"]
=== PASS Test p:load #001
http://tests.xproc.org/tests/required/load-001.xml

[role="pass"]
=== PASS Test p:load #002
http://tests.xproc.org/tests/required/load-002.xml

[role="pass"]
=== PASS Test p:load #003
http://tests.xproc.org/tests/required/load-003.xml

[role="pass"]
=== PASS Test p:load #004
http://tests.xproc.org/tests/required/load-004.xml

[role="pass"]
=== PASS Test p:log #001
http://tests.xproc.org/tests/required/log-001.xml

[role="pass"]
=== PASS Test p:log #002
http://tests.xproc.org/tests/required/log-002.xml

[role="pass"]
=== PASS Test make-absolute-uris #001
http://tests.xproc.org/tests/required/make-absolute-uris-001.xml

[role="pass"]
=== PASS Test make-absolute-uris #002
http://tests.xproc.org/tests/required/make-absolute-uris-002.xml

[role="pass"]
=== PASS Test make-absolute-uris #003
http://tests.xproc.org/tests/required/make-absolute-uris-003.xml

[role="pass"]
=== PASS Test make-sequence
http://tests.xproc.org/tests/required/make-sequence.xml

[role="pass"]
=== PASS Test http-request multipart #001
http://tests.xproc.org/tests/required/multipart-001.xml

[role="pass"]
=== PASS Test http-request multipart #002
http://tests.xproc.org/tests/required/multipart-002.xml

[role="pass"]
=== PASS Test http-request multipart #003
http://tests.xproc.org/tests/required/multipart-003.xml

[role="pass"]
=== PASS Test http-request multipart #004
http://tests.xproc.org/tests/required/multipart-004.xml

[role="pass"]
=== PASS Test http-request multipart #005
http://tests.xproc.org/tests/required/multipart-005.xml

[role="pass"]
=== PASS Test namespace-rename-001
http://tests.xproc.org/tests/required/namespace-rename-001.xml

[role="pass"]
=== PASS Test p:namespace-rename #002
http://tests.xproc.org/tests/required/namespace-rename-002.xml

[role="pass"]
=== PASS Test p:namespace-rename #003
http://tests.xproc.org/tests/required/namespace-rename-003.xml

[role="pass"]
=== PASS Test p:namespace-rename #004
http://tests.xproc.org/tests/required/namespace-rename-004.xml

[role="pass"]
=== PASS Test p:namespace-rename #005
http://tests.xproc.org/tests/required/namespace-rename-005.xml

[role="pass"]
=== PASS Test p:namespace-rename #006
http://tests.xproc.org/tests/required/namespace-rename-006.xml

[role="pass"]
=== PASS Test p:namespace-rename #007
http://tests.xproc.org/tests/required/namespace-rename-007.xml

[role="pass"]
=== PASS Test p:namespace-rename #008
http://tests.xproc.org/tests/required/namespace-rename-008.xml

[role="pass"]
=== PASS Test p:namespace-rename #009
http://tests.xproc.org/tests/required/namespace-rename-009.xml

[role="pass"]
=== PASS Test p:namespace-rename #010
http://tests.xproc.org/tests/required/namespace-rename-010.xml

[role="pass"]
=== PASS Test p:namespace-rename #011
http://tests.xproc.org/tests/required/namespace-rename-011.xml

[role="pass"]
=== PASS Test p:namespace-rename #012
http://tests.xproc.org/tests/required/namespace-rename-012.xml

[role="pass"]
=== PASS Test p:namespace-rename #013
http://tests.xproc.org/tests/required/namespace-rename-013.xml

[role="pass"]
=== PASS Test p:namespace-rename #014
http://tests.xproc.org/tests/required/namespace-rename-014.xml

[role="pass"]
=== PASS Test namespace-rename-015
http://tests.xproc.org/tests/required/namespace-rename-015.xml

[role="pass"]
=== PASS Test namespace-rename-016
http://tests.xproc.org/tests/required/namespace-rename-016.xml

[role="pass"]
=== PASS Test namespace-rename-017
http://tests.xproc.org/tests/required/namespace-rename-017.xml

[role="pass"]
=== PASS Test p:namespaces #001
http://tests.xproc.org/tests/required/namespaces-001.xml

[role="pass"]
=== PASS Test p:namespaces #002
http://tests.xproc.org/tests/required/namespaces-002.xml

[role="pass"]
=== PASS Test p:namespaces #003
http://tests.xproc.org/tests/required/namespaces-003.xml

[role="pass"]
=== PASS Test p:namespaces #004
http://tests.xproc.org/tests/required/namespaces-004.xml

[role="pass"]
=== PASS Test p:namespaces #005
http://tests.xproc.org/tests/required/namespaces-005.xml

[role="pass"]
=== PASS Test p:namespaces #006
http://tests.xproc.org/tests/required/namespaces-006.xml

[role="pass"]
=== PASS Test p:namespaces #007
http://tests.xproc.org/tests/required/namespaces-007.xml

[role="pass"]
=== PASS Test p:namespaces #008
http://tests.xproc.org/tests/required/namespaces-008.xml

[role="pass"]
=== PASS Test p:namespaces #009
http://tests.xproc.org/tests/required/namespaces-009.xml

[role="pass"]
=== PASS Test p:namespaces #010
http://tests.xproc.org/tests/required/namespaces-010.xml

[role="pass"]
=== PASS Test nested pipeline #001
http://tests.xproc.org/tests/required/nested-pipeline-001.xml

[role="pass"]
=== PASS Test option #001
http://tests.xproc.org/tests/required/option-001.xml

[role="pass"]
=== PASS Test option #002
http://tests.xproc.org/tests/required/option-002.xml

[role="pass"]
=== PASS Test option #004
http://tests.xproc.org/tests/required/option-004.xml

[role="pass"]
=== PASS Test output-001
http://tests.xproc.org/tests/required/output-001.xml

[role="pass"]
=== PASS Test output-001
http://tests.xproc.org/tests/required/output-002.xml

[role="pass"]
=== PASS Test pack #001
http://tests.xproc.org/tests/required/pack-001.xml

[role="pass"]
=== PASS Test pack #002
http://tests.xproc.org/tests/required/pack-002.xml

[role="pass"]
=== PASS Test pack #003
http://tests.xproc.org/tests/required/pack-003.xml

[role="pass"]
=== PASS Test pack #004
http://tests.xproc.org/tests/required/pack-004.xml

[role="pass"]
=== PASS Test pack #005
http://tests.xproc.org/tests/required/pack-005.xml

[role="pass"]
=== PASS Test pack #006
http://tests.xproc.org/tests/required/pack-006.xml

[role="pass"]
=== PASS Test param-001
http://tests.xproc.org/tests/required/param-001.xml

[role="pass"]
=== PASS Test param-002
http://tests.xproc.org/tests/required/param-002.xml

[role="pass"]
=== PASS Test param-003
http://tests.xproc.org/tests/required/param-003.xml

[role="pass"]
=== PASS Test param-004
http://tests.xproc.org/tests/required/param-004.xml

[role="pass"]
=== PASS Test param-005
http://tests.xproc.org/tests/required/param-005.xml

[role="pass"]
=== PASS Test parameters-001
http://tests.xproc.org/tests/required/parameters-001.xml

[role="pass"]
=== PASS Test parameters-002
http://tests.xproc.org/tests/required/parameters-002.xml

[role="pass"]
=== PASS Test parameters-003
http://tests.xproc.org/tests/required/parameters-003.xml

[role="pass"]
=== PASS Test p:pipe #001
http://tests.xproc.org/tests/required/pipe-001.xml

[role="pass"]
=== PASS Test p:pipeinfo-001
http://tests.xproc.org/tests/required/pipeinfo-001.xml

[role="pass"]
=== PASS Test preserving base URI #001
http://tests.xproc.org/tests/required/preserve-base-uri-001.xml

[role="pass"]
=== PASS Test preserving base URI #002
http://tests.xproc.org/tests/required/preserve-base-uri-002.xml

[role="pass"]
=== PASS Test rename-001
http://tests.xproc.org/tests/required/rename-001.xml

[role="pass"]
=== PASS Test rename-002
http://tests.xproc.org/tests/required/rename-002.xml

[role="pass"]
=== PASS Test rename-003
http://tests.xproc.org/tests/required/rename-003.xml

[role="pass"]
=== PASS Test rename-004
http://tests.xproc.org/tests/required/rename-004.xml

[role="pass"]
=== PASS Test rename-005
http://tests.xproc.org/tests/required/rename-005.xml

[role="pass"]
=== PASS Test rename-006
http://tests.xproc.org/tests/required/rename-006.xml

[role="pass"]
=== PASS Test rename-007
http://tests.xproc.org/tests/required/rename-007.xml

[role="pass"]
=== PASS Test replace001
http://tests.xproc.org/tests/required/replace-001.xml

[role="pass"]
=== PASS Test resolve-uri #001
http://tests.xproc.org/tests/required/resolve-uri-001.xml

[role="pass"]
=== PASS Test resolve-uri #002
http://tests.xproc.org/tests/required/resolve-uri-002.xml

[role="pass"]
=== PASS Test set-attributes #001
http://tests.xproc.org/tests/required/set-attributes-001.xml

[role="pass"]
=== PASS Test set-attributes #002
http://tests.xproc.org/tests/required/set-attributes-002.xml

[role="pass"]
=== PASS Test p:sink #001
http://tests.xproc.org/tests/required/sink-001.xml

[role="pass"]
=== PASS Test p:sink #002
http://tests.xproc.org/tests/required/sink-002.xml

[role="pass"]
=== PASS Test p:sink #003
http://tests.xproc.org/tests/required/sink-003.xml

[role="pass"]
=== PASS Test split-sequence-001
http://tests.xproc.org/tests/required/split-sequence-001.xml

[role="pass"]
=== PASS Test split-sequence-002
http://tests.xproc.org/tests/required/split-sequence-002.xml

[role="pass"]
=== PASS Test split-sequence-003
http://tests.xproc.org/tests/required/split-sequence-003.xml

[role="pass"]
=== PASS Test tail001
http://tests.xproc.org/tests/required/split-sequence-004.xml

[role="pass"]
=== PASS Test split-sequence 005
http://tests.xproc.org/tests/required/split-sequence-005.xml

[role="pass"]
=== PASS Test split-sequence 006
http://tests.xproc.org/tests/required/split-sequence-006.xml

[role="pass"]
=== PASS Test split-sequence #007
http://tests.xproc.org/tests/required/split-sequence-007.xml

[role="pass"]
=== PASS Test step-available #001
http://tests.xproc.org/tests/required/step-available-001.xml

[role="pass"]
=== PASS Test step-available #002
http://tests.xproc.org/tests/required/step-available-002.xml

[role="pass"]
=== PASS Test step-available #003
http://tests.xproc.org/tests/required/step-available-003.xml

[role="pass"]
=== PASS Test step-available #004
http://tests.xproc.org/tests/required/step-available-004.xml

[role="pass"]
=== PASS Test step-available #005
http://tests.xproc.org/tests/required/step-available-005.xml

[role="pass"]
=== PASS Test step-available #006
http://tests.xproc.org/tests/required/step-available-006.xml

[role="pass"]
=== PASS Test the p:store step
http://tests.xproc.org/tests/required/store-001.xml

[role="pass"]
=== PASS Test p:string-replace #001
http://tests.xproc.org/tests/required/string-replace-001.xml

[role="pass"]
=== PASS Test p:string-replace #002
http://tests.xproc.org/tests/required/string-replace-002.xml

[role="pass"]
=== PASS Test p:string-replace #003
http://tests.xproc.org/tests/required/string-replace-003.xml

[role="pass"]
=== PASS Test p:string-replace #004
http://tests.xproc.org/tests/required/string-replace-004.xml

[role="pass"]
=== PASS Test p:string-replace #005
http://tests.xproc.org/tests/required/string-replace-005.xml

[role="pass"]
=== PASS Test system-property-001
http://tests.xproc.org/tests/required/system-property-001.xml

[role="pass"]
=== PASS Test system-property-002
http://tests.xproc.org/tests/required/system-property-002.xml

[role="pass"]
=== PASS Test try/catch #001
http://tests.xproc.org/tests/required/try-001.xml

[role="pass"]
=== PASS Test try/catch #002
http://tests.xproc.org/tests/required/try-002.xml

[role="pass"]
=== PASS Test try/catch #003
http://tests.xproc.org/tests/required/try-003.xml

[role="pass"]
=== PASS Test try/catch #004
http://tests.xproc.org/tests/required/try-004.xml

[role="pass"]
=== PASS Test try/catch #005
http://tests.xproc.org/tests/required/try-005.xml

[role="pass"]
=== PASS Test try/catch #006
http://tests.xproc.org/tests/required/try-006.xml

[role="pass"]
=== PASS Test unescapemarkup-001
http://tests.xproc.org/tests/required/unescapemarkup-001.xml

[role="pass"]
=== PASS Test unescapemarkup-002
http://tests.xproc.org/tests/required/unescapemarkup-002.xml

[role="pass"]
=== PASS Test unescape markup-003
http://tests.xproc.org/tests/required/unescapemarkup-003.xml

[role="pass"]
=== PASS Test unescapemarkup-004
http://tests.xproc.org/tests/required/unescapemarkup-004.xml

[role="pass"]
=== PASS Test unescapemarkup-005
http://tests.xproc.org/tests/required/unescapemarkup-005.xml

[role="pass"]
=== PASS Test unescapemarkup-005
http://tests.xproc.org/tests/required/unescapemarkup-006.xml

[role="pass"]
=== PASS Test unescapemarkup-007
http://tests.xproc.org/tests/required/unescapemarkup-007.xml

[role="pass"]
=== PASS Test unwrap001
http://tests.xproc.org/tests/required/unwrap-001.xml

[role="pass"]
=== PASS Test unwrap 002
http://tests.xproc.org/tests/required/unwrap-002.xml

[role="pass"]
=== PASS Test use-when #001
http://tests.xproc.org/tests/required/use-when-001.xml

[role="pass"]
=== PASS Test use-when #002
http://tests.xproc.org/tests/required/use-when-002.xml

[role="pass"]
=== PASS Test use-when #003
http://tests.xproc.org/tests/required/use-when-003.xml

[role="pass"]
=== PASS Test use-when #004
http://tests.xproc.org/tests/required/use-when-004.xml

[role="pass"]
=== PASS Test value-available #001
http://tests.xproc.org/tests/required/value-available-001.xml

[role="pass"]
=== PASS Test value-available #002
http://tests.xproc.org/tests/required/value-available-002.xml

[role="pass"]
=== PASS Test value-available #003
http://tests.xproc.org/tests/required/value-available-003.xml

[role="pass"]
=== PASS Test value-available #004
http://tests.xproc.org/tests/required/value-available-004.xml

[role="pass"]
=== PASS Test value-available #005
http://tests.xproc.org/tests/required/value-available-005.xml

[role="pass"]
=== PASS Test value-available #006
http://tests.xproc.org/tests/required/value-available-006.xml

[role="pass"]
=== PASS Test variable #001
http://tests.xproc.org/tests/required/variable-001.xml

[role="pass"]
=== PASS Test variable #002
http://tests.xproc.org/tests/required/variable-002.xml

[role="pass"]
=== PASS Test variable #003
http://tests.xproc.org/tests/required/variable-003.xml

[role="pass"]
=== PASS Test variable #004
http://tests.xproc.org/tests/required/variable-004.xml

[role="pass"]
=== PASS Test variable #005
http://tests.xproc.org/tests/required/variable-005.xml

[role="pass"]
=== PASS Test variable #006
http://tests.xproc.org/tests/required/variable-006.xml

[role="pass"]
=== PASS Test variable #007
http://tests.xproc.org/tests/required/variable-007.xml

[role="pass"]
=== PASS Test variable #008
http://tests.xproc.org/tests/required/variable-008.xml

[role="pass"]
=== PASS Test version-available #001
http://tests.xproc.org/tests/required/version-available-001.xml

[role="pass"]
=== PASS Test version-available #002
http://tests.xproc.org/tests/required/version-available-002.xml

[role="pass"]
=== PASS Test versioning #001
http://tests.xproc.org/tests/required/versioning-001.xml

[role="pass"]
=== PASS Test versioning #002
http://tests.xproc.org/tests/required/versioning-002.xml

[role="pass"]
=== PASS Test versioning #003
http://tests.xproc.org/tests/required/versioning-003.xml

[role="pass"]
=== PASS Test versioning #004
http://tests.xproc.org/tests/required/versioning-004.xml

[role="pass"]
=== PASS Test versioning #005
http://tests.xproc.org/tests/required/versioning-005.xml

[role="pass"]
=== PASS Test versioning #006
http://tests.xproc.org/tests/required/versioning-006.xml

[role="pass"]
=== PASS Test versioning #007
http://tests.xproc.org/tests/required/versioning-007.xml

[role="pass"]
=== PASS Test viewport #001
http://tests.xproc.org/tests/required/viewport-001.xml

[role="pass"]
=== PASS Test viewport #002
http://tests.xproc.org/tests/required/viewport-002.xml

[role="pass"]
=== PASS Test viewport #003
http://tests.xproc.org/tests/required/viewport-003.xml

[role="pass"]
=== PASS Test viewport #004
http://tests.xproc.org/tests/required/viewport-004.xml

[role="pass"]
=== PASS Test viewport #005
http://tests.xproc.org/tests/required/viewport-005.xml

[role="pass"]
=== PASS Test viewport #006
http://tests.xproc.org/tests/required/viewport-006.xml

[role="pass"]
=== PASS Test viewport #007
http://tests.xproc.org/tests/required/viewport-007.xml

[role="pass"]
=== PASS Test viewport #008
http://tests.xproc.org/tests/required/viewport-008.xml

[role="pass"]
=== PASS Test viewport #009
http://tests.xproc.org/tests/required/viewport-009.xml

[role="pass"]
=== PASS Test viewport #010
http://tests.xproc.org/tests/required/viewport-010.xml

[role="pass"]
=== PASS Test viewport #011
http://tests.xproc.org/tests/required/viewport-011.xml

[role="pass"]
=== PASS Test wrap001
http://tests.xproc.org/tests/required/wrap-001.xml

[role="pass"]
=== PASS Test wrap-002
http://tests.xproc.org/tests/required/wrap-002.xml

[role="pass"]
=== PASS Test wrap-003
http://tests.xproc.org/tests/required/wrap-003.xml

[role="pass"]
=== PASS Test for p:wrap #004
http://tests.xproc.org/tests/required/wrap-004.xml

[role="pass"]
=== PASS Test for p:wrap #005
http://tests.xproc.org/tests/required/wrap-005.xml

[role="pass"]
=== PASS Test wrap-006
http://tests.xproc.org/tests/required/wrap-006.xml

[role="pass"]
=== PASS Test wrap-007
http://tests.xproc.org/tests/required/wrap-007.xml

[role="pass"]
=== PASS Test wrap-008
http://tests.xproc.org/tests/required/wrap-008.xml

[role="pass"]
=== PASS Test wrap-009
http://tests.xproc.org/tests/required/wrap-009.xml

[role="pass"]
=== PASS Test wrap-010
http://tests.xproc.org/tests/required/wrap-010.xml

[role="pass"]
=== PASS Test wrap-011
http://tests.xproc.org/tests/required/wrap-011.xml

[role="pass"]
=== PASS Test wrap-sequence-001
http://tests.xproc.org/tests/required/wrap-sequence-001.xml

[role="pass"]
=== PASS Test wrap-sequence-002
http://tests.xproc.org/tests/required/wrap-sequence-002.xml

[role="pass"]
=== PASS Test wrap-sequence-003
http://tests.xproc.org/tests/required/wrap-sequence-003.xml

[role="pass"]
=== PASS Test wrap-sequence-003
http://tests.xproc.org/tests/required/wrap-sequence-004.xml

[role="pass"]
=== PASS Test wrap-sequence-005
http://tests.xproc.org/tests/required/wrap-sequence-005.xml

[role="pass"]
=== PASS Test p:xinclude #001
http://tests.xproc.org/tests/required/xinclude-001.xml

[role="pass"]
=== PASS Test p:xinclude #002
http://tests.xproc.org/tests/required/xinclude-002.xml

[role="pass"]
=== PASS Test p:xinclude #003
http://tests.xproc.org/tests/required/xinclude-003.xml

[role="pass"]
=== PASS Test p:xinclude #004
http://tests.xproc.org/tests/required/xinclude-004.xml

[role="pass"]
=== PASS Test p:xinclude #005
http://tests.xproc.org/tests/required/xinclude-005.xml

[role="pass"]
=== PASS Test literal xml:id support #001
http://tests.xproc.org/tests/required/xml-id-001.xml

[role="pass"]
=== PASS Test added xml:id support #002
http://tests.xproc.org/tests/required/xml-id-002.xml

[role="pass"]
=== PASS Test xpath-version-available #001
http://tests.xproc.org/tests/required/xpath-version-available-001.xml

[role="pass"]
=== PASS Test xpath-version-available #001
http://tests.xproc.org/tests/required/xpath-version-available-002.xml

[role="pass"]
=== PASS Test xslt-001
http://tests.xproc.org/tests/required/xslt-001.xml

[role="pass"]
=== PASS Test xslt-002
http://tests.xproc.org/tests/required/xslt-002.xml

[role="pass"]
=== PASS Test xslt-003
http://tests.xproc.org/tests/required/xslt-003.xml

[role="pass"]
=== PASS Test xslt-004
http://tests.xproc.org/tests/required/xslt-004.xml

[role="pass"]
=== PASS Test xsl-t005
http://tests.xproc.org/tests/required/xslt-005.xml

[role="pass"]
=== PASS Test xslt-006
http://tests.xproc.org/tests/required/xslt-006.xml


== Serialization tests

Passed 23 of 25 tests (92.00%).

[role="pass"]
=== PASS Serialization test byte-order-mark-001
http://tests.xproc.org/tests/serialization/byte-order-mark-001.xml

[role="pass"]
=== PASS Serialization test byte-order-mark-002
http://tests.xproc.org/tests/serialization/byte-order-mark-002.xml

[role="pass"]
=== PASS Serialization test cdata-section-elements-001
http://tests.xproc.org/tests/serialization/cdata-section-elements-001.xml

[role="pass"]
=== PASS Serialization test cdata-section-elements-002
http://tests.xproc.org/tests/serialization/cdata-section-elements-002.xml

[role="pass"]
=== PASS Serialization test doctype-public-001
http://tests.xproc.org/tests/serialization/doctype-public-001.xml

[role="pass"]
=== PASS Serialization test doctype-system-001
http://tests.xproc.org/tests/serialization/doctype-system-001.xml

[role="pass"]
=== PASS Serialization test encoding-001
http://tests.xproc.org/tests/serialization/encoding-001.xml

[role="pass"]
=== PASS Test for err:XD0020 #001
http://tests.xproc.org/tests/serialization/err-d0020-001.xml

[role="pass"]
=== PASS Serialization test escape-uri-001
http://tests.xproc.org/tests/serialization/escape-uri-001.xml

[role="pass"]
=== PASS Serialization test escape-uri-002
http://tests.xproc.org/tests/serialization/escape-uri-002.xml

[role="pass"]
=== PASS Serialization test include-content-type #001
http://tests.xproc.org/tests/serialization/include-content-type-001.xml

[role="pass"]
=== PASS Serialization test include-content-type #002
http://tests.xproc.org/tests/serialization/include-content-type-002.xml

[role="pass"]
=== PASS Serialization test indent #001
http://tests.xproc.org/tests/serialization/indent-001.xml

[role="pass"]
=== PASS Serialization test indent #002
http://tests.xproc.org/tests/serialization/indent-002.xml

[role="pass"]
=== PASS Serialization test media-type #001
http://tests.xproc.org/tests/serialization/media-type-001.xml

[role="pass"]
=== PASS Serialization test normalization-form-001
http://tests.xproc.org/tests/serialization/normalization-form-001.xml

[role="pass"]
=== PASS Serialization test normalization-form-002
http://tests.xproc.org/tests/serialization/normalization-form-002.xml

[role="pass"]
=== PASS Serialization test normalization-form-003
http://tests.xproc.org/tests/serialization/normalization-form-003.xml

[role="pass"]
=== PASS Serialization test omit-xml-declaration-001
http://tests.xproc.org/tests/serialization/omit-xml-declaration-001.xml

[role="pass"]
=== PASS Serialization test omit-xml-declaration-002
http://tests.xproc.org/tests/serialization/omit-xml-declaration-002.xml

[role="pass"]
=== PASS Serialization test standalone-001
http://tests.xproc.org/tests/serialization/standalone-001.xml

[role="pass"]
=== PASS Serialization test standalone-002
http://tests.xproc.org/tests/serialization/standalone-002.xml

[role="pass"]
=== PASS Serialization test standalone-003
http://tests.xproc.org/tests/serialization/standalone-003.xml

[role="fail"]
=== FAIL Serialization test undeclare-prefixes-001
http://tests.xproc.org/tests/serialization/undeclare-prefixes-001.xml


==== Error message


* UnsupportedXMLVersionException:http://tests.xproc.org/tests/doc/xml11.xml is in not supported xml version 1.1

[role="fail"]
=== FAIL Serialization test version-001
http://tests.xproc.org/tests/serialization/version-001.xml


==== Error message


* UnsupportedXMLVersionException:http://tests.xproc.org/tests/doc/xml11.xml is in not supported xml version 1.1


== Optional tests

Passed 113 of 114 tests (99.12%).

[role="pass"]
=== PASS Test for err:XC0033 - 001
http://tests.xproc.org/tests/optional/err-c0033-001.xml

[role="pass"]
=== PASS Test for err:XC0034 - 001
http://tests.xproc.org/tests/optional/err-c0034-001.xml

[role="pass"]
=== PASS Test for err:XC0035 - 001
http://tests.xproc.org/tests/optional/err-c0035-001.xml

[role="pass"]
=== PASS Test for err:XC0035 - 002
http://tests.xproc.org/tests/optional/err-c0035-002.xml

[role="pass"]
=== PASS Test err:XC0036 - #001
http://tests.xproc.org/tests/optional/err-c0036-001.xml

[role="pass"]
=== PASS Test err:XC0036 - #002
http://tests.xproc.org/tests/optional/err-c0036-002.xml

[role="pass"]
=== PASS Test err:XC0036 - #003
http://tests.xproc.org/tests/optional/err-c0036-003.xml

[role="pass"]
=== PASS Test err:XC0036 - #004
http://tests.xproc.org/tests/optional/err-c0036-004.xml

[role="pass"]
=== PASS Test err:XC0036 - #005
http://tests.xproc.org/tests/optional/err-c0036-005.xml

[role="pass"]
=== PASS Test err:XC0037 - #001
http://tests.xproc.org/tests/optional/err-c0037-001.xml

[role="pass"]
=== PASS Test err:XC0037 - #002
http://tests.xproc.org/tests/optional/err-c0037-002.xml

[role="pass"]
=== PASS Test err:XC0037 - #003
http://tests.xproc.org/tests/optional/err-c0037-003.xml

[role="pass"]
=== PASS Test err:XC0053 - #001
http://tests.xproc.org/tests/optional/err-c0053-001.xml

[role="pass"]
=== PASS Test err:XC0053 - #002
http://tests.xproc.org/tests/optional/err-c0053-002.xml

[role="pass"]
=== PASS Test err:XC0053 - #003
http://tests.xproc.org/tests/optional/err-c0053-003.xml

[role="pass"]
=== PASS Test err:XC0053 - #004
http://tests.xproc.org/tests/optional/err-c0053-004.xml

[role="pass"]
=== PASS Test err:XC0054 - #001
http://tests.xproc.org/tests/optional/err-c0054-001.xml

[role="pass"]
=== PASS Test err:XC0057 - #001
http://tests.xproc.org/tests/optional/err-c0057-001.xml

[role="pass"]
=== PASS Test err:XC0060 - #001
http://tests.xproc.org/tests/optional/err-c0060-001.xml

[role="pass"]
=== PASS Test err:XC0061 - #001
http://tests.xproc.org/tests/optional/err-c0061-001.xml

[role="pass"]
=== PASS Test err:XC0063 - #001
http://tests.xproc.org/tests/optional/err-c0063-001.xml

[role="pass"]
=== PASS Test err:XC0063 - #002
http://tests.xproc.org/tests/optional/err-c0063-002.xml

[role="pass"]
=== PASS Test err:XC0064 - #001
http://tests.xproc.org/tests/optional/err-c0064-001.xml

[role="pass"]
=== PASS Test err:XC0066 - #001
http://tests.xproc.org/tests/optional/err-c0066-001.xml

[role="pass"]
=== PASS Test err:XC0066 - #002
http://tests.xproc.org/tests/optional/err-c0066-002.xml

[role="pass"]
=== PASS Test exec-001
http://tests.xproc.org/tests/optional/exec-001.xml

[role="pass"]
=== PASS Test exec-002
http://tests.xproc.org/tests/optional/exec-002.xml

[role="pass"]
=== PASS Test exec-003
http://tests.xproc.org/tests/optional/exec-003.xml

[role="pass"]
=== PASS Test exec-004
http://tests.xproc.org/tests/optional/exec-004.xml

[role="pass"]
=== PASS Test exec-005
http://tests.xproc.org/tests/optional/exec-005.xml

[role="pass"]
=== PASS Test exec-006
http://tests.xproc.org/tests/optional/exec-006.xml

[role="pass"]
=== PASS Test exec-007
http://tests.xproc.org/tests/optional/exec-007.xml

[role="pass"]
=== PASS Test exec-008
http://tests.xproc.org/tests/optional/exec-008.xml

[role="pass"]
=== PASS Test exec-009
http://tests.xproc.org/tests/optional/exec-009.xml

[role="pass"]
=== PASS Test exec-010
http://tests.xproc.org/tests/optional/exec-010.xml

[role="pass"]
=== PASS Test exec-011
http://tests.xproc.org/tests/optional/exec-011.xml

[role="pass"]
=== PASS Test exec-012
http://tests.xproc.org/tests/optional/exec-012.xml

[role="pass"]
=== PASS Test exec-013
http://tests.xproc.org/tests/optional/exec-013.xml

[role="pass"]
=== PASS Test exec-014
http://tests.xproc.org/tests/optional/exec-014.xml

[role="pass"]
=== PASS Test exec-015
http://tests.xproc.org/tests/optional/exec-015.xml

[role="pass"]
=== PASS Test exec-016
http://tests.xproc.org/tests/optional/exec-016.xml

[role="pass"]
=== PASS Test exec-017
http://tests.xproc.org/tests/optional/exec-017.xml

[role="pass"]
=== PASS Test hash-001
http://tests.xproc.org/tests/optional/hash-001.xml

[role="pass"]
=== PASS Test hash-002
http://tests.xproc.org/tests/optional/hash-002.xml

[role="pass"]
=== PASS Test hash-003
http://tests.xproc.org/tests/optional/hash-003.xml

[role="pass"]
=== PASS Test hash-004
http://tests.xproc.org/tests/optional/hash-004.xml

[role="pass"]
=== PASS Test hash-005
http://tests.xproc.org/tests/optional/hash-005.xml

[role="pass"]
=== PASS Test hash-006
http://tests.xproc.org/tests/optional/hash-006.xml

[role="pass"]
=== PASS Test p:in-scope-names #001
http://tests.xproc.org/tests/optional/in-scope-names-001.xml

[role="pass"]
=== PASS Test p:in-scope-names #002
http://tests.xproc.org/tests/optional/in-scope-names-002.xml

[role="fail"]
=== FAIL Test psvi-required-001.xml
http://tests.xproc.org/tests/optional/psvi-required-001.xml

Error: err:XD0022 was raised. 

* XD0022: It is a dynamic error if a processor that does not support PSVI annotations attempts to invoke a step which asserts that they are required.
[role="pass"]
=== PASS Test p:template-001
http://tests.xproc.org/tests/optional/template-001.xml

[role="pass"]
=== PASS Test p:template-002
http://tests.xproc.org/tests/optional/template-002.xml

[role="pass"]
=== PASS Test p:template-003
http://tests.xproc.org/tests/optional/template-003.xml

[role="pass"]
=== PASS Test p:template-004
http://tests.xproc.org/tests/optional/template-004.xml

[role="pass"]
=== PASS Test p:template-005
http://tests.xproc.org/tests/optional/template-005.xml

[role="pass"]
=== PASS Test p:template-006
http://tests.xproc.org/tests/optional/template-006.xml

[role="pass"]
=== PASS Test p:template-007
http://tests.xproc.org/tests/optional/template-007.xml

[role="pass"]
=== PASS Test p:template-008
http://tests.xproc.org/tests/optional/template-008.xml

[role="pass"]
=== PASS Test p:template-009
http://tests.xproc.org/tests/optional/template-009.xml

[role="pass"]
=== PASS Test p:template-010
http://tests.xproc.org/tests/optional/template-010.xml

[role="pass"]
=== PASS Test p:template-011
http://tests.xproc.org/tests/optional/template-011.xml

[role="pass"]
=== PASS Test p:template-012
http://tests.xproc.org/tests/optional/template-012.xml

[role="pass"]
=== PASS Test p:template-013
http://tests.xproc.org/tests/optional/template-013.xml

[role="pass"]
=== PASS Test p:template-014
http://tests.xproc.org/tests/optional/template-014.xml

[role="pass"]
=== PASS Test p:template-015
http://tests.xproc.org/tests/optional/template-015.xml

[role="pass"]
=== PASS Test p:template-016
http://tests.xproc.org/tests/optional/template-016.xml

[role="pass"]
=== PASS Test p:template-016
http://tests.xproc.org/tests/optional/template-017.xml

[role="pass"]
=== PASS Test p:template-018
http://tests.xproc.org/tests/optional/template-018.xml

[role="pass"]
=== PASS Test uuid-001
http://tests.xproc.org/tests/optional/uuid-001.xml

[role="pass"]
=== PASS Test validrng-001
http://tests.xproc.org/tests/optional/validrng-001.xml

[role="pass"]
=== PASS Test validrng-002
http://tests.xproc.org/tests/optional/validrng-002.xml

[role="pass"]
=== PASS Test validrng-003
http://tests.xproc.org/tests/optional/validrng-003.xml

[role="pass"]
=== PASS Test validrng-004
http://tests.xproc.org/tests/optional/validrng-004.xml

[role="pass"]
=== PASS Test validrng-005
http://tests.xproc.org/tests/optional/validrng-005.xml

[role="pass"]
=== PASS Test validrng-006
http://tests.xproc.org/tests/optional/validrng-006.xml

[role="pass"]
=== PASS Test validrng-008
http://tests.xproc.org/tests/optional/validrng-008.xml

[role="pass"]
=== PASS Test validrng-009
http://tests.xproc.org/tests/optional/validrng-009.xml

[role="pass"]
=== PASS Test validsch-001
http://tests.xproc.org/tests/optional/validsch-001.xml

[role="pass"]
=== PASS Test validsch-002
http://tests.xproc.org/tests/optional/validsch-002.xml

[role="pass"]
=== PASS Test validsch-003
http://tests.xproc.org/tests/optional/validsch-003.xml

[role="pass"]
=== PASS Test validsch-004
http://tests.xproc.org/tests/optional/validsch-004.xml

[role="pass"]
=== PASS Test validsch-005
http://tests.xproc.org/tests/optional/validsch-005.xml

[role="pass"]
=== PASS Test validxsd-001
http://tests.xproc.org/tests/optional/validxsd-001.xml

[role="pass"]
=== PASS Test validxsd-002
http://tests.xproc.org/tests/optional/validxsd-002.xml

[role="pass"]
=== PASS Test validxsd-003
http://tests.xproc.org/tests/optional/validxsd-003.xml

[role="pass"]
=== PASS Test validxsd-004
http://tests.xproc.org/tests/optional/validxsd-004.xml

[role="pass"]
=== PASS Test validxsd-005
http://tests.xproc.org/tests/optional/validxsd-005.xml

[role="pass"]
=== PASS Test validxsd-006
http://tests.xproc.org/tests/optional/validxsd-006.xml

[role="pass"]
=== PASS Test validxsd-007
http://tests.xproc.org/tests/optional/validxsd-007.xml

[role="pass"]
=== PASS Test validxsd-008
http://tests.xproc.org/tests/optional/validxsd-008.xml

[role="pass"]
=== PASS Test validxsd-009
http://tests.xproc.org/tests/optional/validxsd-009.xml

[role="pass"]
=== PASS Test validxsd-010
http://tests.xproc.org/tests/optional/validxsd-010.xml

[role="pass"]
=== PASS Test validxsd-011
http://tests.xproc.org/tests/optional/validxsd-011.xml

[role="pass"]
=== PASS Test validxsd-012
http://tests.xproc.org/tests/optional/validxsd-012.xml

[role="pass"]
=== PASS Test validxsd-013
http://tests.xproc.org/tests/optional/validxsd-013.xml

[role="pass"]
=== PASS Test www-form-urldecode-001
http://tests.xproc.org/tests/optional/www-form-urldecode-001.xml

[role="pass"]
=== PASS Test www-form-urlencode-001
http://tests.xproc.org/tests/optional/www-form-urlencode-001.xml

[role="pass"]
=== PASS Test optional features of p:xinclude #001
http://tests.xproc.org/tests/optional/xinclude-001.xml

[role="pass"]
=== PASS Test optional features of p:xinclude #002
http://tests.xproc.org/tests/optional/xinclude-002.xml

[role="pass"]
=== PASS Test optional features of p:xinclude #003
http://tests.xproc.org/tests/optional/xinclude-003.xml

[role="pass"]
=== PASS Test optional features of p:xinclude #004
http://tests.xproc.org/tests/optional/xinclude-004.xml

[role="pass"]
=== PASS Test optional features of p:xinclude #005
http://tests.xproc.org/tests/optional/xinclude-005.xml

[role="pass"]
=== PASS Test optional features of p:xinclude #006
http://tests.xproc.org/tests/optional/xinclude-006.xml

[role="pass"]
=== PASS Test XQuery #001
http://tests.xproc.org/tests/optional/xquery-001.xml

[role="pass"]
=== PASS Test xquery-002
http://tests.xproc.org/tests/optional/xquery-002.xml

[role="pass"]
=== PASS Test xquery-003
http://tests.xproc.org/tests/optional/xquery-003.xml

[role="pass"]
=== PASS Test xquery-004
http://tests.xproc.org/tests/optional/xquery-004.xml

[role="pass"]
=== PASS Test XQuery #005
http://tests.xproc.org/tests/optional/xquery-005.xml

[role="pass"]
=== PASS Test xquery-006
http://tests.xproc.org/tests/optional/xquery-006.xml

[role="pass"]
=== PASS Test XSL Formatter #001
http://tests.xproc.org/tests/optional/xsl-formatter-001.xml

[role="pass"]
=== PASS Test XSLT 2.0 #001
http://tests.xproc.org/tests/optional/xslt2-001.xml

[role="pass"]
=== PASS Test XSLT 2.0 #002
http://tests.xproc.org/tests/optional/xslt2-002.xml

[role="pass"]
=== PASS Test XSLT 2.0 #003
http://tests.xproc.org/tests/optional/xslt2-003.xml


== Extension tests

Passed 1 of 1 tests (100.00%).

[role="pass"]
=== PASS Test extension elements and attributes
http://tests.xproc.org/tests/extension/unimpl-001.xml


== xml-project's additional tests

Passed 24 of 24 tests (100.00%).

[role="pass"]
=== PASS Test additional choose-add-001 - test correct handling of p:choose without an output port
http://www.xml-project.com/files/xproc-tests/additional-tests/choose-add-001.xml

[role="pass"]
=== PASS Test additional try/catch 001 - test correct handling of p:try without an output port
http://www.xml-project.com/files/xproc-tests/additional-tests/try-catch-add-001.xml

[role="pass"]
=== PASS Test for-each #013
http://www.xml-project.com/files/xproc-tests/additional-tests/for-each-013.xml

[role="pass"]
=== PASS Test for-each #014
http://www.xml-project.com/files/xproc-tests/additional-tests/for-each-014.xml

[role="pass"]
=== PASS Test viewport #012
http://www.xml-project.com/files/xproc-tests/additional-tests/viewport-012.xml

[role="pass"]
=== PASS Test viewport #013
http://www.xml-project.com/files/xproc-tests/additional-tests/viewport-013.xml

[role="pass"]
=== PASS Test viewport #014
http://www.xml-project.com/files/xproc-tests/additional-tests/viewport-014.xml

[role="pass"]
=== PASS Test additional pipe 001
http://www.xml-project.com/files/xproc-tests/additional-tests/add-pipe-001.xml

[role="pass"]
=== PASS Test additional pipe 002
http://www.xml-project.com/files/xproc-tests/additional-tests/add-pipe-002.xml

[role="pass"]
=== PASS Test additional pipe 003
http://www.xml-project.com/files/xproc-tests/additional-tests/add-pipe-003.xml

[role="pass"]
=== PASS Test additional pipe 004
http://www.xml-project.com/files/xproc-tests/additional-tests/add-pipe-004.xml

[role="pass"]
=== PASS Test additional pipe 005
http://www.xml-project.com/files/xproc-tests/additional-tests/add-pipe-005.xml

[role="pass"]
=== PASS Test additional pipe 006
http://www.xml-project.com/files/xproc-tests/additional-tests/add-pipe-006.xml

[role="pass"]
=== PASS Test additional pipe 007
http://www.xml-project.com/files/xproc-tests/additional-tests/add-pipe-007.xml

[role="pass"]
=== PASS Test additional pipe 008
http://www.xml-project.com/files/xproc-tests/additional-tests/add-pipe-008.xml

[role="pass"]
=== PASS Test additional pipe 009
http://www.xml-project.com/files/xproc-tests/additional-tests/add-pipe-009.xml

[role="pass"]
=== PASS Test additional pipe-010
http://www.xml-project.com/files/xproc-tests/additional-tests/add-pipe-010.xml

[role="pass"]
=== PASS Test additional pipe 011
http://www.xml-project.com/files/xproc-tests/additional-tests/add-pipe-011.xml

[role="pass"]
=== PASS Test additional pipe 012
http://www.xml-project.com/files/xproc-tests/additional-tests/add-pipe-012.xml

[role="pass"]
=== PASS Test additional pipe 013
http://www.xml-project.com/files/xproc-tests/additional-tests/add-pipe-013.xml

[role="pass"]
=== PASS Test additional output pipe 001
http://www.xml-project.com/files/xproc-tests/additional-tests/add-output-pipe-001.xml

[role="pass"]
=== PASS Test additional output pipe 002
http://www.xml-project.com/files/xproc-tests/additional-tests/add-output-pipe-002.xml

[role="pass"]
=== PASS Test additional output pipe 003
http://www.xml-project.com/files/xproc-tests/additional-tests/add-output-pipe-003.xml

[role="pass"]
=== PASS Test xslt-add-001.xml
http://www.xml-project.com/files/xproc-tests/additional-tests/xslt-add-001.xml


== xml-project's additional tests for proposed extension steps of http://exproc.org/proposed/steps/

Passed 110 of 110 tests (100.00%).

[role="pass"]
=== PASS pos:cwd-001 - tests pos:cwd return same result as pos:info
http://www.xml-project.com/files/xproc-tests/extension-tests/pos_cwd001.xml

[role="pass"]
=== PASS pos:env-001 - tests pos:env return same result as pos:info for user and home
http://www.xml-project.com/files/xproc-tests/extension-tests/pos_env001.xml

[role="pass"]
=== PASS pos:info-001 - get system info
http://www.xml-project.com/files/xproc-tests/extension-tests/pos_info001.xml

[role="pass"]
=== PASS pxf:copy-001 - simple copy
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_copy001.xml

[role="pass"]
=== PASS pxf:copy-002 - copy to non existing folder
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_copy002.xml

[role="pass"]
=== PASS pxf:copy-003 - copy non existing file
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_copy003.xml

[role="pass"]
=== PASS pxf:copy-004 - copy to folder
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_copy004.xml

[role="pass"]
=== PASS pxf:copy-005 - copy non existing file, no fail
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_copy005.xml

[role="pass"]
=== PASS pxf:delete001 - delete a file
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_delete001.xml

[role="pass"]
=== PASS pxf:delete002 - try to delete non existing file
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_delete002.xml

[role="pass"]
=== PASS pxf:delete003 - delete non existing file, no fail
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_delete003.xml

[role="pass"]
=== PASS pxf:delete004 - delete empty folder
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_delete004.xml

[role="pass"]
=== PASS pxf:delete005 - delete a non empty folder
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_delete005.xml

[role="pass"]
=== PASS pxf:delete006 - delete a non empty folder with recursive=false
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_delete006.xml

[role="pass"]
=== PASS pxf:delete007 - delete a non empty folder with recursive=false, no fail
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_delete007.xml

[role="pass"]
=== PASS pxf:head001
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_head001.xml

[role="pass"]
=== PASS pxf:head002 - not existing
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_head002.xml

[role="pass"]
=== PASS pxf:head003 - no file
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_head003.xml

[role="pass"]
=== PASS pxf:head004 negative count
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_head004.xml

[role="pass"]
=== PASS pxf:head005 - not existing, no fail
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_head005.xml

[role="pass"]
=== PASS pxf:info_001, a file
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_info001.xml

[role="pass"]
=== PASS pxf:info_002, not existing file, no failure
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_info002.xml

[role="pass"]
=== PASS pxf:info_003, Non existing file, fail-on-error
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_info003.xml

[role="pass"]
=== PASS pxf:info_004, a directory
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_info004.xml

[role="pass"]
=== PASS pxf:info_005 - extension attribute 'content-type'
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_info005.xml

[role="pass"]
=== PASS pxf:mkdir-001 - create a folder in tmp
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_mkdir001.xml

[role="pass"]
=== PASS pxf:mkdir-002 - create an already existing folder in tmp
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_mkdir002.xml

[role="pass"]
=== PASS pxf:mkdir-003 - create an already existing folder in tmp, no fail
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_mkdir003.xml

[role="pass"]
=== PASS pxf:move-001 - simple move in same folder (rename)
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_move001.xml

[role="pass"]
=== PASS pxf:move-002 - move to non existing folder
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_move002.xml

[role="pass"]
=== PASS pxf:move-003 - move non existing file
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_move003.xml

[role="pass"]
=== PASS pxf:move-004 - move to folder
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_move004.xml

[role="pass"]
=== PASS pxf:move-005 - move non existing file, no fail
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_move005.xml

[role="pass"]
=== PASS pxf:tail001
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_tail001.xml

[role="pass"]
=== PASS pxf:tail002 - not existing
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_tail002.xml

[role="pass"]
=== PASS pxf:tail003 - no file
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_tail003.xml

[role="pass"]
=== PASS pxf:tail004 negative count
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_tail004.xml

[role="pass"]
=== PASS pxf:tail005 - not existing, no fail
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_tail005.xml

[role="pass"]
=== PASS pxf:tempdir001 - create temp dir
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_tempdir001.xml

[role="pass"]
=== PASS pxf:tempdir002 - create temp dir in non existing folder
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_tempdir002.xml

[role="pass"]
=== PASS pxf:tempdir003 - create temp dir in non writable folder
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_tempdir003.xml

[role="pass"]
=== PASS pxf:tempdir004 - create temp dir with prefix and suffix
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_tempdir004.xml

[role="pass"]
=== PASS pxf:tempfile001 - create temp file
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_tempfile001.xml

[role="pass"]
=== PASS pxf:tempfile002 - create temp file in non existing folder
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_tempfile002.xml

[role="pass"]
=== PASS pxf:tempfile003 - create temp file in non writable folder
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_tempfile003.xml

[role="pass"]
=== PASS pxf:tempfile004 - create temp file with prefix and suffix
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_tempfile004.xml

[role="pass"]
=== PASS pxf:touch001 - set date to noon of epoch
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_touch001.xml

[role="pass"]
=== PASS pxf:touch002 - not existing
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_touch002.xml

[role="pass"]
=== PASS pxf:touch003 - illegal time stamp
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_touch003.xml

[role="pass"]
=== PASS pxf:touch004 - not existing, no fail
http://www.xml-project.com/files/xproc-tests/extension-tests/pxf_touch004.xml

[role="pass"]
=== PASS pxp:set-base-uri 001. Tests pxp:set-base-uri
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_set_base_uri001.xml

[role="pass"]
=== PASS pxp:set-base-uri 002. Tests pxp:set-base-uri
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_set_base_uri002.xml

[role="pass"]
=== PASS pxp:set-base-uri 003. Tests pxp:set-base-uri
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_set_base_uri003.xml

[role="pass"]
=== PASS pxp:un-/compress001 - tests pxp:compress and pxp:uncompress with default method
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_un_compress001.xml

[role="pass"]
=== PASS pxp:un-/compress002 - tests pxp:compress and pxp:uncompress (default/gzip)
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_un_compress002.xml

[role="pass"]
=== PASS pxp:un-/compress003 - tests pxp:compress and pxp:uncompress (gzip/guess)
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_un_compress003.xml

[role="pass"]
=== PASS pxp:un-/compress004 - tests pxp:compress and pxp:uncompress (gzip/gzip)
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_un_compress004.xml

[role="pass"]
=== PASS pxp:un-/compress005 - tests pxp:compress and pxp:uncompress (bzip2/guess)
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_un_compress005.xml

[role="pass"]
=== PASS pxp:un-/compress006 - tests pxp:compress and pxp:uncompress (bzip2/bzip2)
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_un_compress006.xml

[role="pass"]
=== PASS pxp:un-/compress007 - tests pxp:compress and pxp:uncompress (deflate/guess)
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_un_compress007.xml

[role="pass"]
=== PASS pxp:un-/compress008 - tests pxp:compress and pxp:uncompress (deflate/deflate)
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_un_compress008.xml

[role="pass"]
=== PASS pxp:un-/compress009 - tests pxp:compress and pxp:uncompress (xz/guess)
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_un_compress009.xml

[role="pass"]
=== PASS pxp:un-/compress010 - tests pxp:compress and pxp:uncompress (xz/xz)
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_un_compress010.xml

[role="pass"]
=== PASS pxp:un-/compress011 - tests pxp:compress and pxp:uncompress from intermediate file
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_un_compress011.xml

[role="pass"]
=== PASS pxp:compress001 - tests pxp:compress content-type (default)
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_compress001.xml

[role="pass"]
=== PASS pxp:compress002 - tests pxp:compress content-type (gzip)
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_compress002.xml

[role="pass"]
=== PASS pxp:compress003 - tests pxp:compress content-type (bzip2)
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_compress003.xml

[role="pass"]
=== PASS pxp:compress004 - tests pxp:compress content-type (xz)
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_compress004.xml

[role="pass"]
=== PASS pxp:compress005 - tests pxp:compress with unknown method. Expected to fail with XD0030
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_compress005.xml

[role="pass"]
=== PASS pxp:compress006 - tests pxp:compress with href attribute.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_compress006.xml

[role="pass"]
=== PASS pxp:uncompress001 - tests pxp:uncompress with wrong method
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_uncompress001.xml

[role="pass"]
=== PASS pxp:uncompress002 - tests pxp:uncompress with unknown method
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_uncompress002.xml

[role="pass"]
=== PASS pxp:uncompress003 - tests pxp:uncompress with defect data
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_uncompress003.xml

[role="pass"]
=== PASS pxp:uncompress004 - tests pxp:uncompress: unencoded data flying through
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_uncompress004.xml

[role="pass"]
=== PASS pxp:unzip001 - tests pxp:unzip, correct table of content
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_unzip001.xml

[role="pass"]
=== PASS pxp:unzip002 - tests pxp:unzip, zip file does not exist
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_unzip002.xml

[role="pass"]
=== PASS pxp:unzip003 - tests pxp:unzip, listing a non zip file
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_unzip003.xml

[role="pass"]
=== PASS pxp:unzip004 - tests pxp:unzip, getting a document from the zip
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_unzip004.xml

[role="pass"]
=== PASS pxp:unzip005 - tests pxp:unzip, getting a document from the zip with xml content-type
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_unzip005.xml

[role="pass"]
=== PASS pxp:unzip006 - tests pxp:unzip, getting a document from the zip with application/octet-stream
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_unzip006.xml

[role="pass"]
=== PASS pxp:unzip007 - tests pxp:unzip, getting png from the zip with application/xml
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_unzip007.xml

[role="pass"]
=== PASS pxp:unzip008 - tests pxp:unzip, getting png from the zip with no content-type
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_unzip008.xml

[role="pass"]
=== PASS pxp:unzip009 - tests pxp:unzip, getting png from the zip with correct content-type
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_unzip009.xml

[role="pass"]
=== PASS pxp:unzip010 - tests pxp:unzip, try getting folder a zip.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_unzip010.xml

[role="pass"]
=== PASS pxp:unzip011 - tests pxp:unzip, try getting non existing file from a zip.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_unzip011.xml

[role="pass"]
=== PASS pxp:unzip012 - tests pxp:unzip, checks base-uri of unzipped document
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_unzip012.xml

[role="pass"]
=== PASS pxp:unzip013 - tests pxp:unzip, getting a document from the zip with content-type text/plain
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_unzip013.xml

[role="pass"]
=== PASS pxp:zip001 - tests pxp:zip, create zip from source port and check step result.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_zip001.xml

[role="pass"]
=== PASS pxp:zip002 - tests pxp:zip, create zip from source port and compare result with pxp:unzip
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_zip002.xml

[role="pass"]
=== PASS pxp:zip003 - tests pxp:zip, create zip from file and check step result.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_zip003.xml

[role="pass"]
=== PASS pxp:zip004 - tests pxp:zip, create zip from source port, then update and check step result.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_zip004.xml

[role="pass"]
=== PASS pxp:zip005 - tests pxp:zip, create zip from source port, then delete one and check step result.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_zip005.xml

[role="pass"]
=== PASS pxp:zip006 - tests pxp:zip, create zip from document on source port, unzip it from zip and compare.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_zip006.xml

[role="pass"]
=== PASS pxp:zip007 - tests pxp:zip, checks method 'deflated'.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_zip007.xml

[role="pass"]
=== PASS pxp:zip008 - tests pxp:zip, checks method 'stored'.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_zip008.xml

[role="pass"]
=== PASS pxp:zip009 - tests pxp:zip, checks manifest method overwrites global.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_zip009.xml

[role="pass"]
=== PASS pxp:zip010 - tests pxp:zip, raise error when compression method is unknown.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_zip010.xml

[role="pass"]
=== PASS pxp:zip011 - tests pxp:zip, raise error when value of compression-level is unknown.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_zip011.xml

[role="pass"]
=== PASS pxp:zip012 - tests pxp:zip, raise error when command is unknown.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_zip012.xml

[role="pass"]
=== PASS pxp:zip013 - tests pxp:zip, raise error when document referenced by manifest is unknown.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_zip013.xml

[role="pass"]
=== PASS pxp:zip014 - tests pxp:zip, raise error when @name is missing in manifest.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_zip014.xml

[role="pass"]
=== PASS pxp:zip015 - tests pxp:zip, raise error when @href is missing in manifest.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_zip015.xml

[role="pass"]
=== PASS pxp:zip016 - tests pxp:zip, raise error when target resource is not available.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_zip016.xml

[role="pass"]
=== PASS pxp:zip017 - tests pxp:zip, raise error when source is not available.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_zip017.xml

[role="pass"]
=== PASS pxp:nvdl001 - tests pxp:nvdl, valid document.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_nvdl001.xml

[role="pass"]
=== PASS pxp:nvdl002 - tests pxp:nvdl, invalid document.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_nvdl002.xml

[role="pass"]
=== PASS pxp:nvdl003 - tests pxp:nvdl, invalid document, but passing
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_nvdl003.xml

[role="pass"]
=== PASS pxp:nvdl004 - tests pxp:nvdl, invalid nvdl.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_nvdl004.xml

[role="pass"]
=== PASS pxp:nvdl005 - tests pxp:nvdl, missing schema.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_nvdl005.xml

[role="pass"]
=== PASS pxp:nvdl006 - tests pxp:nvdl, invalid schema.
http://www.xml-project.com/files/xproc-tests/extension-tests/pxp_nvdl006.xml


== Tests for additional features of MorganaXProc

Passed 37 of 37 tests (100.00%).

[role="pass"]
=== PASS Test xquery functions 001 - importing xquery functions to xproc context
http://www.xml-project.com/files/xproc-tests/add-feature-tests/xquery-functions-001.xml

[role="pass"]
=== PASS Test xquery functions 002 - importing xquery functions to xproc context checking namespace
http://www.xml-project.com/files/xproc-tests/add-feature-tests/xquery-functions-002.xml

[role="pass"]
=== PASS Test xquery functions 003 - importing xquery functions to xproc context, wrong namespace
http://www.xml-project.com/files/xproc-tests/add-feature-tests/xquery-functions-003.xml

[role="pass"]
=== PASS Test xquery functions 004 - importing xquery functions to xproc context, wrong uri
http://www.xml-project.com/files/xproc-tests/add-feature-tests/xquery-functions-004.xml

[role="pass"]
=== PASS Test xquery functions 005 - importing xquery functions to xproc context, function not visible
http://www.xml-project.com/files/xproc-tests/add-feature-tests/xquery-functions-005.xml

[role="pass"]
=== PASS Test xquery functions 006 - importing xquery functions to xproc context, variables not visible
http://www.xml-project.com/files/xproc-tests/add-feature-tests/xquery-functions-006.xml

[role="pass"]
=== PASS Test xquery functions 007 - importing xquery functions to xproc context, circular import fails
http://www.xml-project.com/files/xproc-tests/add-feature-tests/xquery-functions-007.xml

[role="pass"]
=== PASS Test xquery functions 008 - importing xquery functions to xproc context, checking scope - visible
http://www.xml-project.com/files/xproc-tests/add-feature-tests/xquery-functions-008.xml

[role="pass"]
=== PASS Test xquery functions 009 - importing xquery functions to xproc context, checking scope - invisible
http://www.xml-project.com/files/xproc-tests/add-feature-tests/xquery-functions-009.xml

[role="pass"]
=== PASS Test xquery functions 010 - importing xquery functions to xproc context, does not leak to imports
http://www.xml-project.com/files/xproc-tests/add-feature-tests/xquery-functions-010.xml

[role="pass"]
=== PASS Test java functions 001 - importing java functions to xproc context
http://www.xml-project.com/files/xproc-tests/add-feature-tests/java-functions-001.xml

[role="pass"]
=== PASS Test java functions 002 - importing java functions to xproc context checking namespace
http://www.xml-project.com/files/xproc-tests/add-feature-tests/java-functions-002.xml

[role="pass"]
=== PASS Test java functions 003 - importing java functions to xproc context, wrong namespace
http://www.xml-project.com/files/xproc-tests/add-feature-tests/java-functions-003.xml

[role="pass"]
=== PASS Test java functions 004 - importing java functions to xproc context, wrong uri
http://www.xml-project.com/files/xproc-tests/add-feature-tests/java-functions-004.xml

[role="pass"]
=== PASS Test java functions 005 - importing java functions to xproc context, checking scope - visible
http://www.xml-project.com/files/xproc-tests/add-feature-tests/java-functions-005.xml

[role="pass"]
=== PASS Test java functions 006 - importing java functions to xproc context, checking scope - not visible
http://www.xml-project.com/files/xproc-tests/add-feature-tests/java-functions-006.xml

[role="pass"]
=== PASS Test java functions 007- importing java functions to xproc context, checking scope, does not leak to imports
http://www.xml-project.com/files/xproc-tests/add-feature-tests/java-functions-007.xml

[role="pass"]
=== PASS Test java step 001 - importing xproc step from java library
http://www.xml-project.com/files/xproc-tests/add-feature-tests/java-step-001.xml

[role="pass"]
=== PASS Test java step 002 - importing xproc step from java library with namespace
http://www.xml-project.com/files/xproc-tests/add-feature-tests/java-step-002.xml

[role="pass"]
=== PASS Test java step 003 - importing xproc step from java library with wrong namespace
http://www.xml-project.com/files/xproc-tests/add-feature-tests/java-step-003.xml

[role="pass"]
=== PASS Test java step 004 - importing xproc step from java library with wrong class name
http://www.xml-project.com/files/xproc-tests/add-feature-tests/java-step-004.xml

[role="pass"]
=== PASS Test java step 005 - importing xproc step from java library, also importing by uri
http://www.xml-project.com/files/xproc-tests/add-feature-tests/java-step-005.xml

[role="pass"]
=== PASS Test cwd-test - make sure, cwd function and cwd step return the same result
http://www.xml-project.com/files/xproc-tests/add-feature-tests/cwd-test.xml

[role="pass"]
=== PASS Test p:data - csv
http://www.xml-project.com/files/xproc-tests/add-feature-tests/data-csv.xml

[role="pass"]
=== PASS Test extensions-001: Test presence of loaded extension step
http://www.xml-project.com/files/xproc-tests/add-feature-tests/extensions-001.xml

[role="pass"]
=== PASS Test extensions-002: Test presence of loaded extension function
http://www.xml-project.com/files/xproc-tests/add-feature-tests/extensions-002.xml

[role="pass"]
=== PASS Test extensions-003: Test presence of loaded extension step, flags import with p:import
http://www.xml-project.com/files/xproc-tests/add-feature-tests/extensions-003.xml

[role="pass"]
=== PASS Test extensions-004: Test presence of loaded extension function, flags import with p:import
http://www.xml-project.com/files/xproc-tests/add-feature-tests/extensions-004.xml

[role="pass"]
=== PASS Tests depends-on-001: Tests setting dependency between steps with extension attribute
http://www.xml-project.com/files/xproc-tests/add-feature-tests/depends-on-001.xml

[role="pass"]
=== PASS Tests depends-on-002: Tests setting dependency between steps with extension attribute. Useless depends-on
http://www.xml-project.com/files/xproc-tests/add-feature-tests/depends-on-002.xml

[role="pass"]
=== PASS Tests depends-on-003: Tests setting dependency between steps with extension attribute: unknown step
http://www.xml-project.com/files/xproc-tests/add-feature-tests/depends-on-003.xml

[role="pass"]
=== PASS Tests depends-on-004: Tests setting dependency between steps with extension attribute: circular dependency
http://www.xml-project.com/files/xproc-tests/add-feature-tests/depends-on-004.xml

[role="pass"]
=== PASS Tests depends-on-005: Tests setting dependency between steps with extension attribute: Port dependency not affected
http://www.xml-project.com/files/xproc-tests/add-feature-tests/depends-on-005.xml

[role="pass"]
=== PASS Tests depends-on-006: Tests setting dependency between steps with extension attribute: Forbidden dependency
http://www.xml-project.com/files/xproc-tests/add-feature-tests/depends-on-006.xml

[role="pass"]
=== PASS Tests depends-on-007: Tests setting dependency between steps with extension attribute: Correct dependency
http://www.xml-project.com/files/xproc-tests/add-feature-tests/depends-on-007.xml

[role="pass"]
=== PASS Tests depends-on-008: Tests setting dependency between steps with extension attribute: Circular dependency
http://www.xml-project.com/files/xproc-tests/add-feature-tests/depends-on-008.xml

[role="pass"]
=== PASS Tests depends-on-009: Tests setting dependency between steps with extension attribute: testing step list
http://www.xml-project.com/files/xproc-tests/add-feature-tests/depends-on-009.xml


