
= XProc Test Results for eXist XProc

Passed 164 of 340 tests (48.24%) on 02 Jan 2010 at 08:47p.

:toc: right

This report only shows failing tests.

[cols="<h,<,<h,<"]
|=============================================
4+<h|Processor information
|Name|eXist XProc|Language|en
|Vendor|James Fuller|XProc version|1.0
|Vendor URI|http://xproc.net/xproc|XPath version|2.0
|Version|1.5.0|PSVI Supported|false
|=============================================


== Required tests (Revision unknown)

Passed 146 of 278 tests (52.52%).

[role="fail"]
=== FAIL add-attribute-002.xml
tests/required/add-attribute-002.xml

[role="fail"]
=== FAIL add-xml-base-001.xml
tests/required/add-xml-base-001.xml

[role="fail"]
=== FAIL base-uri-002.xml
tests/required/base-uri-002.xml

[role="fail"]
=== FAIL choose-003.xml
tests/required/choose-003.xml

[role="fail"]
=== FAIL choose-006.xml
tests/required/choose-006.xml

[role="fail"]
=== FAIL compare-003.xml
tests/required/compare-003.xml

[role="fail"]
=== FAIL data-004.xml
tests/required/data-004.xml

[role="fail"]
=== FAIL data-005.xml
tests/required/data-005.xml

[role="fail"]
=== FAIL declare-step-005.xml
tests/required/declare-step-005.xml

[role="fail"]
=== FAIL declare-step-006.xml
tests/required/declare-step-006.xml

[role="fail"]
=== FAIL declare-step-011.xml
tests/required/declare-step-011.xml

[role="fail"]
=== FAIL delete-004.xml
tests/required/delete-004.xml

[role="fail"]
=== FAIL directory-list-001.xml
tests/required/directory-list-001.xml

[role="fail"]
=== FAIL directory-list-002.xml
tests/required/directory-list-002.xml

[role="fail"]
=== FAIL document-001.xml
tests/required/document-001.xml

[role="fail"]
=== FAIL exclude-inline-prefixes-005.xml
tests/required/exclude-inline-prefixes-005.xml

[role="fail"]
=== FAIL exclude-inline-prefixes-006.xml
tests/required/exclude-inline-prefixes-006.xml

[role="fail"]
=== FAIL fibonacci.xml
tests/required/fibonacci.xml

[role="fail"]
=== FAIL filter-001.xml
tests/required/filter-001.xml

[role="fail"]
=== FAIL filter-002.xml
tests/required/filter-002.xml

[role="fail"]
=== FAIL for-each-002.xml
tests/required/for-each-002.xml

[role="fail"]
=== FAIL for-each-003.xml
tests/required/for-each-003.xml

[role="fail"]
=== FAIL for-each-004.xml
tests/required/for-each-004.xml

[role="fail"]
=== FAIL for-each-006.xml
tests/required/for-each-006.xml

[role="fail"]
=== FAIL for-each-008.xml
tests/required/for-each-008.xml

[role="fail"]
=== FAIL for-each-009.xml
tests/required/for-each-009.xml

[role="fail"]
=== FAIL for-each-010.xml
tests/required/for-each-010.xml

[role="fail"]
=== FAIL http-request-003.xml
tests/required/http-request-003.xml

[role="fail"]
=== FAIL http-request-004.xml
tests/required/http-request-004.xml

[role="fail"]
=== FAIL http-request-005.xml
tests/required/http-request-005.xml

[role="fail"]
=== FAIL http-request-006.xml
tests/required/http-request-006.xml

[role="fail"]
=== FAIL http-request-011.xml
tests/required/http-request-011.xml

[role="fail"]
=== FAIL identity-003.xml
tests/required/identity-003.xml

[role="fail"]
=== FAIL import-001.xml
tests/required/import-001.xml

[role="fail"]
=== FAIL import-002.xml
tests/required/import-002.xml

[role="fail"]
=== FAIL import-004.xml
tests/required/import-004.xml

[role="fail"]
=== FAIL import-005.xml
tests/required/import-005.xml

[role="fail"]
=== FAIL import-007.xml
tests/required/import-007.xml

[role="fail"]
=== FAIL import-008.xml
tests/required/import-008.xml

[role="fail"]
=== FAIL input-002.xml
tests/required/input-002.xml

[role="fail"]
=== FAIL input-007.xml
tests/required/input-007.xml

[role="fail"]
=== FAIL input-008.xml
tests/required/input-008.xml

[role="fail"]
=== FAIL input-009.xml
tests/required/input-009.xml

[role="fail"]
=== FAIL input-010.xml
tests/required/input-010.xml

[role="fail"]
=== FAIL input-011.xml
tests/required/input-011.xml

[role="fail"]
=== FAIL input-012.xml
tests/required/input-012.xml

[role="fail"]
=== FAIL iteration-001.xml
tests/required/iteration-001.xml

[role="fail"]
=== FAIL load-001.xml
tests/required/load-001.xml

[role="fail"]
=== FAIL load-002.xml
tests/required/load-002.xml

[role="fail"]
=== FAIL load-003.xml
tests/required/load-003.xml

[role="fail"]
=== FAIL load-004.xml
tests/required/load-004.xml

[role="fail"]
=== FAIL make-absolute-uris-001.xml
tests/required/make-absolute-uris-001.xml

[role="fail"]
=== FAIL make-absolute-uris-002.xml
tests/required/make-absolute-uris-002.xml

[role="fail"]
=== FAIL make-absolute-uris-003.xml
tests/required/make-absolute-uris-003.xml

[role="fail"]
=== FAIL make-sequence.xml
tests/required/make-sequence.xml

[role="fail"]
=== FAIL namespace-rename-001.xml
tests/required/namespace-rename-001.xml

[role="fail"]
=== FAIL namespace-rename-002.xml
tests/required/namespace-rename-002.xml

[role="fail"]
=== FAIL namespace-rename-003.xml
tests/required/namespace-rename-003.xml

[role="fail"]
=== FAIL namespace-rename-004.xml
tests/required/namespace-rename-004.xml

[role="fail"]
=== FAIL namespace-rename-005.xml
tests/required/namespace-rename-005.xml

[role="fail"]
=== FAIL namespace-rename-006.xml
tests/required/namespace-rename-006.xml

[role="fail"]
=== FAIL namespace-rename-007.xml
tests/required/namespace-rename-007.xml

[role="fail"]
=== FAIL namespace-rename-008.xml
tests/required/namespace-rename-008.xml

[role="fail"]
=== FAIL namespace-rename-009.xml
tests/required/namespace-rename-009.xml

[role="fail"]
=== FAIL namespace-rename-010.xml
tests/required/namespace-rename-010.xml

[role="fail"]
=== FAIL namespace-rename-011.xml
tests/required/namespace-rename-011.xml

[role="fail"]
=== FAIL namespace-rename-012.xml
tests/required/namespace-rename-012.xml

[role="fail"]
=== FAIL namespace-rename-013.xml
tests/required/namespace-rename-013.xml

[role="fail"]
=== FAIL namespace-rename-014.xml
tests/required/namespace-rename-014.xml

[role="fail"]
=== FAIL namespace-rename-015.xml
tests/required/namespace-rename-015.xml

[role="fail"]
=== FAIL namespaces-002.xml
tests/required/namespaces-002.xml

[role="fail"]
=== FAIL namespaces-003.xml
tests/required/namespaces-003.xml

[role="fail"]
=== FAIL nested-pipeline-001.xml
tests/required/nested-pipeline-001.xml

[role="fail"]
=== FAIL option-001.xml
tests/required/option-001.xml

[role="fail"]
=== FAIL option-002.xml
tests/required/option-002.xml

[role="fail"]
=== FAIL option-004.xml
tests/required/option-004.xml

[role="fail"]
=== FAIL output-001.xml
tests/required/output-001.xml

[role="fail"]
=== FAIL output-002.xml
tests/required/output-002.xml

[role="fail"]
=== FAIL pack-003.xml
tests/required/pack-003.xml

[role="fail"]
=== FAIL pack-004.xml
tests/required/pack-004.xml

[role="fail"]
=== FAIL param-002.xml
tests/required/param-002.xml

[role="fail"]
=== FAIL param-003.xml
tests/required/param-003.xml

[role="fail"]
=== FAIL parameters-001.xml
tests/required/parameters-001.xml

[role="fail"]
=== FAIL pipeinfo-001.xml
tests/required/pipeinfo-001.xml

[role="fail"]
=== FAIL rename-002.xml
tests/required/rename-002.xml

[role="fail"]
=== FAIL rename-003.xml
tests/required/rename-003.xml

[role="fail"]
=== FAIL resolve-uri-001.xml
tests/required/resolve-uri-001.xml

[role="fail"]
=== FAIL resolve-uri-002.xml
tests/required/resolve-uri-002.xml

[role="fail"]
=== FAIL sink-001.xml
tests/required/sink-001.xml

[role="fail"]
=== FAIL sink-002.xml
tests/required/sink-002.xml

[role="fail"]
=== FAIL sink-003.xml
tests/required/sink-003.xml

[role="fail"]
=== FAIL split-sequence-002.xml
tests/required/split-sequence-002.xml

[role="fail"]
=== FAIL step-available-001.xml
tests/required/step-available-001.xml

[role="fail"]
=== FAIL step-available-002.xml
tests/required/step-available-002.xml

[role="fail"]
=== FAIL step-available-003.xml
tests/required/step-available-003.xml

[role="fail"]
=== FAIL step-available-004.xml
tests/required/step-available-004.xml

[role="fail"]
=== FAIL step-available-005.xml
tests/required/step-available-005.xml

[role="fail"]
=== FAIL step-available-006.xml
tests/required/step-available-006.xml

[role="fail"]
=== FAIL store-001.xml
tests/required/store-001.xml

[role="fail"]
=== FAIL unescapemarkup-003.xml
tests/required/unescapemarkup-003.xml

[role="fail"]
=== FAIL unescapemarkup-004.xml
tests/required/unescapemarkup-004.xml

[role="fail"]
=== FAIL unescapemarkup-005.xml
tests/required/unescapemarkup-005.xml

[role="fail"]
=== FAIL use-when-003.xml
tests/required/use-when-003.xml

[role="fail"]
=== FAIL value-available-001.xml
tests/required/value-available-001.xml

[role="fail"]
=== FAIL value-available-002.xml
tests/required/value-available-002.xml

[role="fail"]
=== FAIL value-available-003.xml
tests/required/value-available-003.xml

[role="fail"]
=== FAIL value-available-004.xml
tests/required/value-available-004.xml

[role="fail"]
=== FAIL value-available-005.xml
tests/required/value-available-005.xml

[role="fail"]
=== FAIL value-available-006.xml
tests/required/value-available-006.xml

[role="fail"]
=== FAIL variable-001.xml
tests/required/variable-001.xml

[role="fail"]
=== FAIL variable-002.xml
tests/required/variable-002.xml

[role="fail"]
=== FAIL variable-003.xml
tests/required/variable-003.xml

[role="fail"]
=== FAIL variable-004.xml
tests/required/variable-004.xml

[role="fail"]
=== FAIL version-available-001.xml
tests/required/version-available-001.xml

[role="fail"]
=== FAIL version-available-002.xml
tests/required/version-available-002.xml

[role="fail"]
=== FAIL versioning-002.xml
tests/required/versioning-002.xml

[role="fail"]
=== FAIL versioning-006.xml
tests/required/versioning-006.xml

[role="fail"]
=== FAIL versioning-007.xml
tests/required/versioning-007.xml

[role="fail"]
=== FAIL viewport-002.xml
tests/required/viewport-002.xml

[role="fail"]
=== FAIL viewport-007.xml
tests/required/viewport-007.xml

[role="fail"]
=== FAIL viewport-008.xml
tests/required/viewport-008.xml

[role="fail"]
=== FAIL wrap-005.xml
tests/required/wrap-005.xml

[role="fail"]
=== FAIL wrap-006.xml
tests/required/wrap-006.xml

[role="fail"]
=== FAIL wrap-007.xml
tests/required/wrap-007.xml

[role="fail"]
=== FAIL wrap-008.xml
tests/required/wrap-008.xml

[role="fail"]
=== FAIL xinclude-001.xml
tests/required/xinclude-001.xml

[role="fail"]
=== FAIL xinclude-004.xml
tests/required/xinclude-004.xml

[role="fail"]
=== FAIL xinclude-005.xml
tests/required/xinclude-005.xml

[role="fail"]
=== FAIL xpath-version-available-001.xml
tests/required/xpath-version-available-001.xml

[role="fail"]
=== FAIL xpath-version-available-002.xml
tests/required/xpath-version-available-002.xml

[role="fail"]
=== FAIL xslt-002.xml
tests/required/xslt-002.xml

[role="fail"]
=== FAIL xslt-006.xml
tests/required/xslt-006.xml


== Optional

Passed 18 of 62 tests (29.03%).

[role="fail"]
=== FAIL exec-001.xml
tests/optional/exec-001.xml

[role="fail"]
=== FAIL exec-006.xml
tests/optional/exec-006.xml

[role="fail"]
=== FAIL exec-007.xml
tests/optional/exec-007.xml

[role="fail"]
=== FAIL exec-008.xml
tests/optional/exec-008.xml

[role="fail"]
=== FAIL exec-010.xml
tests/optional/exec-010.xml

[role="fail"]
=== FAIL exec-012.xml
tests/optional/exec-012.xml

[role="fail"]
=== FAIL exec-013.xml
tests/optional/exec-013.xml

[role="fail"]
=== FAIL exec-014.xml
tests/optional/exec-014.xml

[role="fail"]
=== FAIL exec-015.xml
tests/optional/exec-015.xml

[role="fail"]
=== FAIL exec-017.xml
tests/optional/exec-017.xml

[role="fail"]
=== FAIL hash-001.xml
tests/optional/hash-001.xml

[role="fail"]
=== FAIL hash-002.xml
tests/optional/hash-002.xml

[role="fail"]
=== FAIL hash-004.xml
tests/optional/hash-004.xml

[role="fail"]
=== FAIL hash-005.xml
tests/optional/hash-005.xml

[role="fail"]
=== FAIL validrng-003.xml
tests/optional/validrng-003.xml

[role="fail"]
=== FAIL validrng-004.xml
tests/optional/validrng-004.xml

[role="fail"]
=== FAIL validrng-005.xml
tests/optional/validrng-005.xml

[role="fail"]
=== FAIL validrng-006.xml
tests/optional/validrng-006.xml

[role="fail"]
=== FAIL validrng-007.xml
tests/optional/validrng-007.xml

[role="fail"]
=== FAIL validrng-008.xml
tests/optional/validrng-008.xml

[role="fail"]
=== FAIL validrng-009.xml
tests/optional/validrng-009.xml

[role="fail"]
=== FAIL validsch-001.xml
tests/optional/validsch-001.xml

[role="fail"]
=== FAIL validsch-003.xml
tests/optional/validsch-003.xml

[role="fail"]
=== FAIL validsch-004.xml
tests/optional/validsch-004.xml

[role="fail"]
=== FAIL validsch-005.xml
tests/optional/validsch-005.xml

[role="fail"]
=== FAIL validxsd-001.xml
tests/optional/validxsd-001.xml

[role="fail"]
=== FAIL validxsd-002.xml
tests/optional/validxsd-002.xml

[role="fail"]
=== FAIL validxsd-003.xml
tests/optional/validxsd-003.xml

[role="fail"]
=== FAIL validxsd-004.xml
tests/optional/validxsd-004.xml

[role="fail"]
=== FAIL validxsd-005.xml
tests/optional/validxsd-005.xml

[role="fail"]
=== FAIL validxsd-006.xml
tests/optional/validxsd-006.xml

[role="fail"]
=== FAIL validxsd-008.xml
tests/optional/validxsd-008.xml

[role="fail"]
=== FAIL validxsd-009.xml
tests/optional/validxsd-009.xml

[role="fail"]
=== FAIL validxsd-010.xml
tests/optional/validxsd-010.xml

[role="fail"]
=== FAIL validxsd-011.xml
tests/optional/validxsd-011.xml

[role="fail"]
=== FAIL validxsd-012.xml
tests/optional/validxsd-012.xml

[role="fail"]
=== FAIL www-form-urldecode-001.xml
tests/optional/www-form-urldecode-001.xml

[role="fail"]
=== FAIL www-form-urlencode-001.xml
tests/optional/www-form-urlencode-001.xml

[role="fail"]
=== FAIL xquery-003.xml
tests/optional/xquery-003.xml

[role="fail"]
=== FAIL xquery-004.xml
tests/optional/xquery-004.xml

[role="fail"]
=== FAIL xquery-005.xml
tests/optional/xquery-005.xml

[role="fail"]
=== FAIL xquery-006.xml
tests/optional/xquery-006.xml

[role="fail"]
=== FAIL xsl-formatter-001.xml
tests/optional/xsl-formatter-001.xml

[role="fail"]
=== FAIL xslt2-002.xml
tests/optional/xslt2-002.xml

