
= XProc Test Results for eXist XProc

Passed 164 of 340 tests (48.24%) on 02 Jan 2010 at 08:47p.

:toc: right

[cols="<h,<,<h,<"]
|=============================================
4+<h|Processor information
|Name|eXist XProc|Language|en
|Vendor|James Fuller|XProc version|1.0
|Vendor URI|http://xproc.net/xproc|XPath version|2.0
|Version|1.5.0|PSVI Supported|false
|=============================================


== Required tests (Revision unknown)

Passed 146 of 278 tests (52.52%).

[role="pass"]
=== PASS add-attribute-001.xml
tests/required/add-attribute-001.xml

[role="fail"]
=== FAIL add-attribute-002.xml
tests/required/add-attribute-002.xml

[role="pass"]
=== PASS add-attribute-003.xml
tests/required/add-attribute-003.xml

[role="pass"]
=== PASS add-attribute-004.xml
tests/required/add-attribute-004.xml

[role="fail"]
=== FAIL add-xml-base-001.xml
tests/required/add-xml-base-001.xml

[role="pass"]
=== PASS add-xml-base-002.xml
tests/required/add-xml-base-002.xml

[role="pass"]
=== PASS add-xml-base-003.xml
tests/required/add-xml-base-003.xml

[role="pass"]
=== PASS add-xml-base-004.xml
tests/required/add-xml-base-004.xml

[role="pass"]
=== PASS add-xml-base-005.xml
tests/required/add-xml-base-005.xml

[role="pass"]
=== PASS add-xml-base-006.xml
tests/required/add-xml-base-006.xml

[role="pass"]
=== PASS base-uri-001.xml
tests/required/base-uri-001.xml

[role="fail"]
=== FAIL base-uri-002.xml
tests/required/base-uri-002.xml

[role="pass"]
=== PASS choose-001.xml
tests/required/choose-001.xml

[role="pass"]
=== PASS choose-002.xml
tests/required/choose-002.xml

[role="fail"]
=== FAIL choose-003.xml
tests/required/choose-003.xml

[role="pass"]
=== PASS choose-004.xml
tests/required/choose-004.xml

[role="pass"]
=== PASS choose-005.xml
tests/required/choose-005.xml

[role="fail"]
=== FAIL choose-006.xml
tests/required/choose-006.xml

[role="pass"]
=== PASS compare-001.xml
tests/required/compare-001.xml

[role="pass"]
=== PASS compare-002.xml
tests/required/compare-002.xml

[role="fail"]
=== FAIL compare-003.xml
tests/required/compare-003.xml

[role="pass"]
=== PASS compare-004.xml
tests/required/compare-004.xml

[role="pass"]
=== PASS compare-005.xml
tests/required/compare-005.xml

[role="pass"]
=== PASS count-001.xml
tests/required/count-001.xml

[role="pass"]
=== PASS count-002.xml
tests/required/count-002.xml

[role="pass"]
=== PASS count-003.xml
tests/required/count-003.xml

[role="pass"]
=== PASS data-001.xml
tests/required/data-001.xml

[role="pass"]
=== PASS data-002.xml
tests/required/data-002.xml

[role="pass"]
=== PASS data-003.xml
tests/required/data-003.xml

[role="fail"]
=== FAIL data-004.xml
tests/required/data-004.xml

[role="fail"]
=== FAIL data-005.xml
tests/required/data-005.xml

[role="pass"]
=== PASS declare-step-001.xml
tests/required/declare-step-001.xml

[role="pass"]
=== PASS declare-step-002.xml
tests/required/declare-step-002.xml

[role="pass"]
=== PASS declare-step-003.xml
tests/required/declare-step-003.xml

[role="pass"]
=== PASS declare-step-004.xml
tests/required/declare-step-004.xml

[role="fail"]
=== FAIL declare-step-005.xml
tests/required/declare-step-005.xml

[role="fail"]
=== FAIL declare-step-006.xml
tests/required/declare-step-006.xml

[role="pass"]
=== PASS declare-step-007.xml
tests/required/declare-step-007.xml

[role="pass"]
=== PASS declare-step-008.xml
tests/required/declare-step-008.xml

[role="pass"]
=== PASS declare-step-009.xml
tests/required/declare-step-009.xml

[role="pass"]
=== PASS declare-step-010.xml
tests/required/declare-step-010.xml

[role="fail"]
=== FAIL declare-step-011.xml
tests/required/declare-step-011.xml

[role="pass"]
=== PASS delete-001.xml
tests/required/delete-001.xml

[role="pass"]
=== PASS delete-002.xml
tests/required/delete-002.xml

[role="pass"]
=== PASS delete-003.xml
tests/required/delete-003.xml

[role="fail"]
=== FAIL delete-004.xml
tests/required/delete-004.xml

[role="fail"]
=== FAIL directory-list-001.xml
tests/required/directory-list-001.xml

[role="fail"]
=== FAIL directory-list-002.xml
tests/required/directory-list-002.xml

[role="fail"]
=== FAIL document-001.xml
tests/required/document-001.xml

[role="pass"]
=== PASS escape-markup-001.xml
tests/required/escape-markup-001.xml

[role="pass"]
=== PASS evaluation-order-001.xml
tests/required/evaluation-order-001.xml

[role="pass"]
=== PASS evaluation-order-002.xml
tests/required/evaluation-order-002.xml

[role="pass"]
=== PASS evaluation-order-003.xml
tests/required/evaluation-order-003.xml

[role="pass"]
=== PASS exclude-inline-prefixes-001.xml
tests/required/exclude-inline-prefixes-001.xml

[role="pass"]
=== PASS exclude-inline-prefixes-002.xml
tests/required/exclude-inline-prefixes-002.xml

[role="pass"]
=== PASS exclude-inline-prefixes-003.xml
tests/required/exclude-inline-prefixes-003.xml

[role="pass"]
=== PASS exclude-inline-prefixes-004.xml
tests/required/exclude-inline-prefixes-004.xml

[role="fail"]
=== FAIL exclude-inline-prefixes-005.xml
tests/required/exclude-inline-prefixes-005.xml

[role="fail"]
=== FAIL exclude-inline-prefixes-006.xml
tests/required/exclude-inline-prefixes-006.xml

[role="pass"]
=== PASS exclude-inline-prefixes-007.xml
tests/required/exclude-inline-prefixes-007.xml

[role="fail"]
=== FAIL fibonacci.xml
tests/required/fibonacci.xml

[role="fail"]
=== FAIL filter-001.xml
tests/required/filter-001.xml

[role="fail"]
=== FAIL filter-002.xml
tests/required/filter-002.xml

[role="pass"]
=== PASS filter-003.xml
tests/required/filter-003.xml

[role="pass"]
=== PASS for-each-001.xml
tests/required/for-each-001.xml

[role="fail"]
=== FAIL for-each-002.xml
tests/required/for-each-002.xml

[role="fail"]
=== FAIL for-each-003.xml
tests/required/for-each-003.xml

[role="fail"]
=== FAIL for-each-004.xml
tests/required/for-each-004.xml

[role="pass"]
=== PASS for-each-005.xml
tests/required/for-each-005.xml

[role="fail"]
=== FAIL for-each-006.xml
tests/required/for-each-006.xml

[role="pass"]
=== PASS for-each-007.xml
tests/required/for-each-007.xml

[role="fail"]
=== FAIL for-each-008.xml
tests/required/for-each-008.xml

[role="fail"]
=== FAIL for-each-009.xml
tests/required/for-each-009.xml

[role="fail"]
=== FAIL for-each-010.xml
tests/required/for-each-010.xml

[role="pass"]
=== PASS group-001.xml
tests/required/group-001.xml

[role="pass"]
=== PASS group-002.xml
tests/required/group-002.xml

[role="pass"]
=== PASS http-request-001.xml
tests/required/http-request-001.xml

[role="pass"]
=== PASS http-request-002.xml
tests/required/http-request-002.xml

[role="fail"]
=== FAIL http-request-003.xml
tests/required/http-request-003.xml

[role="fail"]
=== FAIL http-request-004.xml
tests/required/http-request-004.xml

[role="fail"]
=== FAIL http-request-005.xml
tests/required/http-request-005.xml

[role="fail"]
=== FAIL http-request-006.xml
tests/required/http-request-006.xml

[role="pass"]
=== PASS http-request-007.xml
tests/required/http-request-007.xml

[role="pass"]
=== PASS http-request-008.xml
tests/required/http-request-008.xml

[role="pass"]
=== PASS http-request-009.xml
tests/required/http-request-009.xml

[role="pass"]
=== PASS http-request-010.xml
tests/required/http-request-010.xml

[role="fail"]
=== FAIL http-request-011.xml
tests/required/http-request-011.xml

[role="pass"]
=== PASS http-request-012.xml
tests/required/http-request-012.xml

[role="pass"]
=== PASS http-request-013.xml
tests/required/http-request-013.xml

[role="pass"]
=== PASS identity-001.xml
tests/required/identity-001.xml

[role="pass"]
=== PASS identity-002.xml
tests/required/identity-002.xml

[role="fail"]
=== FAIL identity-003.xml
tests/required/identity-003.xml

[role="pass"]
=== PASS identity-004.xml
tests/required/identity-004.xml

[role="pass"]
=== PASS identity-005.xml
tests/required/identity-005.xml

[role="fail"]
=== FAIL import-001.xml
tests/required/import-001.xml

[role="fail"]
=== FAIL import-002.xml
tests/required/import-002.xml

[role="fail"]
=== FAIL import-004.xml
tests/required/import-004.xml

[role="fail"]
=== FAIL import-005.xml
tests/required/import-005.xml

[role="pass"]
=== PASS import-006.xml
tests/required/import-006.xml

[role="fail"]
=== FAIL import-007.xml
tests/required/import-007.xml

[role="fail"]
=== FAIL import-008.xml
tests/required/import-008.xml

[role="pass"]
=== PASS input-001.xml
tests/required/input-001.xml

[role="fail"]
=== FAIL input-002.xml
tests/required/input-002.xml

[role="pass"]
=== PASS input-003.xml
tests/required/input-003.xml

[role="pass"]
=== PASS input-004.xml
tests/required/input-004.xml

[role="pass"]
=== PASS input-005.xml
tests/required/input-005.xml

[role="pass"]
=== PASS input-006.xml
tests/required/input-006.xml

[role="fail"]
=== FAIL input-007.xml
tests/required/input-007.xml

[role="fail"]
=== FAIL input-008.xml
tests/required/input-008.xml

[role="fail"]
=== FAIL input-009.xml
tests/required/input-009.xml

[role="fail"]
=== FAIL input-010.xml
tests/required/input-010.xml

[role="fail"]
=== FAIL input-011.xml
tests/required/input-011.xml

[role="fail"]
=== FAIL input-012.xml
tests/required/input-012.xml

[role="pass"]
=== PASS insert-001.xml
tests/required/insert-001.xml

[role="pass"]
=== PASS insert-002.xml
tests/required/insert-002.xml

[role="pass"]
=== PASS insert-003.xml
tests/required/insert-003.xml

[role="pass"]
=== PASS insert-004.xml
tests/required/insert-004.xml

[role="pass"]
=== PASS insert-005.xml
tests/required/insert-005.xml

[role="pass"]
=== PASS insert-006.xml
tests/required/insert-006.xml

[role="pass"]
=== PASS insert-007.xml
tests/required/insert-007.xml

[role="pass"]
=== PASS insert-008.xml
tests/required/insert-008.xml

[role="pass"]
=== PASS insert-009.xml
tests/required/insert-009.xml

[role="fail"]
=== FAIL iteration-001.xml
tests/required/iteration-001.xml

[role="pass"]
=== PASS iteration-002.xml
tests/required/iteration-002.xml

[role="pass"]
=== PASS labelelements-001.xml
tests/required/labelelements-001.xml

[role="pass"]
=== PASS labelelements-002.xml
tests/required/labelelements-002.xml

[role="pass"]
=== PASS labelelements-003.xml
tests/required/labelelements-003.xml

[role="pass"]
=== PASS labelelements-004.xml
tests/required/labelelements-004.xml

[role="pass"]
=== PASS labelelements-005.xml
tests/required/labelelements-005.xml

[role="pass"]
=== PASS labelelements-006.xml
tests/required/labelelements-006.xml

[role="fail"]
=== FAIL load-001.xml
tests/required/load-001.xml

[role="fail"]
=== FAIL load-002.xml
tests/required/load-002.xml

[role="fail"]
=== FAIL load-003.xml
tests/required/load-003.xml

[role="fail"]
=== FAIL load-004.xml
tests/required/load-004.xml

[role="fail"]
=== FAIL make-absolute-uris-001.xml
tests/required/make-absolute-uris-001.xml

[role="fail"]
=== FAIL make-absolute-uris-002.xml
tests/required/make-absolute-uris-002.xml

[role="fail"]
=== FAIL make-absolute-uris-003.xml
tests/required/make-absolute-uris-003.xml

[role="fail"]
=== FAIL make-sequence.xml
tests/required/make-sequence.xml

[role="fail"]
=== FAIL namespace-rename-001.xml
tests/required/namespace-rename-001.xml

[role="fail"]
=== FAIL namespace-rename-002.xml
tests/required/namespace-rename-002.xml

[role="fail"]
=== FAIL namespace-rename-003.xml
tests/required/namespace-rename-003.xml

[role="fail"]
=== FAIL namespace-rename-004.xml
tests/required/namespace-rename-004.xml

[role="fail"]
=== FAIL namespace-rename-005.xml
tests/required/namespace-rename-005.xml

[role="fail"]
=== FAIL namespace-rename-006.xml
tests/required/namespace-rename-006.xml

[role="fail"]
=== FAIL namespace-rename-007.xml
tests/required/namespace-rename-007.xml

[role="fail"]
=== FAIL namespace-rename-008.xml
tests/required/namespace-rename-008.xml

[role="fail"]
=== FAIL namespace-rename-009.xml
tests/required/namespace-rename-009.xml

[role="fail"]
=== FAIL namespace-rename-010.xml
tests/required/namespace-rename-010.xml

[role="fail"]
=== FAIL namespace-rename-011.xml
tests/required/namespace-rename-011.xml

[role="fail"]
=== FAIL namespace-rename-012.xml
tests/required/namespace-rename-012.xml

[role="fail"]
=== FAIL namespace-rename-013.xml
tests/required/namespace-rename-013.xml

[role="fail"]
=== FAIL namespace-rename-014.xml
tests/required/namespace-rename-014.xml

[role="fail"]
=== FAIL namespace-rename-015.xml
tests/required/namespace-rename-015.xml

[role="pass"]
=== PASS namespaces-001.xml
tests/required/namespaces-001.xml

[role="fail"]
=== FAIL namespaces-002.xml
tests/required/namespaces-002.xml

[role="fail"]
=== FAIL namespaces-003.xml
tests/required/namespaces-003.xml

[role="pass"]
=== PASS namespaces-004.xml
tests/required/namespaces-004.xml

[role="fail"]
=== FAIL nested-pipeline-001.xml
tests/required/nested-pipeline-001.xml

[role="fail"]
=== FAIL option-001.xml
tests/required/option-001.xml

[role="fail"]
=== FAIL option-002.xml
tests/required/option-002.xml

[role="fail"]
=== FAIL option-004.xml
tests/required/option-004.xml

[role="fail"]
=== FAIL output-001.xml
tests/required/output-001.xml

[role="fail"]
=== FAIL output-002.xml
tests/required/output-002.xml

[role="pass"]
=== PASS pack-001.xml
tests/required/pack-001.xml

[role="pass"]
=== PASS pack-002.xml
tests/required/pack-002.xml

[role="fail"]
=== FAIL pack-003.xml
tests/required/pack-003.xml

[role="fail"]
=== FAIL pack-004.xml
tests/required/pack-004.xml

[role="pass"]
=== PASS param-001.xml
tests/required/param-001.xml

[role="fail"]
=== FAIL param-002.xml
tests/required/param-002.xml

[role="fail"]
=== FAIL param-003.xml
tests/required/param-003.xml

[role="fail"]
=== FAIL parameters-001.xml
tests/required/parameters-001.xml

[role="pass"]
=== PASS parameters-002.xml
tests/required/parameters-002.xml

[role="pass"]
=== PASS pipe-001.xml
tests/required/pipe-001.xml

[role="fail"]
=== FAIL pipeinfo-001.xml
tests/required/pipeinfo-001.xml

[role="pass"]
=== PASS preserve-base-uri-001.xml
tests/required/preserve-base-uri-001.xml

[role="pass"]
=== PASS preserve-base-uri-002.xml
tests/required/preserve-base-uri-002.xml

[role="pass"]
=== PASS rename-001.xml
tests/required/rename-001.xml

[role="fail"]
=== FAIL rename-002.xml
tests/required/rename-002.xml

[role="fail"]
=== FAIL rename-003.xml
tests/required/rename-003.xml

[role="pass"]
=== PASS replace-001.xml
tests/required/replace-001.xml

[role="fail"]
=== FAIL resolve-uri-001.xml
tests/required/resolve-uri-001.xml

[role="fail"]
=== FAIL resolve-uri-002.xml
tests/required/resolve-uri-002.xml

[role="pass"]
=== PASS set-attributes-001.xml
tests/required/set-attributes-001.xml

[role="pass"]
=== PASS set-attributes-002.xml
tests/required/set-attributes-002.xml

[role="fail"]
=== FAIL sink-001.xml
tests/required/sink-001.xml

[role="fail"]
=== FAIL sink-002.xml
tests/required/sink-002.xml

[role="fail"]
=== FAIL sink-003.xml
tests/required/sink-003.xml

[role="pass"]
=== PASS split-sequence-001.xml
tests/required/split-sequence-001.xml

[role="fail"]
=== FAIL split-sequence-002.xml
tests/required/split-sequence-002.xml

[role="pass"]
=== PASS split-sequence-003.xml
tests/required/split-sequence-003.xml

[role="pass"]
=== PASS split-sequence-004.xml
tests/required/split-sequence-004.xml

[role="pass"]
=== PASS split-sequence-005.xml
tests/required/split-sequence-005.xml

[role="pass"]
=== PASS split-sequence-006.xml
tests/required/split-sequence-006.xml

[role="pass"]
=== PASS split-sequence-007.xml
tests/required/split-sequence-007.xml

[role="fail"]
=== FAIL step-available-001.xml
tests/required/step-available-001.xml

[role="fail"]
=== FAIL step-available-002.xml
tests/required/step-available-002.xml

[role="fail"]
=== FAIL step-available-003.xml
tests/required/step-available-003.xml

[role="fail"]
=== FAIL step-available-004.xml
tests/required/step-available-004.xml

[role="fail"]
=== FAIL step-available-005.xml
tests/required/step-available-005.xml

[role="fail"]
=== FAIL step-available-006.xml
tests/required/step-available-006.xml

[role="fail"]
=== FAIL store-001.xml
tests/required/store-001.xml

[role="pass"]
=== PASS string-replace-001.xml
tests/required/string-replace-001.xml

[role="pass"]
=== PASS string-replace-002.xml
tests/required/string-replace-002.xml

[role="pass"]
=== PASS string-replace-003.xml
tests/required/string-replace-003.xml

[role="pass"]
=== PASS string-replace-004.xml
tests/required/string-replace-004.xml

[role="pass"]
=== PASS system-property-001.xml
tests/required/system-property-001.xml

[role="pass"]
=== PASS system-property-002.xml
tests/required/system-property-002.xml

[role="pass"]
=== PASS try-001.xml
tests/required/try-001.xml

[role="pass"]
=== PASS try-002.xml
tests/required/try-002.xml

[role="pass"]
=== PASS try-003.xml
tests/required/try-003.xml

[role="pass"]
=== PASS try-004.xml
tests/required/try-004.xml

[role="pass"]
=== PASS unescapemarkup-001.xml
tests/required/unescapemarkup-001.xml

[role="pass"]
=== PASS unescapemarkup-002.xml
tests/required/unescapemarkup-002.xml

[role="fail"]
=== FAIL unescapemarkup-003.xml
tests/required/unescapemarkup-003.xml

[role="fail"]
=== FAIL unescapemarkup-004.xml
tests/required/unescapemarkup-004.xml

[role="fail"]
=== FAIL unescapemarkup-005.xml
tests/required/unescapemarkup-005.xml

[role="pass"]
=== PASS unescapemarkup-006.xml
tests/required/unescapemarkup-006.xml

[role="pass"]
=== PASS unescapemarkup-007.xml
tests/required/unescapemarkup-007.xml

[role="pass"]
=== PASS unwrap-001.xml
tests/required/unwrap-001.xml

[role="pass"]
=== PASS unwrap-002.xml
tests/required/unwrap-002.xml

[role="pass"]
=== PASS use-when-001.xml
tests/required/use-when-001.xml

[role="pass"]
=== PASS use-when-002.xml
tests/required/use-when-002.xml

[role="fail"]
=== FAIL use-when-003.xml
tests/required/use-when-003.xml

[role="fail"]
=== FAIL value-available-001.xml
tests/required/value-available-001.xml

[role="fail"]
=== FAIL value-available-002.xml
tests/required/value-available-002.xml

[role="fail"]
=== FAIL value-available-003.xml
tests/required/value-available-003.xml

[role="fail"]
=== FAIL value-available-004.xml
tests/required/value-available-004.xml

[role="fail"]
=== FAIL value-available-005.xml
tests/required/value-available-005.xml

[role="fail"]
=== FAIL value-available-006.xml
tests/required/value-available-006.xml

[role="fail"]
=== FAIL variable-001.xml
tests/required/variable-001.xml

[role="fail"]
=== FAIL variable-002.xml
tests/required/variable-002.xml

[role="fail"]
=== FAIL variable-003.xml
tests/required/variable-003.xml

[role="fail"]
=== FAIL variable-004.xml
tests/required/variable-004.xml

[role="fail"]
=== FAIL version-available-001.xml
tests/required/version-available-001.xml

[role="fail"]
=== FAIL version-available-002.xml
tests/required/version-available-002.xml

[role="pass"]
=== PASS versioning-001.xml
tests/required/versioning-001.xml

[role="fail"]
=== FAIL versioning-002.xml
tests/required/versioning-002.xml

[role="pass"]
=== PASS versioning-003.xml
tests/required/versioning-003.xml

[role="pass"]
=== PASS versioning-004.xml
tests/required/versioning-004.xml

[role="pass"]
=== PASS versioning-005.xml
tests/required/versioning-005.xml

[role="fail"]
=== FAIL versioning-006.xml
tests/required/versioning-006.xml

[role="fail"]
=== FAIL versioning-007.xml
tests/required/versioning-007.xml

[role="pass"]
=== PASS viewport-001.xml
tests/required/viewport-001.xml

[role="fail"]
=== FAIL viewport-002.xml
tests/required/viewport-002.xml

[role="pass"]
=== PASS viewport-003.xml
tests/required/viewport-003.xml

[role="pass"]
=== PASS viewport-004.xml
tests/required/viewport-004.xml

[role="pass"]
=== PASS viewport-005.xml
tests/required/viewport-005.xml

[role="pass"]
=== PASS viewport-006.xml
tests/required/viewport-006.xml

[role="fail"]
=== FAIL viewport-007.xml
tests/required/viewport-007.xml

[role="fail"]
=== FAIL viewport-008.xml
tests/required/viewport-008.xml

[role="pass"]
=== PASS viewport-009.xml
tests/required/viewport-009.xml

[role="pass"]
=== PASS viewport-010.xml
tests/required/viewport-010.xml

[role="pass"]
=== PASS wrap-001.xml
tests/required/wrap-001.xml

[role="pass"]
=== PASS wrap-002.xml
tests/required/wrap-002.xml

[role="pass"]
=== PASS wrap-003.xml
tests/required/wrap-003.xml

[role="pass"]
=== PASS wrap-004.xml
tests/required/wrap-004.xml

[role="fail"]
=== FAIL wrap-005.xml
tests/required/wrap-005.xml

[role="fail"]
=== FAIL wrap-006.xml
tests/required/wrap-006.xml

[role="fail"]
=== FAIL wrap-007.xml
tests/required/wrap-007.xml

[role="fail"]
=== FAIL wrap-008.xml
tests/required/wrap-008.xml

[role="pass"]
=== PASS wrap-009.xml
tests/required/wrap-009.xml

[role="pass"]
=== PASS wrap-sequence-001.xml
tests/required/wrap-sequence-001.xml

[role="pass"]
=== PASS wrap-sequence-002.xml
tests/required/wrap-sequence-002.xml

[role="fail"]
=== FAIL xinclude-001.xml
tests/required/xinclude-001.xml

[role="pass"]
=== PASS xinclude-002.xml
tests/required/xinclude-002.xml

[role="pass"]
=== PASS xinclude-003.xml
tests/required/xinclude-003.xml

[role="fail"]
=== FAIL xinclude-004.xml
tests/required/xinclude-004.xml

[role="fail"]
=== FAIL xinclude-005.xml
tests/required/xinclude-005.xml

[role="pass"]
=== PASS xml-id-001.xml
tests/required/xml-id-001.xml

[role="pass"]
=== PASS xml-id-002.xml
tests/required/xml-id-002.xml

[role="fail"]
=== FAIL xpath-version-available-001.xml
tests/required/xpath-version-available-001.xml

[role="fail"]
=== FAIL xpath-version-available-002.xml
tests/required/xpath-version-available-002.xml

[role="pass"]
=== PASS xslt-001.xml
tests/required/xslt-001.xml

[role="fail"]
=== FAIL xslt-002.xml
tests/required/xslt-002.xml

[role="pass"]
=== PASS xslt-003.xml
tests/required/xslt-003.xml

[role="pass"]
=== PASS xslt-004.xml
tests/required/xslt-004.xml

[role="pass"]
=== PASS xslt-005.xml
tests/required/xslt-005.xml

[role="fail"]
=== FAIL xslt-006.xml
tests/required/xslt-006.xml


== Optional

Passed 18 of 62 tests (29.03%).

[role="fail"]
=== FAIL exec-001.xml
tests/optional/exec-001.xml

[role="pass"]
=== PASS exec-002.xml
tests/optional/exec-002.xml

[role="pass"]
=== PASS exec-003.xml
tests/optional/exec-003.xml

[role="pass"]
=== PASS exec-004.xml
tests/optional/exec-004.xml

[role="pass"]
=== PASS exec-005.xml
tests/optional/exec-005.xml

[role="fail"]
=== FAIL exec-006.xml
tests/optional/exec-006.xml

[role="fail"]
=== FAIL exec-007.xml
tests/optional/exec-007.xml

[role="fail"]
=== FAIL exec-008.xml
tests/optional/exec-008.xml

[role="pass"]
=== PASS exec-009.xml
tests/optional/exec-009.xml

[role="fail"]
=== FAIL exec-010.xml
tests/optional/exec-010.xml

[role="pass"]
=== PASS exec-011.xml
tests/optional/exec-011.xml

[role="fail"]
=== FAIL exec-012.xml
tests/optional/exec-012.xml

[role="fail"]
=== FAIL exec-013.xml
tests/optional/exec-013.xml

[role="fail"]
=== FAIL exec-014.xml
tests/optional/exec-014.xml

[role="fail"]
=== FAIL exec-015.xml
tests/optional/exec-015.xml

[role="pass"]
=== PASS exec-016.xml
tests/optional/exec-016.xml

[role="fail"]
=== FAIL exec-017.xml
tests/optional/exec-017.xml

[role="fail"]
=== FAIL hash-001.xml
tests/optional/hash-001.xml

[role="fail"]
=== FAIL hash-002.xml
tests/optional/hash-002.xml

[role="pass"]
=== PASS hash-003.xml
tests/optional/hash-003.xml

[role="fail"]
=== FAIL hash-004.xml
tests/optional/hash-004.xml

[role="fail"]
=== FAIL hash-005.xml
tests/optional/hash-005.xml

[role="pass"]
=== PASS hash-006.xml
tests/optional/hash-006.xml

[role="pass"]
=== PASS uuid-001.xml
tests/optional/uuid-001.xml

[role="pass"]
=== PASS validrng-001.xml
tests/optional/validrng-001.xml

[role="pass"]
=== PASS validrng-002.xml
tests/optional/validrng-002.xml

[role="fail"]
=== FAIL validrng-003.xml
tests/optional/validrng-003.xml

[role="fail"]
=== FAIL validrng-004.xml
tests/optional/validrng-004.xml

[role="fail"]
=== FAIL validrng-005.xml
tests/optional/validrng-005.xml

[role="fail"]
=== FAIL validrng-006.xml
tests/optional/validrng-006.xml

[role="fail"]
=== FAIL validrng-007.xml
tests/optional/validrng-007.xml

[role="fail"]
=== FAIL validrng-008.xml
tests/optional/validrng-008.xml

[role="fail"]
=== FAIL validrng-009.xml
tests/optional/validrng-009.xml

[role="fail"]
=== FAIL validsch-001.xml
tests/optional/validsch-001.xml

[role="pass"]
=== PASS validsch-002.xml
tests/optional/validsch-002.xml

[role="fail"]
=== FAIL validsch-003.xml
tests/optional/validsch-003.xml

[role="fail"]
=== FAIL validsch-004.xml
tests/optional/validsch-004.xml

[role="fail"]
=== FAIL validsch-005.xml
tests/optional/validsch-005.xml

[role="fail"]
=== FAIL validxsd-001.xml
tests/optional/validxsd-001.xml

[role="fail"]
=== FAIL validxsd-002.xml
tests/optional/validxsd-002.xml

[role="fail"]
=== FAIL validxsd-003.xml
tests/optional/validxsd-003.xml

[role="fail"]
=== FAIL validxsd-004.xml
tests/optional/validxsd-004.xml

[role="fail"]
=== FAIL validxsd-005.xml
tests/optional/validxsd-005.xml

[role="fail"]
=== FAIL validxsd-006.xml
tests/optional/validxsd-006.xml

[role="pass"]
=== PASS validxsd-007.xml
tests/optional/validxsd-007.xml

[role="fail"]
=== FAIL validxsd-008.xml
tests/optional/validxsd-008.xml

[role="fail"]
=== FAIL validxsd-009.xml
tests/optional/validxsd-009.xml

[role="fail"]
=== FAIL validxsd-010.xml
tests/optional/validxsd-010.xml

[role="fail"]
=== FAIL validxsd-011.xml
tests/optional/validxsd-011.xml

[role="fail"]
=== FAIL validxsd-012.xml
tests/optional/validxsd-012.xml

[role="fail"]
=== FAIL www-form-urldecode-001.xml
tests/optional/www-form-urldecode-001.xml

[role="fail"]
=== FAIL www-form-urlencode-001.xml
tests/optional/www-form-urlencode-001.xml

[role="pass"]
=== PASS xquery-001.xml
tests/optional/xquery-001.xml

[role="pass"]
=== PASS xquery-002.xml
tests/optional/xquery-002.xml

[role="fail"]
=== FAIL xquery-003.xml
tests/optional/xquery-003.xml

[role="fail"]
=== FAIL xquery-004.xml
tests/optional/xquery-004.xml

[role="fail"]
=== FAIL xquery-005.xml
tests/optional/xquery-005.xml

[role="fail"]
=== FAIL xquery-006.xml
tests/optional/xquery-006.xml

[role="fail"]
=== FAIL xsl-formatter-001.xml
tests/optional/xsl-formatter-001.xml

[role="pass"]
=== PASS xslt2-001.xml
tests/optional/xslt2-001.xml

[role="fail"]
=== FAIL xslt2-002.xml
tests/optional/xslt2-002.xml

[role="pass"]
=== PASS xslt2-003.xml
tests/optional/xslt2-003.xml

