
= XProc Test Results for XML Calabash

Passed 764 of 768 tests (99.48%) on 16 Aug 2014 at 07:49p.

:toc: right

[cols="<h,<,<h,<"]
|==================================================
4+<h|Processor information
|Name|XML Calabash|Language|en-US
|Vendor|Norman Walsh|XProc version|1.0
|Vendor URI|http://xmlcalabash.com/|XPath version|2.0
|Version|1.0.18 (for Saxon 9.5.1.5/EE)|PSVI Supported|true
|==================================================

== Required tests (Revision 633)

Passed 600 of 602 tests (99.67%).

[role="pass"]
=== PASS Test p:add-attribute #001
http://tests.xproc.org/tests/required/add-attribute-001.xml


[role="pass"]
=== PASS Test p:add-attribute #002
http://tests.xproc.org/tests/required/add-attribute-002.xml


[role="pass"]
=== PASS Test add attribute 003
http://tests.xproc.org/tests/required/add-attribute-003.xml


[role="pass"]
=== PASS Test p:add-attribute #004
http://tests.xproc.org/tests/required/add-attribute-004.xml


[role="pass"]
=== PASS Test p:add-attribute #005
http://tests.xproc.org/tests/required/add-attribute-005.xml


[role="pass"]
=== PASS Test p:add-attribute #006
http://tests.xproc.org/tests/required/add-attribute-006.xml


[role="pass"]
=== PASS Test p:add-attribute #007
http://tests.xproc.org/tests/required/add-attribute-007.xml


[role="pass"]
=== PASS Test add-xml-base-001
http://tests.xproc.org/tests/required/add-xml-base-001.xml


[role="pass"]
=== PASS Test add-xml-base-002
http://tests.xproc.org/tests/required/add-xml-base-002.xml


[role="pass"]
=== PASS Test add-xml-base-003
http://tests.xproc.org/tests/required/add-xml-base-003.xml


[role="pass"]
=== PASS Test add-xml-base-004
http://tests.xproc.org/tests/required/add-xml-base-004.xml


[role="pass"]
=== PASS Test add-xml-base-005
http://tests.xproc.org/tests/required/add-xml-base-005.xml


[role="pass"]
=== PASS Test add-xml-base-006
http://tests.xproc.org/tests/required/add-xml-base-006.xml


[role="pass"]
=== PASS Test base-uri #001
http://tests.xproc.org/tests/required/base-uri-001.xml


[role="pass"]
=== PASS Test base-uri #002
http://tests.xproc.org/tests/required/base-uri-002.xml


[role="pass"]
=== PASS Test base-uri #003
http://tests.xproc.org/tests/required/base-uri-003.xml


[role="pass"]
=== PASS Test choose #001
http://tests.xproc.org/tests/required/choose-001.xml


[role="pass"]
=== PASS Test choose #002
http://tests.xproc.org/tests/required/choose-002.xml


[role="pass"]
=== PASS Test choose #003
http://tests.xproc.org/tests/required/choose-003.xml


[role="pass"]
=== PASS Test choose #004
http://tests.xproc.org/tests/required/choose-004.xml


[role="pass"]
=== PASS Test choose #005
http://tests.xproc.org/tests/required/choose-005.xml


[role="pass"]
=== PASS Test choose #006
http://tests.xproc.org/tests/required/choose-006.xml


[role="pass"]
=== PASS Test choose #007
http://tests.xproc.org/tests/required/choose-007.xml


[role="pass"]
=== PASS Test choose #008
http://tests.xproc.org/tests/required/choose-008.xml


[role="pass"]
=== PASS Test compare
http://tests.xproc.org/tests/required/compare-001.xml


[role="pass"]
=== PASS Test compare
http://tests.xproc.org/tests/required/compare-002.xml


[role="pass"]
=== PASS Test compare
http://tests.xproc.org/tests/required/compare-003.xml


==== Error message


* XC0019

[role="pass"]
=== PASS Test compare
http://tests.xproc.org/tests/required/compare-004.xml


[role="pass"]
=== PASS Test compare
http://tests.xproc.org/tests/required/compare-005.xml


[role="pass"]
=== PASS Test of the p:count Step
http://tests.xproc.org/tests/required/count-001.xml


[role="pass"]
=== PASS Test of the p:count Step #002
http://tests.xproc.org/tests/required/count-002.xml


[role="pass"]
=== PASS Test count 003
http://tests.xproc.org/tests/required/count-003.xml


[role="pass"]
=== PASS Test count 004
http://tests.xproc.org/tests/required/count-004.xml


[role="pass"]
=== PASS Test p:data #001
http://tests.xproc.org/tests/required/data-001.xml


[role="fail"]
=== FAIL Test p:data #002
http://tests.xproc.org/tests/required/data-002.xml

[frame="topbot",cols="d<,d<"]
|====================
|Expected result:|Actual result:
l|<c:data xmlns:c="http://www.w3.org/ns/xproc-step"
        xmlns:t="http://xproc.org/ns/testsuite"
        xmlns:p="http://www.w3.org/ns/xproc"
        xmlns:err="http://www.w3.org/ns/xproc-error"
        content-type="text/plain; charset=&#34;utf-8&#34;">Toman a lesní panna
František Ladislav Čelakovský

Večer před svatým Janem
mluví sestra s Tomanem:
"Kam pojedeš, bratře milý,
v této pozdní na noc chvíli
na koníčku sedlaném,
čistě vyšperkovaném?"

"Do Podhájí k myslivci
musím ke své děvčici;
znenadání nemám stání,
zas mě čekej o svítání.
Dej, sestřičko, dej novou
košiličku kmentovou,
kamizolku růžovou."

Jiskra padla pod koníčkem,
sestra volá za bratříčkem:
"Slyš, Tománku, radou mou,
nedávej se doubravou:
objeď dolem k Svaté hoře,
ať nemám po tobě hoře,
dej se raděj v zápoli,
ať mě srdce nebolí."

Nejel Toman doubravou,
dal se cestičkou pravou;
a v Podhájí u myslivce
nový domek jedna svíce,
hostí mnoho pospolu,
jizba plna hovoru.

Smutkem Toman obklopen
patří s koně do oken
děvče láskou jen rozplývá,
na ženicha se usmívá;
otec jedná námluvy,
matka hledí obsluhy.
Jedli, pili, rozprávěli,
dobrou vůli spolu měli,
žádný na to nic nedbal,
kůň že venku zařehtal,
a mládenec zavzdychal.

Panna jenom snoubená
najednou se zarděla;
svědomí ji přece tlačí,
šeptá cosi sestře mladší.
Sestřička od večeře
vyšla rychle za dvéře:
"Na věky se, Tomane,
milá s tebou rozstane,
jinému se dostane.
Najezdil jsi se k nám dosti,
dnes tu máme bližší hosti,
hledej sobě jinde štěstí."

Toman koněm zatočil,
v šíré pole poskočil,
zaťal zuby, smračil čelo,
kolem všecko neveselo.
Půlnoc byla, měsíc zašel,
sotva jezdec cestu našel;
prudce hned, pak loudavě
ubíral se k doubravě.
"Všecky krásné hvězdičky
ze tmy jsou se prosypaly,
proč vy, moje mladé dni,
ve tmách jste se zasypaly!"

Jede, jede doubravou,
les šumí mu nad hlavou,
větřík chladný z noci fouká,
nad ouvalem sova houká;
koník blýská očima,
koník stříhá ušima.

Cupy dupy z houštiny
letí jelen v mejtiny,
na jelínku podkasaná
sedí sobě Lesní panna;
šaty půl má zelené,
půl kadeřmi černěné,
a ze svatojanských broučků
svítí pásek na kloboučku.

Třikrát kolem jak střela
v běhu koně objela,
pak Tomanovi po boku
vyrovnává v plavném skoku:
"Švarný hochu, nezoufej,
bujným větrům žalost dej,
jedna-li tě opustila,
nahradí to stokrát jiná.
Švarný hochu, nezoufej,
bujným větrům žalost dej!"
To když sladce zpívala,
v oči se mu dívala
Lesní panna na jelenu,
Toman cítí v srdci změnu.

Jedou, jedou pospolu
měkkým mechem do dolu,
panna Tomanu po boku
vyrovnává v plavném skoku:
"Švarný hochu, skloň se, skloň,
jenom dále se mnou hoň;
líbí-li se ti mé líce,
dám radostí na tisíce.
Švarný hochu, skloň se, skloň,
jenom dále se mnou hoň!"
To kdy panna zpívala,
za ruku ho ujala;
Tomanovi rozkoš proudem
prolila se každým oudem.

Jedou, jedou dál a dál
podlé řeky, podlé skal,
panna Tomanu po boku
vyrovnává v plavném skoku:
"Švarný hochu, můj jsi, můj!
K mému bytu se mnou pluj;
světla denního v mém domě
věčně nezachce se tobě.
Švarný hochu, můj jsi, můj -
k mému bytu se mnou pluj!"

To kdy panna zpívala,
v ústa jezdce líbala,
v náručí ho objala.
Tomanovi srdce plesá,
uzdu pouští, s koně klesá
pod skalami prostřed lesa.

Slunce vyšlo nad horu,
skáče koník do dvoru,
smutně hrabe podkovou,
řehce zprávu nedobrou.
Sestra k oknu přiskočila,
a rukama zalomila
"Bratře můj, bratříčku můj,
kde skonal jsi život svůj!"</c:data>
l|<c:data xmlns:c="http://www.w3.org/ns/xproc-step"
        content-type="text/plain; charset=utf-8">Toman a lesní panna
František Ladislav Čelakovský

Večer před svatým Janem
mluví sestra s Tomanem:
"Kam pojedeš, bratře milý,
v této pozdní na noc chvíli
na koníčku sedlaném,
čistě vyšperkovaném?"

"Do Podhájí k myslivci
musím ke své děvčici;
znenadání nemám stání,
zas mě čekej o svítání.
Dej, sestřičko, dej novou
košiličku kmentovou,
kamizolku růžovou."

Jiskra padla pod koníčkem,
sestra volá za bratříčkem:
"Slyš, Tománku, radou mou,
nedávej se doubravou:
objeď dolem k Svaté hoře,
ať nemám po tobě hoře,
dej se raděj v zápoli,
ať mě srdce nebolí."

Nejel Toman doubravou,
dal se cestičkou pravou;
a v Podhájí u myslivce
nový domek jedna svíce,
hostí mnoho pospolu,
jizba plna hovoru.

Smutkem Toman obklopen
patří s koně do oken
děvče láskou jen rozplývá,
na ženicha se usmívá;
otec jedná námluvy,
matka hledí obsluhy.
Jedli, pili, rozprávěli,
dobrou vůli spolu měli,
žádný na to nic nedbal,
kůň že venku zařehtal,
a mládenec zavzdychal.

Panna jenom snoubená
najednou se zarděla;
svědomí ji přece tlačí,
šeptá cosi sestře mladší.
Sestřička od večeře
vyšla rychle za dvéře:
"Na věky se, Tomane,
milá s tebou rozstane,
jinému se dostane.
Najezdil jsi se k nám dosti,
dnes tu máme bližší hosti,
hledej sobě jinde štěstí."

Toman koněm zatočil,
v šíré pole poskočil,
zaťal zuby, smračil čelo,
kolem všecko neveselo.
Půlnoc byla, měsíc zašel,
sotva jezdec cestu našel;
prudce hned, pak loudavě
ubíral se k doubravě.
"Všecky krásné hvězdičky
ze tmy jsou se prosypaly,
proč vy, moje mladé dni,
ve tmách jste se zasypaly!"

Jede, jede doubravou,
les šumí mu nad hlavou,
větřík chladný z noci fouká,
nad ouvalem sova houká;
koník blýská očima,
koník stříhá ušima.

Cupy dupy z houštiny
letí jelen v mejtiny,
na jelínku podkasaná
sedí sobě Lesní panna;
šaty půl má zelené,
půl kadeřmi černěné,
a ze svatojanských broučků
svítí pásek na kloboučku.

Třikrát kolem jak střela
v běhu koně objela,
pak Tomanovi po boku
vyrovnává v plavném skoku:
"Švarný hochu, nezoufej,
bujným větrům žalost dej,
jedna-li tě opustila,
nahradí to stokrát jiná.
Švarný hochu, nezoufej,
bujným větrům žalost dej!"
To když sladce zpívala,
v oči se mu dívala
Lesní panna na jelenu,
Toman cítí v srdci změnu.

Jedou, jedou pospolu
měkkým mechem do dolu,
panna Tomanu po boku
vyrovnává v plavném skoku:
"Švarný hochu, skloň se, skloň,
jenom dále se mnou hoň;
líbí-li se ti mé líce,
dám radostí na tisíce.
Švarný hochu, skloň se, skloň,
jenom dále se mnou hoň!"
To kdy panna zpívala,
za ruku ho ujala;
Tomanovi rozkoš proudem
prolila se každým oudem.

Jedou, jedou dál a dál
podlé řeky, podlé skal,
panna Tomanu po boku
vyrovnává v plavném skoku:
"Švarný hochu, můj jsi, můj!
K mému bytu se mnou pluj;
světla denního v mém domě
věčně nezachce se tobě.
Švarný hochu, můj jsi, můj -
k mému bytu se mnou pluj!"

To kdy panna zpívala,
v ústa jezdce líbala,
v náručí ho objala.
Tomanovi srdce plesá,
uzdu pouští, s koně klesá
pod skalami prostřed lesa.

Slunce vyšlo nad horu,
skáče koník do dvoru,
smutně hrabe podkovou,
řehce zprávu nedobrou.
Sestra k oknu přiskočila,
a rukama zalomila
"Bratře můj, bratříčku můj,
kde skonal jsi život svůj!"</c:data>
|====================

[role="pass"]
=== PASS Test p:data #003
http://tests.xproc.org/tests/required/data-003.xml


[role="pass"]
=== PASS Test p:data #004
http://tests.xproc.org/tests/required/data-004.xml


[role="pass"]
=== PASS Test p:data #005
http://tests.xproc.org/tests/required/data-005.xml


[role="fail"]
=== FAIL Test p:data #006
http://tests.xproc.org/tests/required/data-006.xml

[frame="topbot",cols="d<,d<"]
|====================
|Expected result:|Actual result:
l|<c:data xmlns:c="http://www.w3.org/ns/xproc-step"
        xmlns:t="http://xproc.org/ns/testsuite"
        xmlns:p="http://www.w3.org/ns/xproc"
        xmlns:err="http://www.w3.org/ns/xproc-error"
        content-type="text/plain; charset=&#34;utf-8&#34;">Toman a lesní panna
František Ladislav Čelakovský

Večer před svatým Janem
mluví sestra s Tomanem:
"Kam pojedeš, bratře milý,
v této pozdní na noc chvíli
na koníčku sedlaném,
čistě vyšperkovaném?"

"Do Podhájí k myslivci
musím ke své děvčici;
znenadání nemám stání,
zas mě čekej o svítání.
Dej, sestřičko, dej novou
košiličku kmentovou,
kamizolku růžovou."

Jiskra padla pod koníčkem,
sestra volá za bratříčkem:
"Slyš, Tománku, radou mou,
nedávej se doubravou:
objeď dolem k Svaté hoře,
ať nemám po tobě hoře,
dej se raděj v zápoli,
ať mě srdce nebolí."

Nejel Toman doubravou,
dal se cestičkou pravou;
a v Podhájí u myslivce
nový domek jedna svíce,
hostí mnoho pospolu,
jizba plna hovoru.

Smutkem Toman obklopen
patří s koně do oken
děvče láskou jen rozplývá,
na ženicha se usmívá;
otec jedná námluvy,
matka hledí obsluhy.
Jedli, pili, rozprávěli,
dobrou vůli spolu měli,
žádný na to nic nedbal,
kůň že venku zařehtal,
a mládenec zavzdychal.

Panna jenom snoubená
najednou se zarděla;
svědomí ji přece tlačí,
šeptá cosi sestře mladší.
Sestřička od večeře
vyšla rychle za dvéře:
"Na věky se, Tomane,
milá s tebou rozstane,
jinému se dostane.
Najezdil jsi se k nám dosti,
dnes tu máme bližší hosti,
hledej sobě jinde štěstí."

Toman koněm zatočil,
v šíré pole poskočil,
zaťal zuby, smračil čelo,
kolem všecko neveselo.
Půlnoc byla, měsíc zašel,
sotva jezdec cestu našel;
prudce hned, pak loudavě
ubíral se k doubravě.
"Všecky krásné hvězdičky
ze tmy jsou se prosypaly,
proč vy, moje mladé dni,
ve tmách jste se zasypaly!"

Jede, jede doubravou,
les šumí mu nad hlavou,
větřík chladný z noci fouká,
nad ouvalem sova houká;
koník blýská očima,
koník stříhá ušima.

Cupy dupy z houštiny
letí jelen v mejtiny,
na jelínku podkasaná
sedí sobě Lesní panna;
šaty půl má zelené,
půl kadeřmi černěné,
a ze svatojanských broučků
svítí pásek na kloboučku.

Třikrát kolem jak střela
v běhu koně objela,
pak Tomanovi po boku
vyrovnává v plavném skoku:
"Švarný hochu, nezoufej,
bujným větrům žalost dej,
jedna-li tě opustila,
nahradí to stokrát jiná.
Švarný hochu, nezoufej,
bujným větrům žalost dej!"
To když sladce zpívala,
v oči se mu dívala
Lesní panna na jelenu,
Toman cítí v srdci změnu.

Jedou, jedou pospolu
měkkým mechem do dolu,
panna Tomanu po boku
vyrovnává v plavném skoku:
"Švarný hochu, skloň se, skloň,
jenom dále se mnou hoň;
líbí-li se ti mé líce,
dám radostí na tisíce.
Švarný hochu, skloň se, skloň,
jenom dále se mnou hoň!"
To kdy panna zpívala,
za ruku ho ujala;
Tomanovi rozkoš proudem
prolila se každým oudem.

Jedou, jedou dál a dál
podlé řeky, podlé skal,
panna Tomanu po boku
vyrovnává v plavném skoku:
"Švarný hochu, můj jsi, můj!
K mému bytu se mnou pluj;
světla denního v mém domě
věčně nezachce se tobě.
Švarný hochu, můj jsi, můj -
k mému bytu se mnou pluj!"

To kdy panna zpívala,
v ústa jezdce líbala,
v náručí ho objala.
Tomanovi srdce plesá,
uzdu pouští, s koně klesá
pod skalami prostřed lesa.

Slunce vyšlo nad horu,
skáče koník do dvoru,
smutně hrabe podkovou,
řehce zprávu nedobrou.
Sestra k oknu přiskočila,
a rukama zalomila
"Bratře můj, bratříčku můj,
kde skonal jsi život svůj!"</c:data>
l|<c:data xmlns:c="http://www.w3.org/ns/xproc-step"
        content-type="text/plain; charset=utf-8">Toman a lesní panna
František Ladislav Čelakovský

Večer před svatým Janem
mluví sestra s Tomanem:
"Kam pojedeš, bratře milý,
v této pozdní na noc chvíli
na koníčku sedlaném,
čistě vyšperkovaném?"

"Do Podhájí k myslivci
musím ke své děvčici;
znenadání nemám stání,
zas mě čekej o svítání.
Dej, sestřičko, dej novou
košiličku kmentovou,
kamizolku růžovou."

Jiskra padla pod koníčkem,
sestra volá za bratříčkem:
"Slyš, Tománku, radou mou,
nedávej se doubravou:
objeď dolem k Svaté hoře,
ať nemám po tobě hoře,
dej se raděj v zápoli,
ať mě srdce nebolí."

Nejel Toman doubravou,
dal se cestičkou pravou;
a v Podhájí u myslivce
nový domek jedna svíce,
hostí mnoho pospolu,
jizba plna hovoru.

Smutkem Toman obklopen
patří s koně do oken
děvče láskou jen rozplývá,
na ženicha se usmívá;
otec jedná námluvy,
matka hledí obsluhy.
Jedli, pili, rozprávěli,
dobrou vůli spolu měli,
žádný na to nic nedbal,
kůň že venku zařehtal,
a mládenec zavzdychal.

Panna jenom snoubená
najednou se zarděla;
svědomí ji přece tlačí,
šeptá cosi sestře mladší.
Sestřička od večeře
vyšla rychle za dvéře:
"Na věky se, Tomane,
milá s tebou rozstane,
jinému se dostane.
Najezdil jsi se k nám dosti,
dnes tu máme bližší hosti,
hledej sobě jinde štěstí."

Toman koněm zatočil,
v šíré pole poskočil,
zaťal zuby, smračil čelo,
kolem všecko neveselo.
Půlnoc byla, měsíc zašel,
sotva jezdec cestu našel;
prudce hned, pak loudavě
ubíral se k doubravě.
"Všecky krásné hvězdičky
ze tmy jsou se prosypaly,
proč vy, moje mladé dni,
ve tmách jste se zasypaly!"

Jede, jede doubravou,
les šumí mu nad hlavou,
větřík chladný z noci fouká,
nad ouvalem sova houká;
koník blýská očima,
koník stříhá ušima.

Cupy dupy z houštiny
letí jelen v mejtiny,
na jelínku podkasaná
sedí sobě Lesní panna;
šaty půl má zelené,
půl kadeřmi černěné,
a ze svatojanských broučků
svítí pásek na kloboučku.

Třikrát kolem jak střela
v běhu koně objela,
pak Tomanovi po boku
vyrovnává v plavném skoku:
"Švarný hochu, nezoufej,
bujným větrům žalost dej,
jedna-li tě opustila,
nahradí to stokrát jiná.
Švarný hochu, nezoufej,
bujným větrům žalost dej!"
To když sladce zpívala,
v oči se mu dívala
Lesní panna na jelenu,
Toman cítí v srdci změnu.

Jedou, jedou pospolu
měkkým mechem do dolu,
panna Tomanu po boku
vyrovnává v plavném skoku:
"Švarný hochu, skloň se, skloň,
jenom dále se mnou hoň;
líbí-li se ti mé líce,
dám radostí na tisíce.
Švarný hochu, skloň se, skloň,
jenom dále se mnou hoň!"
To kdy panna zpívala,
za ruku ho ujala;
Tomanovi rozkoš proudem
prolila se každým oudem.

Jedou, jedou dál a dál
podlé řeky, podlé skal,
panna Tomanu po boku
vyrovnává v plavném skoku:
"Švarný hochu, můj jsi, můj!
K mému bytu se mnou pluj;
světla denního v mém domě
věčně nezachce se tobě.
Švarný hochu, můj jsi, můj -
k mému bytu se mnou pluj!"

To kdy panna zpívala,
v ústa jezdce líbala,
v náručí ho objala.
Tomanovi srdce plesá,
uzdu pouští, s koně klesá
pod skalami prostřed lesa.

Slunce vyšlo nad horu,
skáče koník do dvoru,
smutně hrabe podkovou,
řehce zprávu nedobrou.
Sestra k oknu přiskočila,
a rukama zalomila
"Bratře můj, bratříčku můj,
kde skonal jsi život svůj!"</c:data>
|====================

[role="pass"]
=== PASS Test p:data #007
http://tests.xproc.org/tests/required/data-007.xml


[role="pass"]
=== PASS Test p:data #008
http://tests.xproc.org/tests/required/data-008.xml


[role="pass"]
=== PASS Test p:declare-step-001
http://tests.xproc.org/tests/required/declare-step-001.xml


[role="pass"]
=== PASS Test p:declare-step-002
http://tests.xproc.org/tests/required/declare-step-002.xml


[role="pass"]
=== PASS Test p:declare-step-003
http://tests.xproc.org/tests/required/declare-step-003.xml


[role="pass"]
=== PASS Test p:declare-step-004
http://tests.xproc.org/tests/required/declare-step-004.xml


[role="pass"]
=== PASS Test p:declare-step-005
http://tests.xproc.org/tests/required/declare-step-005.xml


[role="pass"]
=== PASS Test p:declare-step-006
http://tests.xproc.org/tests/required/declare-step-006.xml


[role="pass"]
=== PASS Test p:declare-step-007
http://tests.xproc.org/tests/required/declare-step-007.xml


[role="pass"]
=== PASS Test p:declare-step-008
http://tests.xproc.org/tests/required/declare-step-008.xml


[role="pass"]
=== PASS Test p:declare-step-009
http://tests.xproc.org/tests/required/declare-step-009.xml


[role="pass"]
=== PASS Test p:declare-step-010
http://tests.xproc.org/tests/required/declare-step-010.xml


[role="pass"]
=== PASS Test p:declare-step-011
http://tests.xproc.org/tests/required/declare-step-011.xml


[role="pass"]
=== PASS Test delete-001
http://tests.xproc.org/tests/required/delete-001.xml


[role="pass"]
=== PASS Test delete-002
http://tests.xproc.org/tests/required/delete-002.xml


[role="pass"]
=== PASS Test delete-003
http://tests.xproc.org/tests/required/delete-003.xml


[role="pass"]
=== PASS Test delete-004
http://tests.xproc.org/tests/required/delete-004.xml


[role="pass"]
=== PASS Test delete-005
http://tests.xproc.org/tests/required/delete-005.xml


[role="pass"]
=== PASS Test directory-list-001
http://tests.xproc.org/tests/required/directory-list-001.xml


[role="pass"]
=== PASS Test directory-list-002
http://tests.xproc.org/tests/required/directory-list-002.xml


[role="pass"]
=== PASS Test p:document-001
http://tests.xproc.org/tests/required/document-001.xml


[role="pass"]
=== PASS Test ebv-001
http://tests.xproc.org/tests/required/ebv-001.xml


[role="pass"]
=== PASS Test ebv-002
http://tests.xproc.org/tests/required/ebv-002.xml


[role="pass"]
=== PASS Test err:XC0002 #001
http://tests.xproc.org/tests/required/err-c0002-001.xml


==== Error message


* XC0002

[role="pass"]
=== PASS Test for err:XC0003 #001
http://tests.xproc.org/tests/required/err-c0003-001.xml


==== Error message


* Unsupported auth-method: null

[role="pass"]
=== PASS Test for err:XC0003 #002
http://tests.xproc.org/tests/required/err-c0003-002.xml


==== Error message


* Unsupported auth-method: unsupported

[role="pass"]
=== PASS Test err:XC0004 #001
http://tests.xproc.org/tests/required/err-c0004-001.xml


==== Error message


* XC0004

[role="pass"]
=== PASS Test err:XC0005 #001
http://tests.xproc.org/tests/required/err-c0005-001.xml


==== Error message


* XC0005

[role="pass"]
=== PASS Test err:XC0005 #002
http://tests.xproc.org/tests/required/err-c0005-002.xml


==== Error message


* XC0005

[role="pass"]
=== PASS Test for err:XC0006 #001
http://tests.xproc.org/tests/required/err-c0006-001.xml


==== Error message


* XC0006

[role="pass"]
=== PASS Test for err:XC0010 #001
http://tests.xproc.org/tests/required/err-c0010-001.xml


==== Error message


* XC0010

[role="pass"]
=== PASS Test for err:XC0010 #002
http://tests.xproc.org/tests/required/err-c0010-002.xml


==== Error message


* XProc error err:XC0010

[role="pass"]
=== PASS Test err:XC0012 (p:directory-list on an inaccessible directory).
http://tests.xproc.org/tests/required/err-c0012-001.xml


==== Error message


* XC0012

[role="pass"]
=== PASS Test for err:XC0013 #001
http://tests.xproc.org/tests/required/err-c0013-001.xml


==== Error message


* XC0013

[role="pass"]
=== PASS Test err:XC0014 #001
http://tests.xproc.org/tests/required/err-c0014-001.xml


==== Error message


* XC0014

[role="pass"]
=== PASS Test err:XC0014 #002
http://tests.xproc.org/tests/required/err-c0014-002.xml


==== Error message


* XC0014

[role="pass"]
=== PASS Test err:XC0017 (p:directory-list with a non-directory path).
http://tests.xproc.org/tests/required/err-c0017-001.xml


==== Error message


* XC0017

[role="pass"]
=== PASS Test for err:XC0019 - 001
http://tests.xproc.org/tests/required/err-c0019-001.xml


==== Error message


* XC0019

[role="pass"]
=== PASS Test err:XC0020 #001
http://tests.xproc.org/tests/required/err-c0020-001.xml


==== Error message


* XC0020

[role="pass"]
=== PASS Test err:XC0020 #003
http://tests.xproc.org/tests/required/err-c0020-003.xml


==== Error message


* XC0020

[role="pass"]
=== PASS Test err:XC0020 #004
http://tests.xproc.org/tests/required/err-c0020-004.xml


==== Error message


* XC0020

[role="pass"]
=== PASS Test err:XC0020 #005
http://tests.xproc.org/tests/required/err-c0020-005.xml


==== Error message


* XC0020

[role="pass"]
=== PASS Test err:XC0020 #006
http://tests.xproc.org/tests/required/err-c0020-006.xml


==== Error message


* XC0020

[role="pass"]
=== PASS Test err:XC0020 #007
http://tests.xproc.org/tests/required/err-c0020-007.xml


==== Error message


* XC0020

[role="pass"]
=== PASS Test err:XC0022 #001
http://tests.xproc.org/tests/required/err-c0022-001.xml


==== Error message


* XC0022

[role="pass"]
=== PASS Test for err:XC0023 #001
http://tests.xproc.org/tests/required/err-c0023-001.xml


==== Error message


* XC0023

[role="pass"]
=== PASS Test for err:XC0023 #002
http://tests.xproc.org/tests/required/err-c0023-002.xml


==== Error message


* XC0023

[role="pass"]
=== PASS Test for err:XC0023 #003
http://tests.xproc.org/tests/required/err-c0023-003.xml


==== Error message


* XC0023

[role="pass"]
=== PASS Test for err:XC0023 #004
http://tests.xproc.org/tests/required/err-c0023-004.xml


==== Error message


* XC0023

[role="pass"]
=== PASS Test for err:XC0023 #005
http://tests.xproc.org/tests/required/err-c0023-005.xml


==== Error message


* XC0023

[role="pass"]
=== PASS Test for err:XC0023 #006
http://tests.xproc.org/tests/required/err-c0023-006.xml


==== Error message


* XC0023

[role="pass"]
=== PASS Test for err:XC0023 #007
http://tests.xproc.org/tests/required/err-c0023-007.xml


==== Error message


* XC0023

[role="pass"]
=== PASS Test for err:XC0023 #008
http://tests.xproc.org/tests/required/err-c0023-008.xml


==== Error message


* XC0023

[role="pass"]
=== PASS Test for err:XC0023 #009
http://tests.xproc.org/tests/required/err-c0023-009.xml


==== Error message


* XC0023

[role="pass"]
=== PASS Test for err:XC0025 #001
http://tests.xproc.org/tests/required/err-c0025-001.xml


==== Error message


* XC0025

[role="pass"]
=== PASS Test for err:XC0025 #002
http://tests.xproc.org/tests/required/err-c0025-002.xml


==== Error message


* XC0025

[role="pass"]
=== PASS Test for err:XC0027 - 001
http://tests.xproc.org/tests/required/err-c0027-001.xml


==== Error message


* XProc error err:XC0027

[role="pass partial"]
=== PASS Test for err:XC0027 - 002
http://tests.xproc.org/tests/required/err-c0027-002.xml

Wrong error: expected err:XC0027 but err:XC0011 was raised.

* XC0027: 
* XC0011: 

==== Error message


* Could not load ../doc/address-nonexistent-dtd.xml (http://tests.xproc.org/tests/required/err-c0027-002.xml) dtd-validate=true

[role="pass"]
=== PASS Test for err:XC0027 - 003
http://tests.xproc.org/tests/required/err-c0027-003.xml


==== Error message


* XProc error err:XC0027

[role="pass"]
=== PASS Test err:XC0028 #001
http://tests.xproc.org/tests/required/err-c0028-001.xml


==== Error message


* XC0028

[role="pass"]
=== PASS Test err:XC0029 #001
http://tests.xproc.org/tests/required/err-c0029-001.xml


==== Error message


* XInclude document includes itself:

[role="pass"]
=== PASS Test err:XC0029 #002
http://tests.xproc.org/tests/required/err-c0029-002.xml


==== Error message


* XInclude document includes itself: input-xinclude-loop-target.xml

[role="pass"]
=== PASS Test err:XC0030 #001
http://tests.xproc.org/tests/required/err-c0030-001.xml


==== Error message


* XC0030

[role="pass"]
=== PASS Test for err:XC0039 - 001
http://tests.xproc.org/tests/required/err-c0039-001.xml


==== Error message


* XC0039

[role="pass"]
=== PASS Test err:XC0040 #001
http://tests.xproc.org/tests/required/err-c0040-001.xml


==== Error message


* XC0040

[role="pass"]
=== PASS Test for err:XC0050 - 001
http://tests.xproc.org/tests/required/err-c0050-001.xml


==== Error message


* XProc error err:XC0050

[role="pass"]
=== PASS Test err:XC0051 #001
http://tests.xproc.org/tests/required/err-c0051-001.xml


==== Error message


* XC0051

[role="pass"]
=== PASS Test err:XC0052 #001
http://tests.xproc.org/tests/required/err-c0052-001.xml


==== Error message


* XC0052

[role="pass partial"]
=== PASS Test err:XC0052 #002
http://tests.xproc.org/tests/required/err-c0052-002.xml

Wrong error: expected err:XC0052 but null was raised.

* XC0052: 
* null: 

[role="pass partial"]
=== PASS Test for err:XC0056 - 001
http://tests.xproc.org/tests/required/err-c0056-001.xml

Wrong error: expected err:XC0056 but null was raised.

* XC0056: 
* null: 

[role="pass partial"]
=== PASS Test for err:XC0056 - 002
http://tests.xproc.org/tests/required/err-c0056-002.xml

Wrong error: expected err:XC0056 but null was raised.

* XC0056: 
* null: 

[role="pass"]
=== PASS Test for err:XC0058 - 001
http://tests.xproc.org/tests/required/err-c0058-001.xml


==== Error message


* XC0058

[role="pass partial"]
=== PASS Test err:XC0059 #001
http://tests.xproc.org/tests/required/err-c0059-001.xml

Wrong error: expected err:XC0059 but XD0045 was raised.

* XC0059: 
* XD0045: 

==== Error message


* XProc error err:XD0045

[role="pass"]
=== PASS Test err:XC0059 #002
http://tests.xproc.org/tests/required/err-c0059-002.xml


==== Error message


* XC0059

[role="pass partial"]
=== PASS Test err:XC0062 #001
http://tests.xproc.org/tests/required/err-c0062-001.xml

Wrong error: expected err:XC0062 but err:XD0023 was raised.

* XC0062: 
* XD0023: 

==== Error message


* Expression could not be evaluated: namespace::test

[role="pass"]
=== PASS Test err:XD0001 #001
http://tests.xproc.org/tests/required/err-d0001-001.xml


==== Error message


* Only whitespace text nodes can appear at the top level in a document

[role="pass"]
=== PASS Test err:XD0001 #002
http://tests.xproc.org/tests/required/err-d0001-002.xml


==== Error message


* Document must have exactly one top-level element

[role="pass"]
=== PASS Test err:XD0003
http://tests.xproc.org/tests/required/err-d0003-001.xml


==== Error message


* XD0003

[role="pass"]
=== PASS Test err:XD0004
http://tests.xproc.org/tests/required/err-d0004-001.xml


==== Error message


* XD0004

[role="pass"]
=== PASS Test err:XD0005
http://tests.xproc.org/tests/required/err-d0005-001.xml


==== Error message


* XD0005

[role="pass partial"]
=== PASS Test err:XD0006 #001
http://tests.xproc.org/tests/required/err-d0006-001.xml

Wrong error: expected err:XD0006 but err:XD0007 was raised.

* XD0006: 
* XD0007: 

==== Error message


* XD0007

[role="pass"]
=== PASS Test err:XD0007
http://tests.xproc.org/tests/required/err-d0007-001.xml


==== Error message


* XD0007

[role="pass"]
=== PASS Test err:XD0007 (p:viewport)
http://tests.xproc.org/tests/required/err-d0007-002.xml


==== Error message


* XD0007

[role="pass partial"]
=== PASS Test err:XD0007 #003
http://tests.xproc.org/tests/required/err-d0007-003.xml

Wrong error: expected err:XD0007 but err:XD0006 was raised.

* XD0007: 
* XD0006: 

==== Error message


* XD0006

[role="pass"]
=== PASS Test output-003
http://tests.xproc.org/tests/required/err-d0007-004.xml


==== Error message


* XD0007

[role="pass"]
=== PASS Test err:XD0008
http://tests.xproc.org/tests/required/err-d0008-001.xml


==== Error message


* More than one document in context for parameter 'value'

[role="pass"]
=== PASS Test err:XD0009
http://tests.xproc.org/tests/required/err-d0009-001.xml


==== Error message


* XD0009

[role="pass"]
=== PASS Test err:XD0009
http://tests.xproc.org/tests/required/err-d0009-002.xml


==== Error message


* XD0009

[role="pass partial"]
=== PASS Test err:XD0010
http://tests.xproc.org/tests/required/err-d0010-001.xml

Wrong error: expected err:XD0010 but err:XD0023 was raised.

* XD0010: 
* XD0023: 

==== Error message


* Expression could not be evaluated: processing-instruction()

[role="pass"]
=== PASS Test for inaccessible URIs (err:XD0011)
http://tests.xproc.org/tests/required/err-d0011-001.xml


==== Error message


* Could not read: http://i-do-not-exist.com/no/documents/here

[role="pass partial"]
=== PASS Test for err:XD0011 - 002
http://tests.xproc.org/tests/required/err-d0011-002.xml

Wrong error: expected err:XD0011 but err:XC0011 was raised.

* XD0011: 
* XC0011: 

==== Error message


* Could not load ../doc/non-existant-document.xml (http://tests.xproc.org/tests/required/err-d0011-002.xml) dtd-validate=false

[role="pass partial"]
=== PASS Test for err:XD0011 - 003
http://tests.xproc.org/tests/required/err-d0011-003.xml

Wrong error: expected err:XD0011 but err:XC0011 was raised.

* XD0011: 
* XC0011: 

==== Error message


* Could not load ../doc/non-well-formed.xml (http://tests.xproc.org/tests/required/err-d0011-003.xml) dtd-validate=false

[role="pass partial"]
=== PASS Test err:XD0012 #001
http://tests.xproc.org/tests/required/err-d0012-001.xml

Wrong error: expected err:XD0012 but err:XC0011 was raised.

* XD0012: 
* XC0011: 

==== Error message


* Could not load unsupported://foo/bar.xml (http://tests.xproc.org/tests/required/err-d0012-001.xml) dtd-validate=false

[role="pass partial"]
=== PASS Test err:XD0012 #002
http://tests.xproc.org/tests/required/err-d0012-002.xml

Wrong error: expected err:XD0012 but err:XD0011 was raised.

* XD0012: 
* XD0011: 

==== Error message


* Could not read: unsupported://foo/bar.xml

[role="pass partial"]
=== PASS Test err:XD0012 #003
http://tests.xproc.org/tests/required/err-d0012-003.xml

Wrong error: expected err:XD0012 but null was raised.

* XD0012: 
* null: 

[role="pass"]
=== PASS Test err:XD0013 #001
http://tests.xproc.org/tests/required/err-d0013-001.xml


==== Error message


* XD0013

[role="pass"]
=== PASS Test err:XD0013 #002
http://tests.xproc.org/tests/required/err-d0013-002.xml


==== Error message


* XD0013

[role="pass"]
=== PASS Test for err:XD0014 #001
http://tests.xproc.org/tests/required/err-d0014-001.xml


==== Error message


* XD0014

[role="pass"]
=== PASS Test for err:XD0014 #002
http://tests.xproc.org/tests/required/err-d0014-002.xml


==== Error message


* Attribute not allowed

[role="pass partial"]
=== PASS Test for err:XD0015 #001
http://tests.xproc.org/tests/required/err-d0015-001.xml

Wrong error: expected err:XD0015 but null was raised.

* XD0015: 
* null: 

[role="pass"]
=== PASS Test for err:XD0016 #001
http://tests.xproc.org/tests/required/err-d0016-001.xml


==== Error message


* XD0016

[role="pass"]
=== PASS Test for err:XD0016 #002
http://tests.xproc.org/tests/required/err-d0016-002.xml


==== Error message


* XD0016

[role="pass"]
=== PASS Test for err:XD0018 #001
http://tests.xproc.org/tests/required/err-d0018-001.xml


==== Error message


* Element not allowed: foo

[role="pass partial"]
=== PASS Test err:XD0019
http://tests.xproc.org/tests/required/err-d0019-001.xml

Wrong error: expected err:XD0019 but XD0045 was raised.

* XD0019: 
* XD0045: 

==== Error message


* XProc error err:XD0045

[role="pass partial"]
=== PASS Test for err:XD0019 - 002
http://tests.xproc.org/tests/required/err-d0019-002.xml

Wrong error: expected err:XD0019 but XD0045 was raised.

* XD0019: 
* XD0045: 

==== Error message


* XProc error err:XD0045

[role="pass partial"]
=== PASS Test err:XD0020 #001
http://tests.xproc.org/tests/required/err-d0020-001.xml

Wrong error: expected err:XD0020 but err:XC0001 was raised.

* XD0020: 
* XC0001: 

==== Error message


* Only the xml, xhtml, html, and text serialization methods are supported.

[role="pass partial"]
=== PASS Test err:XD0020 #002
http://tests.xproc.org/tests/required/err-d0020-002.xml

Wrong error: expected err:XD0020 but null was raised.

* XD0020: 
* null: 

[role="pass partial"]
=== PASS Test err:XD0021 #001
http://tests.xproc.org/tests/required/err-d0021-001.xml

Wrong error: expected err:XD0021 but err:XD0011 was raised.

* XD0021: 
* XD0011: 

==== Error message


* Could not read: http://tests.xproc.org/docs/basic-auth/

[role="pass partial"]
=== PASS Test for err:XD0021 - 002
http://tests.xproc.org/tests/required/err-d0021-002.xml

Wrong error: expected err:XD0021 but err:XC0011 was raised.

* XD0021: 
* XC0011: 

==== Error message


* Could not load file:///home/www/tests.xproc.org/tests/required/../doc/chmod0.xml (http://tests.xproc.org/tests/required/err-d0021-002.xml) dtd-validate=false

[role="pass partial"]
=== PASS Test for err:XD0022 #001
http://tests.xproc.org/tests/required/err-d0022-001.xml

Wrong error: expected err:XD0022 but null was raised.

* XD0022: 
* null: 

[role="pass"]
=== PASS Test err:XD0023 - #001
http://tests.xproc.org/tests/required/err-d0023-001.xml


==== Error message


* Invalid XPath expression: 'foo^bar'.

[role="pass"]
=== PASS Test err:XD0023 - #002
http://tests.xproc.org/tests/required/err-d0023-002.xml


==== Error message


* Invalid XPath expression: '$foo'.

[role="pass"]
=== PASS Test err:XD0023 - #003
http://tests.xproc.org/tests/required/err-d0023-003.xml


==== Error message


* Invalid XPath expression: 'i-do-not-exist()'.

[role="pass"]
=== PASS Test err:XD0023 - #004
http://tests.xproc.org/tests/required/err-d0023-004.xml


==== Error message


* XD0023

[role="pass"]
=== PASS Test err:XD0023 - #005
http://tests.xproc.org/tests/required/err-d0023-005.xml


==== Error message


* Invalid XPath expression: '$optional-no-default'.

[role="pass"]
=== PASS Test err:XD0023 - #006
http://tests.xproc.org/tests/required/err-d0023-006.xml


==== Error message


* Undeclared variable in XPath expression: $opt2

[role="pass"]
=== PASS Test err:XD0023 - #007
http://tests.xproc.org/tests/required/err-d0023-007.xml


==== Error message


* Undeclared variable in XPath expression: $var2

[role="pass"]
=== PASS Test err:XD0023 - #008
http://tests.xproc.org/tests/required/err-d0023-008.xml


==== Error message


* Prefix foo has not been declared

[role="pass"]
=== PASS Test err:XD0023 - #009
http://tests.xproc.org/tests/required/err-d0023-009.xml


==== Error message


* Expression could not be evaluated: pfx:para

[role="pass partial"]
=== PASS Test for err:XD0025 #001
http://tests.xproc.org/tests/required/err-d0025-001.xml

Wrong error: expected err:XD0025 but null was raised.

* XD0025: 
* null: 

[role="pass"]
=== PASS Test err-d0026-001
http://tests.xproc.org/tests/required/err-d0026-001.xml


==== Error message


* Expression refers to context when none is available: count(//para)

[role="pass"]
=== PASS Test err:XD0026 #002
http://tests.xproc.org/tests/required/err-d0026-002.xml


==== Error message


* Expression refers to context when none is available: /foo

[role="pass"]
=== PASS Test err:XD0026 #003
http://tests.xproc.org/tests/required/err-d0026-003.xml


==== Error message


* Expression refers to context when none is available: /foo

[role="pass"]
=== PASS Test err:XD0026 #004
http://tests.xproc.org/tests/required/err-d0026-004.xml


==== Error message


* Expression refers to context when none is available: /foo

[role="pass"]
=== PASS Test err:XD0026 #005
http://tests.xproc.org/tests/required/err-d0026-005.xml


==== Error message


* Expression refers to context when none is available: boolean(/foo)

[role="pass"]
=== PASS Test for err:XD0027 #001
http://tests.xproc.org/tests/required/err-d0027-001.xml


==== Error message


* XPath version must be 1.0 or 2.0.

[role="pass partial"]
=== PASS Test err:XC0028 #001
http://tests.xproc.org/tests/required/err-d0028-001.xml

Wrong error: expected err:XD0028 but err:XS0025 was raised.

* XD0028: 
* XS0025: 

==== Error message


* Type must be in a namespace.

[role="pass partial"]
=== PASS Test err:XC0028 #002
http://tests.xproc.org/tests/required/err-d0028-002.xml

Wrong error: expected err:XD0028 but null was raised.

* XD0028: 
* null: 

[role="pass partial"]
=== PASS Test err:XC0028 #003
http://tests.xproc.org/tests/required/err-d0028-003.xml

Wrong error: expected err:XD0028 but null was raised.

* XD0028: 
* null: 

[role="pass partial"]
=== PASS Test err:XC0028 #004
http://tests.xproc.org/tests/required/err-d0028-004.xml

Wrong error: expected err:XD0028 but null was raised.

* XD0028: 
* null: 

[role="pass"]
=== PASS Test for err:XD0029 #001
http://tests.xproc.org/tests/required/err-d0029-001.xml


==== Error message


* XProc error err:XD0029

[role="pass"]
=== PASS Test for err:XD0029 #002
http://tests.xproc.org/tests/required/err-d0029-002.xml


==== Error message


* XProc error err:XD0029

[role="pass partial"]
=== PASS Test err:XD0030 - 001
http://tests.xproc.org/tests/required/err-d0030-001.xml

Wrong error: expected err:XD0030 but null was raised.

* XD0030: 
* null: 

[role="pass partial"]
=== PASS Test err:XD0030 - 002
http://tests.xproc.org/tests/required/err-d0030-002.xml

Wrong error: expected err:XD0030 but null was raised.

* XD0030: 
* null: 

[role="pass"]
=== PASS Test err:XD0031 #001
http://tests.xproc.org/tests/required/err-d0031-001.xml


==== Error message


* XD0031

[role="pass"]
=== PASS Test err:XD0031 #002
http://tests.xproc.org/tests/required/err-d0031-002.xml


==== Error message


* XD0031

[role="pass"]
=== PASS Test err:XD0033 #001
http://tests.xproc.org/tests/required/err-d0033-001.xml


==== Error message


* XD0033

[role="pass"]
=== PASS Test err:XD0033 #002
http://tests.xproc.org/tests/required/err-d0033-002.xml


==== Error message


* XD0033

[role="pass"]
=== PASS Test err:XD0034 - 001
http://tests.xproc.org/tests/required/err-d0034-001.xml


==== Error message


* You can't specify a namespace if the attribute name contains a colon

[role="pass"]
=== PASS Test err:XD0034 - 002
http://tests.xproc.org/tests/required/err-d0034-002.xml


==== Error message


* You can't specify a prefix without a namespace

[role="pass"]
=== PASS Test err:XD0034 - 003
http://tests.xproc.org/tests/required/err-d0034-003.xml


==== Error message


* You can't specify a namespace if the attribute name contains a colon

[role="pass"]
=== PASS Test err:XD0034 - 004
http://tests.xproc.org/tests/required/err-d0034-004.xml


==== Error message


* You can't specify a prefix without a namespace

[role="pass"]
=== PASS Test err:XD0034 - 005
http://tests.xproc.org/tests/required/err-d0034-005.xml


==== Error message


* You can't specify a namespace if the wrapper name contains a colon

[role="pass"]
=== PASS Test err:XD0034 - 006
http://tests.xproc.org/tests/required/err-d0034-006.xml


==== Error message


* You can't specify a prefix without a namespace

[role="pass"]
=== PASS Test err:XD0034 - 007
http://tests.xproc.org/tests/required/err-d0034-007.xml


==== Error message


* You can't specify a namespace if the new-name contains a colon

[role="pass"]
=== PASS Test err:XD0034 - 008
http://tests.xproc.org/tests/required/err-d0034-008.xml


==== Error message


* You can't specify a prefix without a namespace

[role="pass"]
=== PASS Test err:XD0034 - 009
http://tests.xproc.org/tests/required/err-d0034-009.xml


==== Error message


* You can't specify a namespace if the wrapper name contains a colon

[role="pass"]
=== PASS Test err:XD0034 - 010
http://tests.xproc.org/tests/required/err-d0034-010.xml


==== Error message


* You can't specify a prefix without a namespace

[role="pass"]
=== PASS Test err:XD0034 - 011
http://tests.xproc.org/tests/required/err-d0034-011.xml


==== Error message


* You can't specify a namespace if the wrapper name contains a colon

[role="pass"]
=== PASS Test err:XD0034 - 012
http://tests.xproc.org/tests/required/err-d0034-012.xml


==== Error message


* You can't specify a prefix without a namespace

[role="pass"]
=== PASS Test err:XD0034 - 013
http://tests.xproc.org/tests/required/err-d0034-013.xml


==== Error message


* You can't specify a namespace if the code name contains a colon

[role="pass"]
=== PASS Test err:XD0034 - 014
http://tests.xproc.org/tests/required/err-d0034-014.xml


==== Error message


* You can't specify a prefix without a namespace

[role="pass"]
=== PASS Test err:XD0034 - 015
http://tests.xproc.org/tests/required/err-d0034-015.xml


==== Error message


* You cannot specify a namespace if the wrapper name contains a colon.

[role="pass"]
=== PASS Test err:XD0034 - 016
http://tests.xproc.org/tests/required/err-d0034-016.xml


==== Error message


* You cannot specify a prefix without a namespace.

[role="pass"]
=== PASS Test err:XD0034 - 017
http://tests.xproc.org/tests/required/err-d0034-017.xml


==== Error message


* You cannot specify a prefix without a namespace.

[role="pass"]
=== PASS Test err:XD0034 - 018
http://tests.xproc.org/tests/required/err-d0034-018.xml


==== Error message


* You cannot specify a namespace without a wrapper.

[role="pass"]
=== PASS Test err:XS0008
http://tests.xproc.org/tests/required/err-primary-001.xml


==== Error message


* The "primary" attribute is not allowed in this context.

[role="pass"]
=== PASS Test for err:XS0001
http://tests.xproc.org/tests/required/err-s0001-001.xml


==== Error message


* No roots in pipeline

[role="pass"]
=== PASS Test for err:XS0001 #002
http://tests.xproc.org/tests/required/err-s0001-002.xml


==== Error message


* No roots in pipeline

[role="pass"]
=== PASS Test for err:XS0001 #003
http://tests.xproc.org/tests/required/err-s0001-003.xml


==== Error message


* No roots in pipeline

[role="pass"]
=== PASS Test for err:XS0001 #004
http://tests.xproc.org/tests/required/err-s0001-004.xml


==== Error message


* No roots in !1.3.1

[role="pass partial"]
=== PASS Test for err:XS0001 #005
http://tests.xproc.org/tests/required/err-s0001-005.xml

Wrong error: expected err:XS0001 but err:XS0006 was raised.

* XS0001: 
* XS0006: 

==== Error message


* Unbound primary output port on last step: !1.2.1

[role="pass"]
=== PASS Test for err:XS0001 #006
http://tests.xproc.org/tests/required/err-s0001-006.xml


==== Error message


* No roots in !1.3.1

[role="pass partial"]
=== PASS Test for err:XS0001 #007
http://tests.xproc.org/tests/required/err-s0001-007.xml

Wrong error: expected err:XS0001 but err:XS0006 was raised.

* XS0001: 
* XS0006: 

==== Error message


* Unbound primary output port on last step: !1.2.1

[role="pass"]
=== PASS Test for err:XS0001 #008
http://tests.xproc.org/tests/required/err-s0001-008.xml


==== Error message


* No roots in !1.3.1

[role="pass"]
=== PASS Test for err:XS0001 #010
http://tests.xproc.org/tests/required/err-s0001-010.xml


==== Error message


* No roots in !1.3.1

[role="pass"]
=== PASS Test for err:XS0001 #011
http://tests.xproc.org/tests/required/err-s0001-011.xml


==== Error message


* No roots in !1.3.1

[role="pass"]
=== PASS Test for duplicate names error (err:XS0002)
http://tests.xproc.org/tests/required/err-s0002-001.xml


==== Error message


* Duplicate step name: stepname

[role="pass"]
=== PASS Test for duplicate names error (err:XS0002)
http://tests.xproc.org/tests/required/err-s0002-002.xml


==== Error message


* Duplicate step name: identity

[role="pass partial"]
=== PASS Test err:XS0003 #001
http://tests.xproc.org/tests/required/err-s0003-001.xml

Wrong error: expected err:XS0003 but err:XS0032 was raised.

* XS0003: 
* XS0032: 

==== Error message


* Input alternate unbound on p:compare step named !1.3.1.1 and no default binding available.

[role="pass partial"]
=== PASS Test err:XS0003 #002
http://tests.xproc.org/tests/required/err-s0003-002.xml

Wrong error: expected err:XS0003 but err:XS0030 was raised.

* XS0003: 
* XS0030: 

==== Error message


* At most one primary input port is allowed

[role="pass partial"]
=== PASS Test err:XS0003 #004
http://tests.xproc.org/tests/required/err-s0003-004.xml

Wrong error: expected err:XS0003 but err:XS0032 was raised.

* XS0003: 
* XS0032: 

==== Error message


* Input source unbound on p:error step named !1.4.1.1 and no default binding available.

[role="pass"]
=== PASS Test for err:XS0004 #001
http://tests.xproc.org/tests/required/err-s0004-001.xml


==== Error message


* Duplication option name: select

[role="pass"]
=== PASS Test for err:XS0004 #002
http://tests.xproc.org/tests/required/err-s0004-002.xml


==== Error message


* Duplication option name: _

[role="pass"]
=== PASS Test for err:XS0004 #003
http://tests.xproc.org/tests/required/err-s0004-003.xml


==== Error message


* Duplicate variable/option name: varName

[role="pass"]
=== PASS Test for err:XS0004 #004
http://tests.xproc.org/tests/required/err-s0004-004.xml


==== Error message


* Duplicate variable/option name: foo

[role="pass partial"]
=== PASS Test err:XS0005 #001
http://tests.xproc.org/tests/required/err-s0005-001.xml

Wrong error: expected err:XS0005 but ERR was raised.

* XS0005: 
* ERR: 

==== Error message


* Unbound primary output: [output result on identity1]

[role="pass partial"]
=== PASS Test err:XS0005 #002
http://tests.xproc.org/tests/required/err-s0005-002.xml

Wrong error: expected err:XS0005 but ERR was raised.

* XS0005: 
* ERR: 

==== Error message


* Unbound primary output: [output result on xslt]

[role="pass partial"]
=== PASS Test err:XS0005 #003
http://tests.xproc.org/tests/required/err-s0005-003.xml

Wrong error: expected err:XS0005 but err:XS0006 was raised.

* XS0005: 
* XS0006: 

==== Error message


* Unbound primary output port on last step: !1.3.1

[role="pass partial"]
=== PASS Test err:XS0005 #004
http://tests.xproc.org/tests/required/err-s0005-004.xml

Wrong error: expected err:XS0005 but err:XS0006 was raised.

* XS0005: 
* XS0006: 

==== Error message


* Unbound primary output port on last step: !1.3.1

[role="pass partial"]
=== PASS Test err:XS0005 #005
http://tests.xproc.org/tests/required/err-s0005-005.xml

Wrong error: expected err:XS0005 but err:XS0006 was raised.

* XS0005: 
* XS0006: 

==== Error message


* Unbound primary output port on last step: !1.4.1.1

[role="pass partial"]
=== PASS Test err:XS0005 #006
http://tests.xproc.org/tests/required/err-s0005-006.xml

Wrong error: expected err:XS0005 but ERR was raised.

* XS0005: 
* ERR: 

==== Error message


* Unbound primary output: [output result on identity]

[role="pass partial"]
=== PASS Test err:XS0005 #007
http://tests.xproc.org/tests/required/err-s0005-007.xml

Wrong error: expected err:XS0005 but ERR was raised.

* XS0005: 
* ERR: 

==== Error message


* Unbound primary output: [output result on identity]

[role="pass partial"]
=== PASS Test err:XS0005 #008
http://tests.xproc.org/tests/required/err-s0005-008.xml

Wrong error: expected err:XS0005 but ERR was raised.

* XS0005: 
* ERR: 

==== Error message


* Unbound primary output: [output result on identity]

[role="pass partial"]
=== PASS Test err:XS0005 #009
http://tests.xproc.org/tests/required/err-s0005-009.xml

Wrong error: expected err:XS0005 but err:XS0006 was raised.

* XS0005: 
* XS0006: 

==== Error message


* Unbound primary output port on last step: loop

[role="pass partial"]
=== PASS Test err:XS0005 #010
http://tests.xproc.org/tests/required/err-s0005-010.xml

Wrong error: expected err:XS0005 but err:XS0006 was raised.

* XS0005: 
* XS0006: 

==== Error message


* Unbound primary output port on last step: !1.4.1

[role="pass partial"]
=== PASS Test err:XS0005 #011
http://tests.xproc.org/tests/required/err-s0005-011.xml

Wrong error: expected err:XS0005 but ERR was raised.

* XS0005: 
* ERR: 

==== Error message


* Unbound primary output: [output !result on group]

[role="pass partial"]
=== PASS Test err:XS0005 #012
http://tests.xproc.org/tests/required/err-s0005-012.xml

Wrong error: expected err:XS0005 but ERR was raised.

* XS0005: 
* ERR: 

==== Error message


* Unbound primary output: [output out on group]

[role="pass partial"]
=== PASS Test err:XS0005 #013
http://tests.xproc.org/tests/required/err-s0005-013.xml

Wrong error: expected err:XS0005 but ERR was raised.

* XS0005: 
* ERR: 

==== Error message


* Unbound primary output: [output out on group]

[role="pass partial"]
=== PASS Test for err:XS0006 - 001
http://tests.xproc.org/tests/required/err-s0006-001.xml

Wrong error: expected err:XS0006 but err:XS0005 was raised.

* XS0006: 
* XS0005: 

==== Error message


* Output port 'result' on step declare-step named pipeline at http://tests.xproc.org/tests/required/err-s0006-001.xml:20 unbound

[role="pass"]
=== PASS Test for err:XS0007
http://tests.xproc.org/tests/required/err-s0007-001.xml


==== Error message


* Input port |result2 is extra.

[role="pass"]
=== PASS Test for err:XS0007 #002
http://tests.xproc.org/tests/required/err-s0007-002.xml


==== Error message


* Output port !result missing.

[role="pass"]
=== PASS Test for err:XS0007 #003
http://tests.xproc.org/tests/required/err-s0007-003.xml


==== Error message


* Output port !result missing.

[role="pass"]
=== PASS Test for err:XS0008 - 001
http://tests.xproc.org/tests/required/err-s0008-001.xml


==== Error message


* Attribute "p:someinvalidattribute" not allowed on p:count

[role="pass"]
=== PASS Test for err:XS0009 - 001
http://tests.xproc.org/tests/required/err-s0009-001.xml


==== Error message


* Output port out2 is extra.

[role="pass"]
=== PASS Test for err:XS0009 - 002
http://tests.xproc.org/tests/required/err-s0009-002.xml


==== Error message


* Output port out has different primary status.

[role="pass"]
=== PASS Test for err:XS0009 - 004
http://tests.xproc.org/tests/required/err-s0009-004.xml


==== Error message


* The p:group and p:catch in a p:try must declare the same outputs

[role="pass"]
=== PASS Test for err:XS0009 - 005
http://tests.xproc.org/tests/required/err-s0009-005.xml


==== Error message


* The p:group and p:catch in a p:try must declare the same outputs

[role="pass"]
=== PASS Test for err:XS0010 - 001
http://tests.xproc.org/tests/required/err-s0010-001.xml


==== Error message


* Undeclared option specified: somenonexistantoption

[role="pass"]
=== PASS Test for err:XS0010 - 002
http://tests.xproc.org/tests/required/err-s0010-002.xml


==== Error message


* Undeclared option specified: mynonexistentoption

[role="pass"]
=== PASS Test for err:XS0010 - 003
http://tests.xproc.org/tests/required/err-s0010-003.xml


==== Error message


* Undeclared input port 'i-do-not-exist' on step p:count named !1.4.1.1 at http://tests.xproc.org/tests/required/err-s0010-003.xml:23

[role="pass"]
=== PASS Test err:XS0011 #001
http://tests.xproc.org/tests/required/err-s0011-001.xml


==== Error message


* Duplicate port name: source

[role="pass"]
=== PASS Test err:XS0011 #002
http://tests.xproc.org/tests/required/err-s0011-002.xml


==== Error message


* Duplicate port name: source

[role="pass"]
=== PASS Test err:XS0011 #003
http://tests.xproc.org/tests/required/err-s0011-003.xml


==== Error message


* Duplicate port name: current

[role="pass"]
=== PASS Test err:XS0011 #004
http://tests.xproc.org/tests/required/err-s0011-004.xml


==== Error message


* Duplicate port name: current

[role="pass"]
=== PASS Test for multiple primary outputs
http://tests.xproc.org/tests/required/err-s0014-001.xml


==== Error message


* You cannot have more than one primary output port.

[role="pass"]
=== PASS Test err:XS0015 #001
http://tests.xproc.org/tests/required/err-s0015-001.xml


==== Error message


* A p:group must contain a subpipeline.

[role="pass"]
=== PASS Test for err:XS0017 - 001
http://tests.xproc.org/tests/required/err-s0017-001.xml


==== Error message


* You can't specify a default value on a required option

[role="pass"]
=== PASS Test for err:XS0018 - 001
http://tests.xproc.org/tests/required/err-s0018-001.xml


==== Error message


* Required option not specified: match

[role="pass"]
=== PASS Test for err:XS0018 - 002
http://tests.xproc.org/tests/required/err-s0018-002.xml


==== Error message


* No value provided for required option "opt"

[role="pass"]
=== PASS Test for err:XS0018 - 003
http://tests.xproc.org/tests/required/err-s0018-003.xml


==== Error message


* Required option not specified: opt

[role="pass"]
=== PASS Test for err:XS0019 - 001
http://tests.xproc.org/tests/required/err-s0019-001.xml


==== Error message


* Variable binding to result on identity not allowed.

[role="pass partial"]
=== PASS Test for err:XS0020 - 001
http://tests.xproc.org/tests/required/err-s0020-001.xml

Wrong error: expected err:XS0020 but null was raised.

* XS0020: 
* null: 

[role="pass partial"]
=== PASS Test for err:XS0020 - 002
http://tests.xproc.org/tests/required/err-s0020-002.xml

Wrong error: expected err:XS0020 but null was raised.

* XS0020: 
* null: 

[role="pass partial"]
=== PASS Test for err:XS0020 - 003
http://tests.xproc.org/tests/required/err-s0020-003.xml

Wrong error: expected err:XS0020 but null was raised.

* XS0020: 
* null: 

[role="pass"]
=== PASS Test err:XS0022 #001
http://tests.xproc.org/tests/required/err-s0022-001.xml


==== Error message


* No step named "foo" is visible here.

[role="pass"]
=== PASS Test for err:XS0022
http://tests.xproc.org/tests/required/err-s0022-002.xml


==== Error message


* No port named "_" on step named "_"

[role="pass partial"]
=== PASS Test for err:XS0022
http://tests.xproc.org/tests/required/err-s0022-003.xml

Wrong error: expected err:XS0022 but null was raised.

* XS0022: 
* null: 

[role="pass partial"]
=== PASS Test for err:XS0022 #004
http://tests.xproc.org/tests/required/err-s0022-004.xml

Wrong error: expected err:XS0022 but null was raised.

* XS0022: 
* null: 

[role="pass partial"]
=== PASS Test for err:XS0022 #005
http://tests.xproc.org/tests/required/err-s0022-005.xml

Wrong error: expected err:XS0022 but err:XS0006 was raised.

* XS0022: 
* XS0006: 

==== Error message


* Unbound primary output port on last step: !1.3.1

[role="pass partial"]
=== PASS Test for err:XS0022 #006
http://tests.xproc.org/tests/required/err-s0022-006.xml

Wrong error: expected err:XS0022 but XE0001 was raised.

* XS0022: 
* XE0001: 

==== Error message


* Unreadable port: current on viewport

[role="pass partial"]
=== PASS Test for err:XS0024 #001
http://tests.xproc.org/tests/required/err-s0024-001.xml

Wrong error: expected err:XS0024 but err:XS0011 was raised.

* XS0024: 
* XS0011: 

==== Error message


* Duplicate port name: source

[role="pass partial"]
=== PASS Test for err:XS0024 #002
http://tests.xproc.org/tests/required/err-s0024-002.xml

Wrong error: expected err:XS0024 but err:XS0011 was raised.

* XS0024: 
* XS0011: 

==== Error message


* Duplicate port name: source

[role="pass"]
=== PASS Test for err:XS0025 #001
http://tests.xproc.org/tests/required/err-s0025-001.xml


==== Error message


* Type must be in a namespace.

[role="pass"]
=== PASS Test for err:XS0025 #002
http://tests.xproc.org/tests/required/err-s0025-002.xml


==== Error message


* Type must be in a namespace.

[role="pass"]
=== PASS Test for err:XS0025 #003
http://tests.xproc.org/tests/required/err-s0025-003.xml


==== Error message


* Type cannot be in the p: namespace.

[role="pass"]
=== PASS Test for err:XS0025 #004
http://tests.xproc.org/tests/required/err-s0025-004.xml


==== Error message


* Type cannot be in the p: namespace.

[role="pass"]
=== PASS Test for err:XS0026 #001
http://tests.xproc.org/tests/required/err-s0026-001.xml


==== Error message


* A p:log specified for a bad port: foo

[role="pass"]
=== PASS Test for err:XS0026 #002
http://tests.xproc.org/tests/required/err-s0026-002.xml


==== Error message


* A p:log was specified more than once for the same port: result

[role="pass partial"]
=== PASS Test for err:XS0027
http://tests.xproc.org/tests/required/err-s0027-001.xml

Wrong error: expected err:XS0027 but err:XS0004 was raised.

* XS0027: 
* XS0004: 

==== Error message


* Duplication option name: select

[role="pass"]
=== PASS Test err:XS0028 #001
http://tests.xproc.org/tests/required/err-s0028-001.xml


==== Error message


* You cannot specify an option in the p: namespace.

[role="pass"]
=== PASS Test err:XS0028 #002
http://tests.xproc.org/tests/required/err-s0028-002.xml


==== Error message


* You cannot specify a variable in the p: namespace.

[role="pass partial"]
=== PASS Test err:XS0029 #001
http://tests.xproc.org/tests/required/err-s0029-001.xml

Wrong error: expected err:XS0029 but err:XS0042 was raised.

* XS0029: 
* XS0042: 

==== Error message


* Input bindings are not allowed on an atomic step

[role="pass"]
=== PASS Test for multiple primary inputs
http://tests.xproc.org/tests/required/err-s0030-001.xml


==== Error message


* You cannot have more than one primary input port.

[role="pass partial"]
=== PASS Test for err:XS0031 - 001
http://tests.xproc.org/tests/required/err-s0031-001.xml

Wrong error: expected err:XS0031 but err:XS0010 was raised.

* XS0031: 
* XS0010: 

==== Error message


* Undeclared option specified: not-declared

[role="pass partial"]
=== PASS Test for err:XS0031 - 002
http://tests.xproc.org/tests/required/err-s0031-002.xml

Wrong error: expected err:XS0031 but err:XS0010 was raised.

* XS0031: 
* XS0010: 

==== Error message


* Undeclared option specified: undeclared

[role="pass"]
=== PASS Test err:XS0032 #001
http://tests.xproc.org/tests/required/err-s0032-001.xml


==== Error message


* Input source unbound on p:sink step named !1.2.1.1 and no default binding available.

[role="pass"]
=== PASS Test for err:XS0033 - 001
http://tests.xproc.org/tests/required/err-s0033-001.xml


==== Error message


* Kind must be document or parameter

[role="pass partial"]
=== PASS Test for err:XS0034 - 001
http://tests.xproc.org/tests/required/err-s0034-001.xml

Wrong error: expected err:XS0034 but XE0001 was raised.

* XS0034: 
* XE0001: 

==== Error message


* Port is not a parameter input port: source

[role="pass"]
=== PASS Test for err:XS0034 - 002
http://tests.xproc.org/tests/required/err-s0034-002.xml


==== Error message


* No parameter input port.

[role="pass"]
=== PASS Test err:XS0035 #001
http://tests.xproc.org/tests/required/err-s0035-001.xml


==== Error message


* You must not specify bindings in this context.

[role="pass"]
=== PASS Test err:XS0035 #002
http://tests.xproc.org/tests/required/err-s0035-002.xml


==== Error message


* You must not specify bindings in this context.

[role="pass partial"]
=== PASS Test err:XS0036 #001
http://tests.xproc.org/tests/required/err-s0036-001.xml

Wrong error: expected err:XS0036 but err:XS0025 was raised.

* XS0036: 
* XS0025: 

==== Error message


* Type cannot be in the p: namespace.

[role="pass partial"]
=== PASS Test err:XS0036 #002
http://tests.xproc.org/tests/required/err-s0036-002.xml

Wrong error: expected err:XS0036 but null was raised.

* XS0036: 
* null: 

[role="pass partial"]
=== PASS Test err:XS0036 #003
http://tests.xproc.org/tests/required/err-s0036-003.xml

Wrong error: expected err:XS0036 but null was raised.

* XS0036: 
* null: 

[role="pass partial"]
=== PASS Test err:XS0036 #004
http://tests.xproc.org/tests/required/err-s0036-004.xml

Wrong error: expected err:XS0036 but null was raised.

* XS0036: 
* null: 

[role="pass partial"]
=== PASS Test err:xs0036 #005
http://tests.xproc.org/tests/required/err-s0036-005.xml

Wrong error: expected err:XS0036 but err:XS0025 was raised.

* XS0036: 
* XS0025: 

==== Error message


* Type cannot be in the p: namespace.

[role="pass"]
=== PASS Test for err:XS0037 - 001
http://tests.xproc.org/tests/required/err-s0037-001.xml


==== Error message


* Unexpected text: some text

[role="pass"]
=== PASS Test for err:XS0037 - 002
http://tests.xproc.org/tests/required/err-s0037-002.xml


==== Error message


* Unexpected text: some text

[role="pass"]
=== PASS Test for err:XS0037 - 003
http://tests.xproc.org/tests/required/err-s0037-003.xml


==== Error message


* Unexpected text: some text

[role="pass partial"]
=== PASS Test for err:XS0038 - 001
http://tests.xproc.org/tests/required/err-s0038-001.xml

Wrong error: expected err:XS0038 but null was raised.

* XS0038: 
* null: 

[role="pass partial"]
=== PASS Test for err:XS0038 - 002
http://tests.xproc.org/tests/required/err-s0038-002.xml

Wrong error: expected err:XS0038 but null was raised.

* XS0038: 
* null: 

[role="pass"]
=== PASS Test for err:XS0039 - 001
http://tests.xproc.org/tests/required/err-s0039-001.xml


==== Error message


* A p:serialization specifies a non-existant port.

[role="pass"]
=== PASS Test for err:XS0039 - 002
http://tests.xproc.org/tests/required/err-s0039-002.xml


==== Error message


* A p:serialization must specify a port and can only be specified once.

[role="pass"]
=== PASS Test for err:XS0040 - 001
http://tests.xproc.org/tests/required/err-s0040-001.xml


==== Error message


* Sequence cannot be 'false' on a parameter input

[role="pass"]
=== PASS Test err:XS0041 #001
http://tests.xproc.org/tests/required/err-s0041-001.xml


==== Error message


* XS0041

[role="pass"]
=== PASS Test err:XS0042 #001
http://tests.xproc.org/tests/required/err-s0042-001.xml


==== Error message


* Input bindings are not allowed on an atomic step

[role="pass"]
=== PASS Test err:XS0044 #001
http://tests.xproc.org/tests/required/err-s0044-001.xml


==== Error message


* Unexpected step name: p:this-is-an-error

[role="pass"]
=== PASS Test err:XS0044 #002
http://tests.xproc.org/tests/required/err-s0044-002.xml


==== Error message


* Unexpected step name: this-is-an-error

[role="pass"]
=== PASS Test err:XS0044 #0003
http://tests.xproc.org/tests/required/err-s0044-003.xml


==== Error message


* Default input bindings cannot use p:pipe

[role="pass partial"]
=== PASS Test for err:XS0048 - 001
http://tests.xproc.org/tests/required/err-s0048-001.xml

Wrong error: expected err:XS0048 but err:XS0044 was raised.

* XS0048: 
* XS0044: 

==== Error message


* A p:identity step must contain only a signature. p:identity not allowed.

[role="pass"]
=== PASS Test err:XS0051 #001
http://tests.xproc.org/tests/required/err-s0051-001.xml


==== Error message


* Unbound prefix in except-prefixes: #foo

[role="pass"]
=== PASS Test err:XS0051 #001
http://tests.xproc.org/tests/required/err-s0051-002.xml


==== Error message


* Unbound prefix in except-prefixes: h

[role="pass"]
=== PASS Test err:XS0052 #001
http://tests.xproc.org/tests/required/err-s0052-001.xml


==== Error message


* Cannot import: http://tests.xproc.org/tests/required/i-do-not-exist.xml

[role="pass"]
=== PASS Test err:XS0052 #002
http://tests.xproc.org/tests/required/err-s0052-002.xml


==== Error message


* Not a pipeline or library: doc

[role="pass"]
=== PASS Test err:XS0053 #001
http://tests.xproc.org/tests/required/err-s0053-001.xml


==== Error message


* No type attribute on imported pipeline.

[role="pass"]
=== PASS Test err:XS0055 #001
http://tests.xproc.org/tests/required/err-s0055-001.xml


==== Error message


* Parameter input parameters unbound on p:xslt step named !1.3.1.2 and no default binding available.

[role="pass"]
=== PASS Test err:XS0055 #002
http://tests.xproc.org/tests/required/err-s0055-002.xml


==== Error message


* Parameter input parameters unbound on foo:test step named !1.4.1.4 and no default binding available.

[role="pass"]
=== PASS Test err:XS0057 #001
http://tests.xproc.org/tests/required/err-s0057-001.xml


==== Error message


* No binding for 'foo:'

[role="pass"]
=== PASS Test err:XS0057 #002
http://tests.xproc.org/tests/required/err-s0057-002.xml


==== Error message


* No binding for 'foo^bar:'

[role="pass partial"]
=== PASS Test err:XS0058 #001
http://tests.xproc.org/tests/required/err-s0058-001.xml

Wrong error: expected err:XS0058 but err:XD0007 was raised.

* XS0058: 
* XD0007: 

==== Error message


* XD0007

[role="pass"]
=== PASS Test for err:XS0059 #001
http://tests.xproc.org/tests/required/err-s0059-001.xml


==== Error message


* Expected p:declare-step or p:pipeline, got foo

[role="pass partial"]
=== PASS Test err:XS0061 #001
http://tests.xproc.org/tests/required/err-s0061-001.xml

Wrong error: expected err:XS0061 but err:XD0023 was raised.

* XS0061: 
* XD0023: 

==== Error message


* Finding root of tree: the context item is absent

[role="pass"]
=== PASS Test for err:XS0062 #001
http://tests.xproc.org/tests/required/err-s0062-001.xml


==== Error message


* Version attribute is required.

[role="pass"]
=== PASS Test for err:XS0062 #002
http://tests.xproc.org/tests/required/err-s0062-002.xml


==== Error message


* Version attribute is required.

[role="pass"]
=== PASS Test err:XS0063 #001
http://tests.xproc.org/tests/required/err-s0063-001.xml


==== Error message


* XProc error err:XS0063

[role="pass"]
=== PASS Test p:error #001
http://tests.xproc.org/tests/required/error-001.xml


==== Error message


* Bang!

[role="pass"]
=== PASS Test p:error #002
http://tests.xproc.org/tests/required/error-002.xml


[role="pass"]
=== PASS Test p:error #003
http://tests.xproc.org/tests/required/error-003.xml


[role="pass"]
=== PASS Test escape-markup #001
http://tests.xproc.org/tests/required/escape-markup-001.xml


[role="pass"]
=== PASS Test evaluation order #001
http://tests.xproc.org/tests/required/evaluation-order-001.xml


[role="pass"]
=== PASS Test evaluation order #002
http://tests.xproc.org/tests/required/evaluation-order-002.xml


[role="pass"]
=== PASS Test evaluation order #003
http://tests.xproc.org/tests/required/evaluation-order-003.xml


[role="pass"]
=== PASS Test exclude-inline-prefixes-001
http://tests.xproc.org/tests/required/exclude-inline-prefixes-001.xml


[role="pass"]
=== PASS Test exclude-inline-prefixes-002
http://tests.xproc.org/tests/required/exclude-inline-prefixes-002.xml


[role="pass"]
=== PASS Test exclude-inline-prefixes-003
http://tests.xproc.org/tests/required/exclude-inline-prefixes-003.xml


[role="pass"]
=== PASS Test exclude-inline-prefixes-004
http://tests.xproc.org/tests/required/exclude-inline-prefixes-004.xml


[role="pass"]
=== PASS Test exclude-inline-prefixes-005
http://tests.xproc.org/tests/required/exclude-inline-prefixes-005.xml


[role="pass"]
=== PASS Test exclude-inline-prefixes-006
http://tests.xproc.org/tests/required/exclude-inline-prefixes-006.xml


[role="pass"]
=== PASS Test exclude-inline-prefixes-007
http://tests.xproc.org/tests/required/exclude-inline-prefixes-007.xml


[role="pass"]
=== PASS Test exclude-inline-prefixes-008
http://tests.xproc.org/tests/required/exclude-inline-prefixes-008.xml


[role="pass"]
=== PASS Test exclude-inline-prefixes-009
http://tests.xproc.org/tests/required/exclude-inline-prefixes-009.xml


[role="pass"]
=== PASS Test exclude-inline-prefixes-010
http://tests.xproc.org/tests/required/exclude-inline-prefixes-010.xml


[role="pass"]
=== PASS Test fibonacci
http://tests.xproc.org/tests/required/fibonacci.xml


[role="pass"]
=== PASS Test filter-001
http://tests.xproc.org/tests/required/filter-001.xml


[role="pass"]
=== PASS Test filter-002
http://tests.xproc.org/tests/required/filter-002.xml


[role="pass"]
=== PASS Test filter-003
http://tests.xproc.org/tests/required/filter-003.xml


[role="pass"]
=== PASS Test for-each #001
http://tests.xproc.org/tests/required/for-each-001.xml


[role="pass"]
=== PASS Test for-each #002
http://tests.xproc.org/tests/required/for-each-002.xml


[role="pass"]
=== PASS Test for-each #003
http://tests.xproc.org/tests/required/for-each-003.xml


[role="pass"]
=== PASS Test for-each #004
http://tests.xproc.org/tests/required/for-each-004.xml


[role="pass"]
=== PASS Test for-each #005
http://tests.xproc.org/tests/required/for-each-005.xml


[role="pass"]
=== PASS Test for-each #006
http://tests.xproc.org/tests/required/for-each-006.xml


[role="pass"]
=== PASS Test for-each #007
http://tests.xproc.org/tests/required/for-each-007.xml


[role="pass"]
=== PASS Test for-each #008
http://tests.xproc.org/tests/required/for-each-008.xml


[role="pass"]
=== PASS Test for-each #009
http://tests.xproc.org/tests/required/for-each-009.xml


[role="pass"]
=== PASS Test for-each #010
http://tests.xproc.org/tests/required/for-each-010.xml


[role="pass"]
=== PASS Test for-each #011
http://tests.xproc.org/tests/required/for-each-011.xml


[role="pass"]
=== PASS Test for-each #004
http://tests.xproc.org/tests/required/for-each-012.xml


[role="pass"]
=== PASS Test group #001
http://tests.xproc.org/tests/required/group-001.xml


[role="pass"]
=== PASS Test group #002
http://tests.xproc.org/tests/required/group-002.xml


[role="pass"]
=== PASS Test group #003
http://tests.xproc.org/tests/required/group-003.xml


[role="pass"]
=== PASS Test http-request #001
http://tests.xproc.org/tests/required/http-request-001.xml


[role="pass"]
=== PASS Test http-request #002
http://tests.xproc.org/tests/required/http-request-002.xml


[role="pass"]
=== PASS Test http-request #003
http://tests.xproc.org/tests/required/http-request-003.xml


[role="pass"]
=== PASS Test http-request #004
http://tests.xproc.org/tests/required/http-request-004.xml


[role="pass"]
=== PASS Test http-request #005
http://tests.xproc.org/tests/required/http-request-005.xml


[role="pass"]
=== PASS Test http-request #006
http://tests.xproc.org/tests/required/http-request-006.xml


[role="pass"]
=== PASS Test http-request #007
http://tests.xproc.org/tests/required/http-request-007.xml


[role="pass"]
=== PASS Test http-request #008
http://tests.xproc.org/tests/required/http-request-008.xml


[role="pass"]
=== PASS Test http-request #009
http://tests.xproc.org/tests/required/http-request-009.xml


[role="pass"]
=== PASS Test http-request #010
http://tests.xproc.org/tests/required/http-request-010.xml


[role="pass"]
=== PASS Test http-request #011
http://tests.xproc.org/tests/required/http-request-011.xml


[role="pass"]
=== PASS Test http-request #012
http://tests.xproc.org/tests/required/http-request-012.xml


[role="pass"]
=== PASS Test http-request #009
http://tests.xproc.org/tests/required/http-request-013.xml


[role="pass"]
=== PASS Test http-request #014
http://tests.xproc.org/tests/required/http-request-014.xml


[role="pass"]
=== PASS Test p:identity-step-001
http://tests.xproc.org/tests/required/identity-001.xml


[role="pass"]
=== PASS Test p:identity-step-002
http://tests.xproc.org/tests/required/identity-002.xml


[role="pass"]
=== PASS Test p:identity-step-002
http://tests.xproc.org/tests/required/identity-003.xml


[role="pass"]
=== PASS Test p:identity-step-004
http://tests.xproc.org/tests/required/identity-004.xml


[role="pass"]
=== PASS Test p:identity-step-005
http://tests.xproc.org/tests/required/identity-005.xml


[role="pass"]
=== PASS Test p:import #001
http://tests.xproc.org/tests/required/import-001.xml


[role="pass"]
=== PASS Test p:import #002
http://tests.xproc.org/tests/required/import-002.xml


[role="pass"]
=== PASS Test p:import #009
http://tests.xproc.org/tests/required/import-003.xml


[role="pass"]
=== PASS Test p:import #004
http://tests.xproc.org/tests/required/import-004.xml


[role="pass"]
=== PASS Test p:import #005
http://tests.xproc.org/tests/required/import-005.xml


[role="pass"]
=== PASS Test p:import #006
http://tests.xproc.org/tests/required/import-006.xml


[role="pass"]
=== PASS Test p:import #007
http://tests.xproc.org/tests/required/import-007.xml


[role="pass"]
=== PASS Test p:import #008
http://tests.xproc.org/tests/required/import-008.xml


[role="pass"]
=== PASS Test p:import #009
http://tests.xproc.org/tests/required/import-009.xml


[role="pass"]
=== PASS Test p:import #010
http://tests.xproc.org/tests/required/import-010.xml


[role="pass"]
=== PASS Test p:import #011
http://tests.xproc.org/tests/required/import-011.xml


[role="pass"]
=== PASS Test input-001
http://tests.xproc.org/tests/required/input-001.xml


[role="pass"]
=== PASS Test input-002
http://tests.xproc.org/tests/required/input-002.xml


[role="pass"]
=== PASS Test input-003
http://tests.xproc.org/tests/required/input-003.xml


[role="pass"]
=== PASS Test input-004
http://tests.xproc.org/tests/required/input-004.xml


[role="pass"]
=== PASS Test input-005
http://tests.xproc.org/tests/required/input-005.xml


[role="pass"]
=== PASS Test input-006
http://tests.xproc.org/tests/required/input-006.xml


[role="pass"]
=== PASS Test input-007
http://tests.xproc.org/tests/required/input-007.xml


[role="pass"]
=== PASS Test input-008
http://tests.xproc.org/tests/required/input-008.xml


[role="pass"]
=== PASS Test input-009
http://tests.xproc.org/tests/required/input-009.xml


[role="pass"]
=== PASS Test input-010
http://tests.xproc.org/tests/required/input-010.xml


[role="pass"]
=== PASS Test input-011
http://tests.xproc.org/tests/required/input-011.xml


[role="pass"]
=== PASS Test input-012
http://tests.xproc.org/tests/required/input-012.xml


[role="pass"]
=== PASS Test p:insert #001
http://tests.xproc.org/tests/required/insert-001.xml


[role="pass"]
=== PASS Test p:insert #002
http://tests.xproc.org/tests/required/insert-002.xml


[role="pass"]
=== PASS Test p:insert #003
http://tests.xproc.org/tests/required/insert-003.xml


[role="pass"]
=== PASS Test p:insert #004
http://tests.xproc.org/tests/required/insert-004.xml


[role="pass"]
=== PASS Test insert-005
http://tests.xproc.org/tests/required/insert-005.xml


[role="pass"]
=== PASS Test insert-006
http://tests.xproc.org/tests/required/insert-006.xml


[role="pass"]
=== PASS Test p:insert #007
http://tests.xproc.org/tests/required/insert-007.xml


[role="pass"]
=== PASS Test p:insert #008
http://tests.xproc.org/tests/required/insert-008.xml


[role="pass"]
=== PASS Test insert-009
http://tests.xproc.org/tests/required/insert-009.xml


[role="pass"]
=== PASS Test p:insert #010
http://tests.xproc.org/tests/required/insert-010.xml


[role="pass"]
=== PASS Test iteration #001
http://tests.xproc.org/tests/required/iteration-001.xml


[role="pass"]
=== PASS Test iteration #002
http://tests.xproc.org/tests/required/iteration-002.xml


[role="pass"]
=== PASS Test labelelements001
http://tests.xproc.org/tests/required/labelelements-001.xml


[role="pass"]
=== PASS Test p:label-elements #002
http://tests.xproc.org/tests/required/labelelements-002.xml


[role="pass"]
=== PASS Test p:label-elements #003
http://tests.xproc.org/tests/required/labelelements-003.xml


[role="pass"]
=== PASS Test labelelements #004
http://tests.xproc.org/tests/required/labelelements-004.xml


[role="pass"]
=== PASS Test p:label-elements #005
http://tests.xproc.org/tests/required/labelelements-005.xml


[role="pass"]
=== PASS Test labelelements #006
http://tests.xproc.org/tests/required/labelelements-006.xml


[role="pass"]
=== PASS Test labelelements #007
http://tests.xproc.org/tests/required/labelelements-007.xml


[role="pass"]
=== PASS Test labelelements #008
http://tests.xproc.org/tests/required/labelelements-008.xml


[role="pass"]
=== PASS Test labelelements #009
http://tests.xproc.org/tests/required/labelelements-009.xml


[role="pass"]
=== PASS Test labelelements #010
http://tests.xproc.org/tests/required/labelelements-010.xml


[role="pass"]
=== PASS Test labelelements #011
http://tests.xproc.org/tests/required/labelelements-011.xml


[role="pass"]
=== PASS Test p:load #001
http://tests.xproc.org/tests/required/load-001.xml


[role="pass"]
=== PASS Test p:load #002
http://tests.xproc.org/tests/required/load-002.xml


[role="pass"]
=== PASS Test p:load #003
http://tests.xproc.org/tests/required/load-003.xml


[role="pass"]
=== PASS Test p:load #004
http://tests.xproc.org/tests/required/load-004.xml


[role="pass"]
=== PASS Test p:log #001
http://tests.xproc.org/tests/required/log-001.xml


[role="pass"]
=== PASS Test p:log #002
http://tests.xproc.org/tests/required/log-002.xml


[role="pass"]
=== PASS Test make-absolute-uris #001
http://tests.xproc.org/tests/required/make-absolute-uris-001.xml


[role="pass"]
=== PASS Test make-absolute-uris #002
http://tests.xproc.org/tests/required/make-absolute-uris-002.xml


[role="pass"]
=== PASS Test make-absolute-uris #003
http://tests.xproc.org/tests/required/make-absolute-uris-003.xml


[role="pass"]
=== PASS Test make-sequence
http://tests.xproc.org/tests/required/make-sequence.xml


[role="pass"]
=== PASS Test http-request multipart #001
http://tests.xproc.org/tests/required/multipart-001.xml


[role="pass"]
=== PASS Test http-request multipart #002
http://tests.xproc.org/tests/required/multipart-002.xml


[role="pass"]
=== PASS Test http-request multipart #003
http://tests.xproc.org/tests/required/multipart-003.xml


[role="pass"]
=== PASS Test http-request multipart #004
http://tests.xproc.org/tests/required/multipart-004.xml


[role="pass"]
=== PASS Test http-request multipart #005
http://tests.xproc.org/tests/required/multipart-005.xml


[role="pass"]
=== PASS Test namespace-rename-001
http://tests.xproc.org/tests/required/namespace-rename-001.xml


[role="pass"]
=== PASS Test p:namespace-rename #002
http://tests.xproc.org/tests/required/namespace-rename-002.xml


[role="pass"]
=== PASS Test p:namespace-rename #003
http://tests.xproc.org/tests/required/namespace-rename-003.xml


[role="pass"]
=== PASS Test p:namespace-rename #004
http://tests.xproc.org/tests/required/namespace-rename-004.xml


[role="pass"]
=== PASS Test p:namespace-rename #005
http://tests.xproc.org/tests/required/namespace-rename-005.xml


[role="pass"]
=== PASS Test p:namespace-rename #006
http://tests.xproc.org/tests/required/namespace-rename-006.xml


[role="pass"]
=== PASS Test p:namespace-rename #007
http://tests.xproc.org/tests/required/namespace-rename-007.xml


[role="pass"]
=== PASS Test p:namespace-rename #008
http://tests.xproc.org/tests/required/namespace-rename-008.xml


[role="pass"]
=== PASS Test p:namespace-rename #009
http://tests.xproc.org/tests/required/namespace-rename-009.xml


[role="pass"]
=== PASS Test p:namespace-rename #010
http://tests.xproc.org/tests/required/namespace-rename-010.xml


[role="pass"]
=== PASS Test p:namespace-rename #011
http://tests.xproc.org/tests/required/namespace-rename-011.xml


[role="pass"]
=== PASS Test p:namespace-rename #012
http://tests.xproc.org/tests/required/namespace-rename-012.xml


[role="pass"]
=== PASS Test p:namespace-rename #013
http://tests.xproc.org/tests/required/namespace-rename-013.xml


[role="pass"]
=== PASS Test p:namespace-rename #014
http://tests.xproc.org/tests/required/namespace-rename-014.xml


[role="pass"]
=== PASS Test namespace-rename-015
http://tests.xproc.org/tests/required/namespace-rename-015.xml


[role="pass"]
=== PASS Test namespace-rename-016
http://tests.xproc.org/tests/required/namespace-rename-016.xml


[role="pass"]
=== PASS Test namespace-rename-017
http://tests.xproc.org/tests/required/namespace-rename-017.xml


[role="pass"]
=== PASS Test p:namespaces #001
http://tests.xproc.org/tests/required/namespaces-001.xml


[role="pass"]
=== PASS Test p:namespaces #002
http://tests.xproc.org/tests/required/namespaces-002.xml


[role="pass"]
=== PASS Test p:namespaces #003
http://tests.xproc.org/tests/required/namespaces-003.xml


[role="pass"]
=== PASS Test p:namespaces #004
http://tests.xproc.org/tests/required/namespaces-004.xml


[role="pass"]
=== PASS Test p:namespaces #005
http://tests.xproc.org/tests/required/namespaces-005.xml


[role="pass"]
=== PASS Test p:namespaces #006
http://tests.xproc.org/tests/required/namespaces-006.xml


[role="pass"]
=== PASS Test p:namespaces #007
http://tests.xproc.org/tests/required/namespaces-007.xml


[role="pass"]
=== PASS Test p:namespaces #008
http://tests.xproc.org/tests/required/namespaces-008.xml


[role="pass"]
=== PASS Test p:namespaces #009
http://tests.xproc.org/tests/required/namespaces-009.xml


[role="pass"]
=== PASS Test p:namespaces #010
http://tests.xproc.org/tests/required/namespaces-010.xml


[role="pass"]
=== PASS Test nested pipeline #001
http://tests.xproc.org/tests/required/nested-pipeline-001.xml


[role="pass"]
=== PASS Test option #001
http://tests.xproc.org/tests/required/option-001.xml


[role="pass"]
=== PASS Test option #002
http://tests.xproc.org/tests/required/option-002.xml


[role="pass"]
=== PASS Test option #004
http://tests.xproc.org/tests/required/option-004.xml


[role="pass"]
=== PASS Test output-001
http://tests.xproc.org/tests/required/output-001.xml


[role="pass"]
=== PASS Test output-001
http://tests.xproc.org/tests/required/output-002.xml


[role="pass"]
=== PASS Test pack #001
http://tests.xproc.org/tests/required/pack-001.xml


[role="pass"]
=== PASS Test pack #002
http://tests.xproc.org/tests/required/pack-002.xml


[role="pass"]
=== PASS Test pack #003
http://tests.xproc.org/tests/required/pack-003.xml


[role="pass"]
=== PASS Test pack #004
http://tests.xproc.org/tests/required/pack-004.xml


[role="pass"]
=== PASS Test pack #005
http://tests.xproc.org/tests/required/pack-005.xml


[role="pass"]
=== PASS Test pack #006
http://tests.xproc.org/tests/required/pack-006.xml


[role="pass"]
=== PASS Test param-001
http://tests.xproc.org/tests/required/param-001.xml


[role="pass"]
=== PASS Test param-002
http://tests.xproc.org/tests/required/param-002.xml


[role="pass"]
=== PASS Test param-003
http://tests.xproc.org/tests/required/param-003.xml


[role="pass"]
=== PASS Test param-004
http://tests.xproc.org/tests/required/param-004.xml


[role="pass"]
=== PASS Test param-005
http://tests.xproc.org/tests/required/param-005.xml


[role="pass"]
=== PASS Test parameters-001
http://tests.xproc.org/tests/required/parameters-001.xml


[role="pass"]
=== PASS Test parameters-002
http://tests.xproc.org/tests/required/parameters-002.xml


[role="pass"]
=== PASS Test parameters-003
http://tests.xproc.org/tests/required/parameters-003.xml


[role="pass"]
=== PASS Test p:pipe #001
http://tests.xproc.org/tests/required/pipe-001.xml


[role="pass"]
=== PASS Test p:pipeinfo-001
http://tests.xproc.org/tests/required/pipeinfo-001.xml


[role="pass"]
=== PASS Test preserving base URI #001
http://tests.xproc.org/tests/required/preserve-base-uri-001.xml


[role="pass"]
=== PASS Test preserving base URI #002
http://tests.xproc.org/tests/required/preserve-base-uri-002.xml


[role="pass"]
=== PASS Test rename-001
http://tests.xproc.org/tests/required/rename-001.xml


[role="pass"]
=== PASS Test rename-002
http://tests.xproc.org/tests/required/rename-002.xml


[role="pass"]
=== PASS Test rename-003
http://tests.xproc.org/tests/required/rename-003.xml


[role="pass"]
=== PASS Test rename-004
http://tests.xproc.org/tests/required/rename-004.xml


[role="pass"]
=== PASS Test rename-005
http://tests.xproc.org/tests/required/rename-005.xml


[role="pass"]
=== PASS Test rename-006
http://tests.xproc.org/tests/required/rename-006.xml


[role="pass"]
=== PASS Test rename-007
http://tests.xproc.org/tests/required/rename-007.xml


[role="pass"]
=== PASS Test replace001
http://tests.xproc.org/tests/required/replace-001.xml


[role="pass"]
=== PASS Test resolve-uri #001
http://tests.xproc.org/tests/required/resolve-uri-001.xml


[role="pass"]
=== PASS Test resolve-uri #002
http://tests.xproc.org/tests/required/resolve-uri-002.xml


[role="pass"]
=== PASS Test set-attributes #001
http://tests.xproc.org/tests/required/set-attributes-001.xml


[role="pass"]
=== PASS Test set-attributes #002
http://tests.xproc.org/tests/required/set-attributes-002.xml


[role="pass"]
=== PASS Test p:sink #001
http://tests.xproc.org/tests/required/sink-001.xml


[role="pass"]
=== PASS Test p:sink #002
http://tests.xproc.org/tests/required/sink-002.xml


[role="pass"]
=== PASS Test p:sink #003
http://tests.xproc.org/tests/required/sink-003.xml


[role="pass"]
=== PASS Test split-sequence-001
http://tests.xproc.org/tests/required/split-sequence-001.xml


[role="pass"]
=== PASS Test split-sequence-002
http://tests.xproc.org/tests/required/split-sequence-002.xml


[role="pass"]
=== PASS Test split-sequence-003
http://tests.xproc.org/tests/required/split-sequence-003.xml


[role="pass"]
=== PASS Test tail001
http://tests.xproc.org/tests/required/split-sequence-004.xml


[role="pass"]
=== PASS Test split-sequence 005
http://tests.xproc.org/tests/required/split-sequence-005.xml


[role="pass"]
=== PASS Test split-sequence 006
http://tests.xproc.org/tests/required/split-sequence-006.xml


[role="pass"]
=== PASS Test split-sequence #007
http://tests.xproc.org/tests/required/split-sequence-007.xml


[role="pass"]
=== PASS Test step-available #001
http://tests.xproc.org/tests/required/step-available-001.xml


[role="pass"]
=== PASS Test step-available #002
http://tests.xproc.org/tests/required/step-available-002.xml


[role="pass"]
=== PASS Test step-available #003
http://tests.xproc.org/tests/required/step-available-003.xml


[role="pass"]
=== PASS Test step-available #004
http://tests.xproc.org/tests/required/step-available-004.xml


[role="pass"]
=== PASS Test step-available #005
http://tests.xproc.org/tests/required/step-available-005.xml


[role="pass"]
=== PASS Test step-available #006
http://tests.xproc.org/tests/required/step-available-006.xml


[role="pass"]
=== PASS Test the p:store step
http://tests.xproc.org/tests/required/store-001.xml


[role="pass"]
=== PASS Test p:string-replace #001
http://tests.xproc.org/tests/required/string-replace-001.xml


[role="pass"]
=== PASS Test p:string-replace #002
http://tests.xproc.org/tests/required/string-replace-002.xml


[role="pass"]
=== PASS Test p:string-replace #003
http://tests.xproc.org/tests/required/string-replace-003.xml


[role="pass"]
=== PASS Test p:string-replace #004
http://tests.xproc.org/tests/required/string-replace-004.xml


[role="pass"]
=== PASS Test p:string-replace #005
http://tests.xproc.org/tests/required/string-replace-005.xml


[role="pass"]
=== PASS Test system-property-001
http://tests.xproc.org/tests/required/system-property-001.xml


[role="pass"]
=== PASS Test system-property-002
http://tests.xproc.org/tests/required/system-property-002.xml


[role="pass"]
=== PASS Test try/catch #001
http://tests.xproc.org/tests/required/try-001.xml


[role="pass"]
=== PASS Test try/catch #002
http://tests.xproc.org/tests/required/try-002.xml


[role="pass"]
=== PASS Test try/catch #003
http://tests.xproc.org/tests/required/try-003.xml


[role="pass"]
=== PASS Test try/catch #004
http://tests.xproc.org/tests/required/try-004.xml


[role="pass"]
=== PASS Test try/catch #005
http://tests.xproc.org/tests/required/try-005.xml


[role="pass"]
=== PASS Test try/catch #006
http://tests.xproc.org/tests/required/try-006.xml


[role="pass"]
=== PASS Test unescapemarkup-001
http://tests.xproc.org/tests/required/unescapemarkup-001.xml


[role="pass"]
=== PASS Test unescapemarkup-002
http://tests.xproc.org/tests/required/unescapemarkup-002.xml


[role="pass"]
=== PASS Test unescape markup-003
http://tests.xproc.org/tests/required/unescapemarkup-003.xml


[role="pass"]
=== PASS Test unescapemarkup-004
http://tests.xproc.org/tests/required/unescapemarkup-004.xml


[role="pass"]
=== PASS Test unescapemarkup-005
http://tests.xproc.org/tests/required/unescapemarkup-005.xml


[role="pass"]
=== PASS Test unescapemarkup-005
http://tests.xproc.org/tests/required/unescapemarkup-006.xml


[role="pass"]
=== PASS Test unescapemarkup-007
http://tests.xproc.org/tests/required/unescapemarkup-007.xml


[role="pass"]
=== PASS Test unwrap001
http://tests.xproc.org/tests/required/unwrap-001.xml


[role="pass"]
=== PASS Test unwrap 002
http://tests.xproc.org/tests/required/unwrap-002.xml


[role="pass"]
=== PASS Test use-when #001
http://tests.xproc.org/tests/required/use-when-001.xml


[role="pass"]
=== PASS Test use-when #002
http://tests.xproc.org/tests/required/use-when-002.xml


[role="pass"]
=== PASS Test use-when #003
http://tests.xproc.org/tests/required/use-when-003.xml


[role="pass"]
=== PASS Test use-when #004
http://tests.xproc.org/tests/required/use-when-004.xml


[role="pass"]
=== PASS Test value-available #001
http://tests.xproc.org/tests/required/value-available-001.xml


[role="pass"]
=== PASS Test value-available #002
http://tests.xproc.org/tests/required/value-available-002.xml


[role="pass"]
=== PASS Test value-available #003
http://tests.xproc.org/tests/required/value-available-003.xml


[role="pass"]
=== PASS Test value-available #004
http://tests.xproc.org/tests/required/value-available-004.xml


[role="pass"]
=== PASS Test value-available #005
http://tests.xproc.org/tests/required/value-available-005.xml


[role="pass"]
=== PASS Test value-available #006
http://tests.xproc.org/tests/required/value-available-006.xml


[role="pass"]
=== PASS Test variable #001
http://tests.xproc.org/tests/required/variable-001.xml


[role="pass"]
=== PASS Test variable #002
http://tests.xproc.org/tests/required/variable-002.xml


[role="pass"]
=== PASS Test variable #003
http://tests.xproc.org/tests/required/variable-003.xml


[role="pass"]
=== PASS Test variable #004
http://tests.xproc.org/tests/required/variable-004.xml


[role="pass"]
=== PASS Test variable #005
http://tests.xproc.org/tests/required/variable-005.xml


[role="pass"]
=== PASS Test variable #006
http://tests.xproc.org/tests/required/variable-006.xml


[role="pass"]
=== PASS Test variable #007
http://tests.xproc.org/tests/required/variable-007.xml


[role="pass"]
=== PASS Test variable #008
http://tests.xproc.org/tests/required/variable-008.xml


[role="pass"]
=== PASS Test version-available #001
http://tests.xproc.org/tests/required/version-available-001.xml


[role="pass"]
=== PASS Test version-available #002
http://tests.xproc.org/tests/required/version-available-002.xml


[role="pass"]
=== PASS Test versioning #001
http://tests.xproc.org/tests/required/versioning-001.xml


[role="pass"]
=== PASS Test versioning #002
http://tests.xproc.org/tests/required/versioning-002.xml


==== Error message


* No roots in !1.3.1

[role="pass"]
=== PASS Test versioning #003
http://tests.xproc.org/tests/required/versioning-003.xml


[role="pass"]
=== PASS Test versioning #004
http://tests.xproc.org/tests/required/versioning-004.xml


[role="pass"]
=== PASS Test versioning #005
http://tests.xproc.org/tests/required/versioning-005.xml


[role="pass"]
=== PASS Test versioning #006
http://tests.xproc.org/tests/required/versioning-006.xml


[role="pass"]
=== PASS Test versioning #007
http://tests.xproc.org/tests/required/versioning-007.xml


[role="pass"]
=== PASS Test viewport #001
http://tests.xproc.org/tests/required/viewport-001.xml


[role="pass"]
=== PASS Test viewport #002
http://tests.xproc.org/tests/required/viewport-002.xml


[role="pass"]
=== PASS Test viewport #003
http://tests.xproc.org/tests/required/viewport-003.xml


[role="pass"]
=== PASS Test viewport #004
http://tests.xproc.org/tests/required/viewport-004.xml


[role="pass"]
=== PASS Test viewport #005
http://tests.xproc.org/tests/required/viewport-005.xml


[role="pass"]
=== PASS Test viewport #006
http://tests.xproc.org/tests/required/viewport-006.xml


[role="pass"]
=== PASS Test viewport #007
http://tests.xproc.org/tests/required/viewport-007.xml


[role="pass"]
=== PASS Test viewport #008
http://tests.xproc.org/tests/required/viewport-008.xml


[role="pass"]
=== PASS Test viewport #009
http://tests.xproc.org/tests/required/viewport-009.xml


[role="pass"]
=== PASS Test viewport #010
http://tests.xproc.org/tests/required/viewport-010.xml


[role="pass"]
=== PASS Test viewport #011
http://tests.xproc.org/tests/required/viewport-011.xml


[role="pass"]
=== PASS Test wrap001
http://tests.xproc.org/tests/required/wrap-001.xml


[role="pass"]
=== PASS Test wrap-002
http://tests.xproc.org/tests/required/wrap-002.xml


[role="pass"]
=== PASS Test wrap-003
http://tests.xproc.org/tests/required/wrap-003.xml


[role="pass"]
=== PASS Test for p:wrap #004
http://tests.xproc.org/tests/required/wrap-004.xml


[role="pass"]
=== PASS Test for p:wrap #005
http://tests.xproc.org/tests/required/wrap-005.xml


[role="pass"]
=== PASS Test wrap-006
http://tests.xproc.org/tests/required/wrap-006.xml


[role="pass"]
=== PASS Test wrap-007
http://tests.xproc.org/tests/required/wrap-007.xml


[role="pass"]
=== PASS Test wrap-008
http://tests.xproc.org/tests/required/wrap-008.xml


[role="pass"]
=== PASS Test wrap-009
http://tests.xproc.org/tests/required/wrap-009.xml


[role="pass"]
=== PASS Test wrap-010
http://tests.xproc.org/tests/required/wrap-010.xml


[role="pass"]
=== PASS Test wrap-011
http://tests.xproc.org/tests/required/wrap-011.xml


[role="pass"]
=== PASS Test wrap-sequence-001
http://tests.xproc.org/tests/required/wrap-sequence-001.xml


[role="pass"]
=== PASS Test wrap-sequence-002
http://tests.xproc.org/tests/required/wrap-sequence-002.xml


[role="pass"]
=== PASS Test wrap-sequence-003
http://tests.xproc.org/tests/required/wrap-sequence-003.xml


[role="pass"]
=== PASS Test wrap-sequence-003
http://tests.xproc.org/tests/required/wrap-sequence-004.xml


[role="pass"]
=== PASS Test wrap-sequence-005
http://tests.xproc.org/tests/required/wrap-sequence-005.xml


[role="pass"]
=== PASS Test p:xinclude #001
http://tests.xproc.org/tests/required/xinclude-001.xml


[role="pass"]
=== PASS Test p:xinclude #002
http://tests.xproc.org/tests/required/xinclude-002.xml


[role="pass"]
=== PASS Test p:xinclude #003
http://tests.xproc.org/tests/required/xinclude-003.xml


[role="pass"]
=== PASS Test p:xinclude #004
http://tests.xproc.org/tests/required/xinclude-004.xml


[role="pass"]
=== PASS Test p:xinclude #005
http://tests.xproc.org/tests/required/xinclude-005.xml


[role="pass"]
=== PASS Test literal xml:id support #001
http://tests.xproc.org/tests/required/xml-id-001.xml


[role="pass"]
=== PASS Test added xml:id support #002
http://tests.xproc.org/tests/required/xml-id-002.xml


[role="pass"]
=== PASS Test xpath-version-available #001
http://tests.xproc.org/tests/required/xpath-version-available-001.xml


[role="pass"]
=== PASS Test xpath-version-available #001
http://tests.xproc.org/tests/required/xpath-version-available-002.xml


[role="pass"]
=== PASS Test xslt-001
http://tests.xproc.org/tests/required/xslt-001.xml


[role="pass partial"]
=== PASS Test xslt-002
http://tests.xproc.org/tests/required/xslt-002.xml

Wrong error: expected err:XC0038 but err:XD0001 was raised.

* XC0038: 
* XD0001: 

==== Error message


* Only whitespace text nodes can appear at the top level in a document

[role="pass"]
=== PASS Test xslt-003
http://tests.xproc.org/tests/required/xslt-003.xml


[role="pass"]
=== PASS Test xslt-004
http://tests.xproc.org/tests/required/xslt-004.xml


[role="pass"]
=== PASS Test xsl-t005
http://tests.xproc.org/tests/required/xslt-005.xml


[role="pass"]
=== PASS Test xslt-006
http://tests.xproc.org/tests/required/xslt-006.xml



== Serialization tests (Revision 633)

Passed 25 of 25 tests (100.00%).

[role="pass"]
=== PASS Serialization test byte-order-mark-001
http://tests.xproc.org/tests/serialization/byte-order-mark-001.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.

[role="pass"]
=== PASS Serialization test byte-order-mark-002
http://tests.xproc.org/tests/serialization/byte-order-mark-002.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.

[role="pass"]
=== PASS Serialization test cdata-section-elements-001
http://tests.xproc.org/tests/serialization/cdata-section-elements-001.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.

[role="pass"]
=== PASS Serialization test cdata-section-elements-002
http://tests.xproc.org/tests/serialization/cdata-section-elements-002.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.

[role="pass"]
=== PASS Serialization test doctype-public-001
http://tests.xproc.org/tests/serialization/doctype-public-001.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.

[role="pass"]
=== PASS Serialization test doctype-system-001
http://tests.xproc.org/tests/serialization/doctype-system-001.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.

[role="pass"]
=== PASS Serialization test encoding-001
http://tests.xproc.org/tests/serialization/encoding-001.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.

[role="pass partial"]
=== PASS Test for err:XD0020 #001
http://tests.xproc.org/tests/serialization/err-d0020-001.xml

Wrong error: expected err:XD0020 but null was raised.

* XD0020: 
* null: 

[role="pass"]
=== PASS Serialization test escape-uri-001
http://tests.xproc.org/tests/serialization/escape-uri-001.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.

[role="pass"]
=== PASS Serialization test escape-uri-002
http://tests.xproc.org/tests/serialization/escape-uri-002.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.

[role="pass"]
=== PASS Serialization test include-content-type #001
http://tests.xproc.org/tests/serialization/include-content-type-001.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.

[role="pass"]
=== PASS Serialization test include-content-type #002
http://tests.xproc.org/tests/serialization/include-content-type-002.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.

[role="pass"]
=== PASS Serialization test indent #001
http://tests.xproc.org/tests/serialization/indent-001.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.

[role="pass"]
=== PASS Serialization test indent #002
http://tests.xproc.org/tests/serialization/indent-002.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.

[role="pass"]
=== PASS Serialization test media-type #001
http://tests.xproc.org/tests/serialization/media-type-001.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.

[role="pass"]
=== PASS Serialization test normalization-form-001
http://tests.xproc.org/tests/serialization/normalization-form-001.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.

[role="pass"]
=== PASS Serialization test normalization-form-002
http://tests.xproc.org/tests/serialization/normalization-form-002.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.

[role="pass"]
=== PASS Serialization test normalization-form-003
http://tests.xproc.org/tests/serialization/normalization-form-003.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.

[role="pass"]
=== PASS Serialization test omit-xml-declaration-001
http://tests.xproc.org/tests/serialization/omit-xml-declaration-001.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.

[role="pass"]
=== PASS Serialization test omit-xml-declaration-002
http://tests.xproc.org/tests/serialization/omit-xml-declaration-002.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.

[role="pass"]
=== PASS Serialization test standalone-001
http://tests.xproc.org/tests/serialization/standalone-001.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.

[role="pass"]
=== PASS Serialization test standalone-002
http://tests.xproc.org/tests/serialization/standalone-002.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.

[role="pass"]
=== PASS Serialization test standalone-003
http://tests.xproc.org/tests/serialization/standalone-003.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.

[role="pass"]
=== PASS Serialization test undeclare-prefixes-001
http://tests.xproc.org/tests/serialization/undeclare-prefixes-001.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.

[role="pass"]
=== PASS Serialization test version-001
http://tests.xproc.org/tests/serialization/version-001.xml


==== Error messages


* java.io.IOException: Cannot run program "serdiff": java.io.IOException: error=2, No such file or directory
* Compare pipelines failed: this shouldn't happen.


== Optional tests (Revision 633)

Passed 113 of 114 tests (99.12%).

[role="pass partial"]
=== PASS Test for err:XC0033 - 001
http://tests.xproc.org/tests/optional/err-c0033-001.xml

Wrong error: expected err:XC0033 but null was raised.

* XC0033: 
* null: 

[role="pass"]
=== PASS Test for err:XC0034 - 001
http://tests.xproc.org/tests/optional/err-c0034-001.xml


==== Error message


* Cannot change to requested directory: /i/do/not/exist

[role="pass partial"]
=== PASS Test for err:XC0035 - 001
http://tests.xproc.org/tests/optional/err-c0035-001.xml

Wrong error: expected err:XC0035 but null was raised.

* XC0035: 
* null: 

[role="pass partial"]
=== PASS Test for err:XC0035 - 002
http://tests.xproc.org/tests/optional/err-c0035-002.xml

Wrong error: expected err:XC0035 but null was raised.

* XC0035: 
* null: 

[role="pass partial"]
=== PASS Test err:XC0036 - #001
http://tests.xproc.org/tests/optional/err-c0036-001.xml

Wrong error: expected err:XC0036 but err:XD0036 was raised.

* XC0036: 
* XD0036: 

==== Error message


* XD0036

[role="pass partial"]
=== PASS Test err:XC0036 - #002
http://tests.xproc.org/tests/optional/err-c0036-002.xml

Wrong error: expected err:XC0036 but err:XD0036 was raised.

* XC0036: 
* XD0036: 

==== Error message


* XD0036

[role="pass partial"]
=== PASS Test err:XC0036 - #003
http://tests.xproc.org/tests/optional/err-c0036-003.xml

Wrong error: expected err:XC0036 but err:XD0036 was raised.

* XC0036: 
* XD0036: 

==== Error message


* XD0036

[role="pass partial"]
=== PASS Test err:XC0036 - #004
http://tests.xproc.org/tests/optional/err-c0036-004.xml

Wrong error: expected err:XC0036 but err:XD0036 was raised.

* XC0036: 
* XD0036: 

==== Error message


* XD0036

[role="pass partial"]
=== PASS Test err:XC0036 - #005
http://tests.xproc.org/tests/optional/err-c0036-005.xml

Wrong error: expected err:XC0036 but err:XD0036 was raised.

* XC0036: 
* XD0036: 

==== Error message


* XD0036

[role="pass partial"]
=== PASS Test err:XC0037 - #001
http://tests.xproc.org/tests/optional/err-c0037-001.xml

Wrong error: expected err:XC0037 but null was raised.

* XC0037: 
* null: 

[role="pass partial"]
=== PASS Test err:XC0037 - #002
http://tests.xproc.org/tests/optional/err-c0037-002.xml

Wrong error: expected err:XC0037 but null was raised.

* XC0037: 
* null: 

[role="pass partial"]
=== PASS Test err:XC0037 - #003
http://tests.xproc.org/tests/optional/err-c0037-003.xml

Wrong error: expected err:XC0037 but null was raised.

* XC0037: 
* null: 

[role="pass"]
=== PASS Test err:XC0053 - #001
http://tests.xproc.org/tests/optional/err-c0053-001.xml


==== Error message


* XProc error err:XC0053

[role="pass"]
=== PASS Test err:XC0053 - #002
http://tests.xproc.org/tests/optional/err-c0053-002.xml


==== Error message


* XC0053

[role="pass"]
=== PASS Test err:XC0053 - #003
http://tests.xproc.org/tests/optional/err-c0053-003.xml


==== Error message


* XC0053

[role="pass"]
=== PASS Test err:XC0053 - #004
http://tests.xproc.org/tests/optional/err-c0053-004.xml


==== Error message


* XProc error err:XC0053

[role="pass"]
=== PASS Test err:XC0054 - #001
http://tests.xproc.org/tests/optional/err-c0054-001.xml


==== Error message


* XC0054

[role="pass partial"]
=== PASS Test err:XC0057 - #001
http://tests.xproc.org/tests/optional/err-c0057-001.xml

Wrong error: expected err:XC0057 but null was raised.

* XC0057: 
* null: 

[role="pass"]
=== PASS Test err:XC0060 - #001
http://tests.xproc.org/tests/optional/err-c0060-001.xml


==== Error message


* XC0060

[role="pass"]
=== PASS Test err:XC0061 - #001
http://tests.xproc.org/tests/optional/err-c0061-001.xml


==== Error message


* XC0061

[role="pass"]
=== PASS Test err:XC0063 - #001
http://tests.xproc.org/tests/optional/err-c0063-001.xml


==== Error message


* XC0063

[role="pass"]
=== PASS Test err:XC0063 - #002
http://tests.xproc.org/tests/optional/err-c0063-002.xml


==== Error message


* XC0063

[role="pass"]
=== PASS Test err:XC0064 - #001
http://tests.xproc.org/tests/optional/err-c0064-001.xml


==== Error message


* XC0064

[role="pass"]
=== PASS Test err:XC0066 - #001
http://tests.xproc.org/tests/optional/err-c0066-001.xml


==== Error message


* XC0066

[role="pass"]
=== PASS Test err:XC0066 - #002
http://tests.xproc.org/tests/optional/err-c0066-002.xml


==== Error message


* XC0066

[role="pass"]
=== PASS Test exec-001
http://tests.xproc.org/tests/optional/exec-001.xml


[role="pass"]
=== PASS Test exec-002
http://tests.xproc.org/tests/optional/exec-002.xml


[role="pass"]
=== PASS Test exec-003
http://tests.xproc.org/tests/optional/exec-003.xml


[role="pass"]
=== PASS Test exec-004
http://tests.xproc.org/tests/optional/exec-004.xml


[role="pass"]
=== PASS Test exec-005
http://tests.xproc.org/tests/optional/exec-005.xml


[role="pass"]
=== PASS Test exec-006
http://tests.xproc.org/tests/optional/exec-006.xml


[role="pass"]
=== PASS Test exec-007
http://tests.xproc.org/tests/optional/exec-007.xml


[role="pass"]
=== PASS Test exec-008
http://tests.xproc.org/tests/optional/exec-008.xml


[role="pass"]
=== PASS Test exec-009
http://tests.xproc.org/tests/optional/exec-009.xml


[role="pass"]
=== PASS Test exec-010
http://tests.xproc.org/tests/optional/exec-010.xml


[role="pass"]
=== PASS Test exec-011
http://tests.xproc.org/tests/optional/exec-011.xml


[role="pass"]
=== PASS Test exec-012
http://tests.xproc.org/tests/optional/exec-012.xml


[role="pass"]
=== PASS Test exec-013
http://tests.xproc.org/tests/optional/exec-013.xml


[role="pass"]
=== PASS Test exec-014
http://tests.xproc.org/tests/optional/exec-014.xml


[role="pass"]
=== PASS Test exec-015
http://tests.xproc.org/tests/optional/exec-015.xml


==== Error message


* XD0006

[role="pass"]
=== PASS Test exec-016
http://tests.xproc.org/tests/optional/exec-016.xml


[role="pass"]
=== PASS Test exec-017
http://tests.xproc.org/tests/optional/exec-017.xml


[role="pass"]
=== PASS Test hash-001
http://tests.xproc.org/tests/optional/hash-001.xml


[role="pass"]
=== PASS Test hash-002
http://tests.xproc.org/tests/optional/hash-002.xml


[role="pass"]
=== PASS Test hash-003
http://tests.xproc.org/tests/optional/hash-003.xml


[role="pass"]
=== PASS Test hash-004
http://tests.xproc.org/tests/optional/hash-004.xml


[role="pass"]
=== PASS Test hash-005
http://tests.xproc.org/tests/optional/hash-005.xml


[role="pass"]
=== PASS Test hash-006
http://tests.xproc.org/tests/optional/hash-006.xml


[role="pass"]
=== PASS Test p:in-scope-names #001
http://tests.xproc.org/tests/optional/in-scope-names-001.xml


[role="pass"]
=== PASS Test p:in-scope-names #002
http://tests.xproc.org/tests/optional/in-scope-names-002.xml


[role="pass"]
=== PASS Test psvi-required-001.xml
http://tests.xproc.org/tests/optional/psvi-required-001.xml


[role="pass"]
=== PASS Test p:template-001
http://tests.xproc.org/tests/optional/template-001.xml


[role="pass"]
=== PASS Test p:template-002
http://tests.xproc.org/tests/optional/template-002.xml


[role="pass"]
=== PASS Test p:template-003
http://tests.xproc.org/tests/optional/template-003.xml


[role="pass"]
=== PASS Test p:template-004
http://tests.xproc.org/tests/optional/template-004.xml


==== Error message


* XC0067

[role="pass"]
=== PASS Test p:template-005
http://tests.xproc.org/tests/optional/template-005.xml


==== Error message


* XC0067

[role="pass"]
=== PASS Test p:template-006
http://tests.xproc.org/tests/optional/template-006.xml


==== Error message


* XC0067

[role="pass"]
=== PASS Test p:template-007
http://tests.xproc.org/tests/optional/template-007.xml


==== Error message


* XC0067

[role="pass"]
=== PASS Test p:template-008
http://tests.xproc.org/tests/optional/template-008.xml


[role="pass"]
=== PASS Test p:template-009
http://tests.xproc.org/tests/optional/template-009.xml


[role="pass"]
=== PASS Test p:template-010
http://tests.xproc.org/tests/optional/template-010.xml


[role="pass"]
=== PASS Test p:template-011
http://tests.xproc.org/tests/optional/template-011.xml


[role="pass"]
=== PASS Test p:template-012
http://tests.xproc.org/tests/optional/template-012.xml


==== Error message


* XC0067

[role="pass"]
=== PASS Test p:template-013
http://tests.xproc.org/tests/optional/template-013.xml


==== Error message


* XC0068

[role="pass partial"]
=== PASS Test p:template-014
http://tests.xproc.org/tests/optional/template-014.xml

Wrong error: expected err:XC0026 but err:XD0026 was raised.

* XC0026: 
* XD0026: 

==== Error message


* Expression refers to context when none is available: /doc/p

[role="pass"]
=== PASS Test p:template-015
http://tests.xproc.org/tests/optional/template-015.xml


[role="pass"]
=== PASS Test p:template-016
http://tests.xproc.org/tests/optional/template-016.xml


==== Error message


* XC0067

[role="pass"]
=== PASS Test p:template-016
http://tests.xproc.org/tests/optional/template-017.xml


==== Error message


* XC0067

[role="pass"]
=== PASS Test p:template-018
http://tests.xproc.org/tests/optional/template-018.xml


[role="pass"]
=== PASS Test uuid-001
http://tests.xproc.org/tests/optional/uuid-001.xml


[role="pass"]
=== PASS Test validrng-001
http://tests.xproc.org/tests/optional/validrng-001.xml


[role="pass"]
=== PASS Test validrng-002
http://tests.xproc.org/tests/optional/validrng-002.xml


[role="pass"]
=== PASS Test validrng-003
http://tests.xproc.org/tests/optional/validrng-003.xml


[role="pass"]
=== PASS Test validrng-004
http://tests.xproc.org/tests/optional/validrng-004.xml


[role="pass"]
=== PASS Test validrng-005
http://tests.xproc.org/tests/optional/validrng-005.xml


[role="pass"]
=== PASS Test validrng-006
http://tests.xproc.org/tests/optional/validrng-006.xml


[role="pass"]
=== PASS Test validrng-008
http://tests.xproc.org/tests/optional/validrng-008.xml


[role="pass"]
=== PASS Test validrng-009
http://tests.xproc.org/tests/optional/validrng-009.xml


[role="pass"]
=== PASS Test validsch-001
http://tests.xproc.org/tests/optional/validsch-001.xml


[role="pass"]
=== PASS Test validsch-002
http://tests.xproc.org/tests/optional/validsch-002.xml


[role="pass"]
=== PASS Test validsch-003
http://tests.xproc.org/tests/optional/validsch-003.xml


[role="pass"]
=== PASS Test validsch-004
http://tests.xproc.org/tests/optional/validsch-004.xml


[role="pass"]
=== PASS Test validsch-005
http://tests.xproc.org/tests/optional/validsch-005.xml


[role="pass"]
=== PASS Test validxsd-001
http://tests.xproc.org/tests/optional/validxsd-001.xml


[role="pass"]
=== PASS Test validxsd-002
http://tests.xproc.org/tests/optional/validxsd-002.xml


[role="pass"]
=== PASS Test validxsd-003
http://tests.xproc.org/tests/optional/validxsd-003.xml


[role="pass"]
=== PASS Test validxsd-004
http://tests.xproc.org/tests/optional/validxsd-004.xml


==== Error message


* XProc error err:XC0053

[role="pass"]
=== PASS Test validxsd-005
http://tests.xproc.org/tests/optional/validxsd-005.xml


[role="pass"]
=== PASS Test validxsd-006
http://tests.xproc.org/tests/optional/validxsd-006.xml


[role="pass"]
=== PASS Test validxsd-007
http://tests.xproc.org/tests/optional/validxsd-007.xml


[role="pass"]
=== PASS Test validxsd-008
http://tests.xproc.org/tests/optional/validxsd-008.xml


[role="pass"]
=== PASS Test validxsd-009
http://tests.xproc.org/tests/optional/validxsd-009.xml


[role="pass"]
=== PASS Test validxsd-010
http://tests.xproc.org/tests/optional/validxsd-010.xml


==== Error message


* XProc error err:XC0053

[role="pass"]
=== PASS Test validxsd-011
http://tests.xproc.org/tests/optional/validxsd-011.xml


==== Error message


* XProc error err:XC0053

[role="pass"]
=== PASS Test validxsd-012
http://tests.xproc.org/tests/optional/validxsd-012.xml


[role="pass"]
=== PASS Test validxsd-013
http://tests.xproc.org/tests/optional/validxsd-013.xml


[role="pass"]
=== PASS Test www-form-urldecode-001
http://tests.xproc.org/tests/optional/www-form-urldecode-001.xml


[role="pass"]
=== PASS Test www-form-urlencode-001
http://tests.xproc.org/tests/optional/www-form-urlencode-001.xml


[role="pass"]
=== PASS Test optional features of p:xinclude #001
http://tests.xproc.org/tests/optional/xinclude-001.xml


[role="pass"]
=== PASS Test optional features of p:xinclude #002
http://tests.xproc.org/tests/optional/xinclude-002.xml


[role="pass"]
=== PASS Test optional features of p:xinclude #003
http://tests.xproc.org/tests/optional/xinclude-003.xml


[role="pass"]
=== PASS Test optional features of p:xinclude #004
http://tests.xproc.org/tests/optional/xinclude-004.xml


[role="pass"]
=== PASS Test optional features of p:xinclude #005
http://tests.xproc.org/tests/optional/xinclude-005.xml


[role="pass"]
=== PASS Test optional features of p:xinclude #006
http://tests.xproc.org/tests/optional/xinclude-006.xml


[role="pass"]
=== PASS Test XQuery #001
http://tests.xproc.org/tests/optional/xquery-001.xml


[role="pass"]
=== PASS Test xquery-002
http://tests.xproc.org/tests/optional/xquery-002.xml


[role="pass"]
=== PASS Test xquery-003
http://tests.xproc.org/tests/optional/xquery-003.xml


[role="pass"]
=== PASS Test xquery-004
http://tests.xproc.org/tests/optional/xquery-004.xml


[role="pass"]
=== PASS Test XQuery #005
http://tests.xproc.org/tests/optional/xquery-005.xml


[role="pass"]
=== PASS Test xquery-006
http://tests.xproc.org/tests/optional/xquery-006.xml


[role="fail"]
=== FAIL Test XSL Formatter #001
http://tests.xproc.org/tests/optional/xsl-formatter-001.xml

[frame="topbot",cols="d<,d<"]
|====================
|Expected result:|Actual result:
l|<c:result xmlns:c="http://www.w3.org/ns/xproc-step"
          xmlns:t="http://xproc.org/ns/testsuite"
          xmlns:p="http://www.w3.org/ns/xproc"
          xmlns:err="http://www.w3.org/ns/xproc-error">file:///tmp/out.pdf</c:result>
l|<c:result xmlns:c="http://www.w3.org/ns/xproc-step">file:/tmp/out.pdf</c:result>
|====================

[role="pass"]
=== PASS Test XSLT 2.0 #001
http://tests.xproc.org/tests/optional/xslt2-001.xml


[role="pass"]
=== PASS Test XSLT 2.0 #002
http://tests.xproc.org/tests/optional/xslt2-002.xml


[role="pass"]
=== PASS Test XSLT 2.0 #003
http://tests.xproc.org/tests/optional/xslt2-003.xml



== Extension tests (Revision 633)

Passed 1 of 1 tests (100.00%).

[role="pass partial"]
=== PASS Test extension elements and attributes
http://tests.xproc.org/tests/extension/unimpl-001.xml

Wrong error: expected err:XD0017 but null was raised.

* XD0017: 
* null: 


== XML Calabash extension tests

Passed 25 of 26 tests (96.15%).

[role="pass"]
=== PASS Test ml:adhoc-query-001
http://xmlcalabash.com/tests/adhoc-query-001.xml


[role="pass"]
=== PASS Test cx:collection-manager
http://xmlcalabash.com/tests/collection-manager-001.xml


[role="pass"]
=== PASS Test cxu:compare
http://xmlcalabash.com/tests/compare-001.xml


[role="pass"]
=== PASS Test pxp:compress
http://xmlcalabash.com/tests/compress-001.xml


[role="pass"]
=== PASS Test cxf:copy
http://xmlcalabash.com/tests/copy-001.xml


[role="pass"]
=== PASS Test cxf:delete
http://xmlcalabash.com/tests/delete-001.xml


[role="pass"]
=== PASS Test cxf:head
http://xmlcalabash.com/tests/head-001.xml


[role="pass"]
=== PASS Test cxf:info
http://xmlcalabash.com/tests/info-001.xml


[role="pass"]
=== PASS Test cx:css-formatter
http://xmlcalabash.com/tests/css-formatter-001.xml


[role="pass"]
=== PASS Test cx:delta-xml
http://xmlcalabash.com/tests/delta-xml-001.xml


[role="pass"]
=== PASS Test cx:eval
http://xmlcalabash.com/tests/eval-001.xml


[role="pass"]
=== PASS Test cx:get-cookies
http://xmlcalabash.com/tests/get-cookies-001.xml


[role="pass"]
=== PASS Test ml:insert-document-001
http://xmlcalabash.com/tests/insert-document-001.xml


[role="pass"]
=== PASS Test ml:invoke-module-001
http://xmlcalabash.com/tests/invoke-module-001.xml


[role="pass"]
=== PASS Test cx:java-properties
http://xmlcalabash.com/tests/java-properties-001.xml


[role="pass"]
=== PASS Test message-001
http://xmlcalabash.com/tests/message-001.xml


[role="pass"]
=== PASS Test cx:metadata-extractor
http://xmlcalabash.com/tests/metadata-extractor-001.xml


[role="pass"]
=== PASS Test cx:namespace-delete
http://xmlcalabash.com/tests/namespace-delete-001.xml


[role="pass"]
=== PASS Test cx:pretty-print
http://xmlcalabash.com/tests/pretty-print-001.xml


[role="pass"]
=== PASS Test exf:cwd() #001
http://xmlcalabash.com/tests/exf-cwd-001.xml


[role="pass"]
=== PASS Test cx:set-cookies
http://xmlcalabash.com/tests/set-cookies-001.xml


[role="pass"]
=== PASS Test unzip-001
http://xmlcalabash.com/tests/unzip-001.xml


[role="pass"]
=== PASS Test unzip-002
http://xmlcalabash.com/tests/unzip-002.xml


[role="fail"]
=== FAIL Test cx:uri-info
http://xmlcalabash.com/tests/uri-info-001.xml

[frame="topbot",cols="d<,d<"]
|====================
|Expected result:|Actual result:
l|<c:uri-info xmlns:c="http://www.w3.org/ns/xproc-step"
            xmlns:t="http://xproc.org/ns/testsuite"
            href="http://tests.xproc.org/"
            status="200"
            readable="true"
            exists="true"
            uri="http://tests.xproc.org/"
            size="2598">
   <c:header name="Server" value="Apache"/>
   <c:header name="Accept-Ranges" value="bytes"/>
   <c:header name="Vary" value="Accept-Encoding"/>
   <c:header name="Content-Length" value="2598"/>
   <c:header name="Keep-Alive" value="timeout=2, max=99"/>
   <c:header name="Connection" value="Keep-Alive"/>
   <c:header name="Content-Type" value="text/html; charset=utf-8"/>
</c:uri-info>
l|<c:uri-info xmlns:c="http://www.w3.org/ns/xproc-step"
            href="http://tests.xproc.org/"
            status="200"
            readable="true"
            exists="true"
            uri="http://tests.xproc.org/"
            size="2598">
   <c:header name="Server" value="Apache"/>
   <c:header name="Accept-Ranges" value="bytes"/>
   <c:header name="Vary" value="Accept-Encoding"/>
   <c:header name="Content-Length" value="2598"/>
   <c:header name="Keep-Alive" value="timeout=2, max=98"/>
   <c:header name="Connection" value="Keep-Alive"/>
   <c:header name="Content-Type" value="text/html; charset=utf-8"/>
</c:uri-info>
|====================

[role="pass"]
=== PASS Test cx:rdf-load #001
http://xmlcalabash.com/tests/rdf-load-001.xml


[role="pass"]
=== PASS Test cx:sparql #001
http://xmlcalabash.com/tests/sparql-001.xml


